import '../../app_keys.dart';

const profileStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.noAccountForProfile:
        'ChÆ°a cÃ³ thÃ´ng tin tÃ i khoáº£n Ä‘á»ƒ táº£i há»“ sÆ¡.',
    AppKeys.noAccountForHistory:
        'ChÆ°a cÃ³ thÃ´ng tin tÃ i khoáº£n Ä‘á»ƒ táº£i lá»‹ch sá»­.',
    AppKeys.profileLoadFailed: 'Táº£i há»“ sÆ¡ tháº¥t báº¡i.',
    AppKeys.profileLoadErrorTitle: 'KhÃ´ng táº£i Ä‘Æ°á»£c há»“ sÆ¡',
    AppKeys.noProfileTitle: 'ChÆ°a cÃ³ há»“ sÆ¡',
    AppKeys.noProfileMessage:
        'Báº¡n cÃ³ thá»ƒ thÃªm há»“ sÆ¡ há»c táº­p cho bÃ©.',
    AppKeys.addProfile: 'ThÃªm há»“ sÆ¡',
    AppKeys.profileTitle: 'Há»“ SÆ¡',
    AppKeys.addProfileTitle: 'ThÃªm Há»“ SÆ¡',
    AppKeys.updateProfileTitle: 'Cáº­p Nháº­t Há»“ SÆ¡',
    AppKeys.updatingProfile: 'Äang cáº­p nháº­t há»“ sÆ¡...',
    AppKeys.school: 'TrÆ°á»ng Há»c',
    AppKeys.profileMenuTitle: 'Há»“ SÆ¡',
    AppKeys.profileMenuSubtitle: 'Xem vÃ  chá»‰nh sá»­a há»“ sÆ¡',
    AppKeys.imagePickFailed: 'KhÃ´ng thá»ƒ chá»n áº£nh lÃºc nÃ y.',
    AppKeys.profileOptionsMissingAccount:
        'ChÆ°a cÃ³ thÃ´ng tin tÃ i khoáº£n Ä‘á»ƒ táº£i lá»±a chá»n.',
    AppKeys.profileOptionsLoadFailed:
        'Táº£i lá»±a chá»n há»“ sÆ¡ tháº¥t báº¡i.',
    AppKeys.schoolOptionsLoadFailed: 'Táº£i danh sÃ¡ch trÆ°á»ng tháº¥t báº¡i.',
    AppKeys.reloadOptions: 'Táº£i láº¡i lá»±a chá»n',
    AppKeys.missingProfileName: 'Vui lÃ²ng nháº­p há» tÃªn.',
    AppKeys.missingProfileSelections: 'Vui lÃ²ng chá»n Ä‘á»§ thÃ´ng tin.',
    AppKeys.missingProfileId: 'Há»“ sÆ¡ nÃ y thiáº¿u profile_id.',
    AppKeys.profileCreateFailed:
        'KhÃ´ng thá»ƒ táº¡o há»“ sÆ¡. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.profileUpdateFailed:
        'KhÃ´ng thá»ƒ cáº­p nháº­t há»“ sÆ¡. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.deleteProfileTitle: 'XÃ³a há»“ sÆ¡?',
    AppKeys.deleteProfileMessage:
        'Báº¡n cÃ³ cháº¯c muá»‘n delete profile nÃ y khÃ´ng?',
    AppKeys.profileDeleted: 'ÄÃ£ xÃ³a há»“ sÆ¡.',
    AppKeys.profileDeleteFailed:
        'KhÃ´ng thá»ƒ xÃ³a há»“ sÆ¡. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.username: 'TÃªn NgÆ°á»i DÃ¹ng',
    AppKeys.fullName: 'Há» TÃªn',
    AppKeys.studentNameHint: 'Nháº­p há» tÃªn há»c sinh',
    AppKeys.parentProfileNameHint: 'Nháº­p há» tÃªn phá»¥ huynh',
    AppKeys.email: 'Email',
    AppKeys.parentProfilePhoneHint: 'Nháº­p sá»‘ Ä‘iá»‡n thoáº¡i phá»¥ huynh',
    AppKeys.parentProfileEmailHint: 'Nháº­p email phá»¥ huynh',
    AppKeys.grade: 'Lá»›p',
    AppKeys.program: 'ChÆ°Æ¡ng TrÃ¬nh',
    AppKeys.learningProgram: 'ChÆ°Æ¡ng TrÃ¬nh Há»c',
    AppKeys.semester: 'Há»c ká»³',
    AppKeys.chooseSchool: 'Chá»n trÆ°á»ng há»c',
    AppKeys.chooseGrade: 'Chá»n lá»›p',
    AppKeys.chooseProgram: 'Chá»n chÆ°Æ¡ng trÃ¬nh',
    AppKeys.chooseSemester: 'Chá»n há»c ká»³',
    AppKeys.noSchools: 'ChÆ°a cÃ³ trÆ°á»ng há»c nÃ o Ä‘á»ƒ hiá»ƒn thá»‹.',
    AppKeys.active: 'ACTIVE',
    AppKeys.profileRole: 'Vai trÃ²',
    AppKeys.roleStudent: 'Há»c sinh',
    AppKeys.roleParent: 'Phá»¥ huynh',
    AppKeys.roleTeacher: 'GiÃ¡o viÃªn',
    AppKeys.belovedChild: 'BÃ© yÃªu',
    AppKeys.notSelected: 'ChÆ°a chá»n',
    AppKeys.profileIdCopied: 'ÄÃ£ sao chÃ©p ID há»“ sÆ¡.',
    AppKeys.profileCodeLabel: 'MÃ£',
    AppKeys.profileCodeCopied: 'ÄÃ£ sao chÃ©p mÃ£ há»“ sÆ¡.',
    AppKeys.profileTeacherNameHint: 'Nháº­p tÃªn giÃ¡o viÃªn',
    AppKeys.profileIdTypeLabel: 'Loáº¡i giáº¥y tá»',
    AppKeys.profileIdTypeHint: 'Chá»n loáº¡i giáº¥y tá»',
    AppKeys.profileIdTypeNone: 'KhÃ´ng chá»n',
    AppKeys.profileIdValueLabel: 'ID',
    AppKeys.profileTeacherIdHint:
        'Nháº­p mÃ£ cÃ¡n bá»™ giÃ¡o viÃªn hoáº·c sá»‘ Ä‘á»‹nh danh',
    AppKeys.profileStudentIdHint: 'Nháº­p mÃ£ há»c báº¡',
    AppKeys.idTypeMoetLabel: 'MÃ£ há»c báº¡',
    AppKeys.idTypeTeacherMoetLabel: 'MÃ£ cÃ¡n bá»™ giÃ¡o viÃªn',
    AppKeys.idTypePublicIdLabel: 'Sá»‘ Ä‘á»‹nh danh cÃ¡ nhÃ¢n',
    AppKeys.noAccountForGrades:
        'ChÆ°a cÃ³ thÃ´ng tin tÃ i khoáº£n Ä‘á»ƒ táº£i danh sÃ¡ch lá»›p.',
    AppKeys.gradeLoadFailed: 'Táº£i danh sÃ¡ch lá»›p tháº¥t báº¡i.',
    AppKeys.gradeQuestionTitle: 'BÃ© Ä‘ang há»c lá»›p\nmáº¥y nhá»‰?',
  },
  'en': {
    AppKeys.noAccountForProfile: 'No account information to load profiles.',
    AppKeys.noAccountForHistory: 'No account information to load history.',
    AppKeys.profileLoadFailed: 'Failed to load profiles.',
    AppKeys.profileLoadErrorTitle: 'Could not load profiles',
    AppKeys.noProfileTitle: 'No profile yet',
    AppKeys.noProfileMessage: 'You can add a learning profile for your child.',
    AppKeys.addProfile: 'Add profile',
    AppKeys.profileTitle: 'Profile',
    AppKeys.addProfileTitle: 'Add Profile',
    AppKeys.updateProfileTitle: 'Update Profile',
    AppKeys.updatingProfile: 'Updating profile...',
    AppKeys.school: 'School',
    AppKeys.profileMenuTitle: 'Profile',
    AppKeys.profileMenuSubtitle: 'View and edit profiles',
    AppKeys.imagePickFailed: 'Could not choose an image now.',
    AppKeys.profileOptionsMissingAccount:
        'No account information to load options.',
    AppKeys.profileOptionsLoadFailed: 'Failed to load profile options.',
    AppKeys.schoolOptionsLoadFailed: 'Failed to load schools.',
    AppKeys.reloadOptions: 'Reload options',
    AppKeys.missingProfileName: 'Please enter a full name.',
    AppKeys.missingProfileSelections: 'Please select all required information.',
    AppKeys.missingProfileId: 'This profile is missing profile_id.',
    AppKeys.profileCreateFailed: 'Could not create profile. Please try again.',
    AppKeys.profileUpdateFailed: 'Could not update profile. Please try again.',
    AppKeys.deleteProfileTitle: 'Delete profile?',
    AppKeys.deleteProfileMessage:
        'Are you sure you want to delete this profile?',
    AppKeys.profileDeleted: 'Profile deleted.',
    AppKeys.profileDeleteFailed: 'Could not delete profile. Please try again.',
    AppKeys.username: 'Username',
    AppKeys.fullName: 'Full Name',
    AppKeys.studentNameHint: "Enter student's full name",
    AppKeys.parentProfileNameHint: "Enter parent's full name",
    AppKeys.email: 'Email',
    AppKeys.parentProfilePhoneHint: "Enter parent's phone number",
    AppKeys.parentProfileEmailHint: "Enter parent's email",
    AppKeys.grade: 'Grade',
    AppKeys.program: 'Program',
    AppKeys.learningProgram: 'Learning Program',
    AppKeys.semester: 'Semester',
    AppKeys.chooseSchool: 'Choose school',
    AppKeys.chooseGrade: 'Choose grade',
    AppKeys.chooseProgram: 'Choose program',
    AppKeys.chooseSemester: 'Choose semester',
    AppKeys.noSchools: 'No schools to show.',
    AppKeys.active: 'ACTIVE',
    AppKeys.profileRole: 'Role',
    AppKeys.roleStudent: 'Student',
    AppKeys.roleParent: 'Parent',
    AppKeys.roleTeacher: 'Teacher',
    AppKeys.belovedChild: 'Little learner',
    AppKeys.notSelected: 'Not selected',
    AppKeys.profileIdCopied: 'Profile ID copied.',
    AppKeys.profileCodeLabel: 'Code',
    AppKeys.profileCodeCopied: 'Profile code copied.',
    AppKeys.profileTeacherNameHint: 'Enter teacher name',
    AppKeys.profileIdTypeLabel: 'Document type',
    AppKeys.profileIdTypeHint: 'Choose document type',
    AppKeys.profileIdTypeNone: 'None',
    AppKeys.profileIdValueLabel: 'ID',
    AppKeys.profileTeacherIdHint: 'Enter teacher staff ID or personal ID',
    AppKeys.profileStudentIdHint: 'Enter student record ID',
    AppKeys.idTypeMoetLabel: 'Student record ID',
    AppKeys.idTypeTeacherMoetLabel: 'Teacher staff ID',
    AppKeys.idTypePublicIdLabel: 'Personal identification number',
    AppKeys.noAccountForGrades: 'No account information to load grades.',
    AppKeys.gradeLoadFailed: 'Failed to load grades.',
    AppKeys.gradeQuestionTitle: 'Which grade is your\nchild in?',
  },
};
