import '../../app_keys.dart';

const profileStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.noAccountForProfile: 'Chưa có thông tin tài khoản để tải hồ sơ.',
    AppKeys.noAccountForHistory: 'Chưa có thông tin tài khoản để tải lịch sử.',
    AppKeys.profileLoadFailed: 'Tải hồ sơ thất bại.',
    AppKeys.profileLoadErrorTitle: 'Không tải được hồ sơ',
    AppKeys.noProfileTitle: 'Chưa có hồ sơ',
    AppKeys.noProfileMessage: 'Bạn có thể thêm hồ sơ học tập cho bé.',
    AppKeys.addProfile: 'Thêm hồ sơ',
    AppKeys.profileTitle: 'Hồ Sơ',
    AppKeys.addProfileTitle: 'Thêm Hồ Sơ',
    AppKeys.updateProfileTitle: 'Cập Nhật Hồ Sơ',
    AppKeys.updatingProfile: 'Đang cập nhật hồ sơ...',
    AppKeys.school: 'Trường Học',
    AppKeys.profileMenuTitle: 'Hồ Sơ',
    AppKeys.profileMenuSubtitle: 'Xem và chỉnh sửa hồ sơ',
    AppKeys.imagePickFailed: 'Không thể chọn ảnh lúc này.',
    AppKeys.profileOptionsMissingAccount:
        'Chưa có thông tin tài khoản để tải lựa chọn.',
    AppKeys.profileOptionsLoadFailed: 'Tải lựa chọn hồ sơ thất bại.',
    AppKeys.schoolOptionsLoadFailed: 'Tải danh sách trường thất bại.',
    AppKeys.reloadOptions: 'Tải lại lựa chọn',
    AppKeys.missingProfileName: 'Vui lòng nhập họ tên.',
    AppKeys.missingProfileSelections: 'Vui lòng chọn đủ thông tin.',
    AppKeys.missingProfileId: 'Hồ sơ này thiếu profile_id.',
    AppKeys.profileCreateFailed: 'Không thể tạo hồ sơ. Vui lòng thử lại.',
    AppKeys.profileUpdateFailed: 'Không thể cập nhật hồ sơ. Vui lòng thử lại.',
    AppKeys.deleteProfileTitle: 'Xóa hồ sơ?',
    AppKeys.deleteProfileMessage: 'Bạn có chắc muốn delete profile này không?',
    AppKeys.profileDeleted: 'Đã xóa hồ sơ.',
    AppKeys.profileDeleteFailed: 'Không thể xóa hồ sơ. Vui lòng thử lại.',
    AppKeys.username: 'Tên Người Dùng',
    AppKeys.fullName: 'Họ Tên',
    AppKeys.studentNameHint: 'Nhập họ tên học sinh',
    AppKeys.parentProfileNameHint: 'Nhập họ tên phụ huynh',
    AppKeys.email: 'Email',
    AppKeys.parentProfilePhoneHint: 'Nhập số điện thoại phụ huynh',
    AppKeys.parentProfileEmailHint: 'Nhập email phụ huynh',
    AppKeys.grade: 'Lớp',
    AppKeys.program: 'Chương Trình',
    AppKeys.learningProgram: 'Chương Trình Học',
    AppKeys.semester: 'Học kỳ',
    AppKeys.chooseSchool: 'Chọn trường học',
    AppKeys.chooseGrade: 'Chọn lớp',
    AppKeys.chooseProgram: 'Chọn chương trình',
    AppKeys.chooseSemester: 'Chọn học kỳ',
    AppKeys.noSchools: 'Chưa có trường học nào để hiển thị.',
    AppKeys.active: 'ACTIVE',
    AppKeys.profileRole: 'Vai trò',
    AppKeys.roleStudent: 'Học sinh',
    AppKeys.roleParent: 'Phụ huynh',
    AppKeys.roleTeacher: 'Giáo viên',
    AppKeys.belovedChild: 'Bé yêu',
    AppKeys.notSelected: 'Chưa chọn',
    AppKeys.profileIdCopied: 'Đã sao chép ID hồ sơ.',
    AppKeys.profileCodeLabel: 'Mã',
    AppKeys.profileCodeCopied: 'Đã sao chép mã hồ sơ.',
    AppKeys.profileTeacherNameHint: 'Nhập tên giáo viên',
    AppKeys.profileIdTypeLabel: 'Loại giấy tờ',
    AppKeys.profileIdTypeHint: 'Chọn loại giấy tờ',
    AppKeys.profileIdTypeNone: 'Không chọn',
    AppKeys.profileIdValueLabel: 'ID',
    AppKeys.profileTeacherIdHint: 'Nhập mã cán bộ giáo viên hoặc số định danh',
    AppKeys.profileStudentIdHint: 'Nhập mã học bạ',
    AppKeys.idTypeMoetLabel: 'Mã học bạ',
    AppKeys.idTypeTeacherMoetLabel: 'Mã cán bộ giáo viên',
    AppKeys.idTypePublicIdLabel: 'Số định danh cá nhân',
    AppKeys.noAccountForGrades:
        'Chưa có thông tin tài khoản để tải danh sách lớp.',
    AppKeys.gradeLoadFailed: 'Tải danh sách lớp thất bại.',
    AppKeys.gradeQuestionTitle: 'Bé đang học lớp\nmấy nhỉ?',
  },
  'en': {
    AppKeys.noAccountForProfile: 'No account information to load profiles.',
    AppKeys.noAccountForHistory: 'No account information to load history.',
    AppKeys.profileLoadFailed: 'Failed to load profiles.',
    AppKeys.profileLoadErrorTitle: 'Could not load profiles',
    AppKeys.noProfileTitle: 'No profile yet',
    AppKeys.noProfileMessage: 'You can add a learning profile for your child.',
    AppKeys.addProfile: 'Add profile',
    AppKeys.profileTitle: 'Profile',
    AppKeys.addProfileTitle: 'Add Profile',
    AppKeys.updateProfileTitle: 'Update Profile',
    AppKeys.updatingProfile: 'Updating profile...',
    AppKeys.school: 'School',
    AppKeys.profileMenuTitle: 'Profile',
    AppKeys.profileMenuSubtitle: 'View and edit profiles',
    AppKeys.imagePickFailed: 'Could not choose an image now.',
    AppKeys.profileOptionsMissingAccount:
        'No account information to load options.',
    AppKeys.profileOptionsLoadFailed: 'Failed to load profile options.',
    AppKeys.schoolOptionsLoadFailed: 'Failed to load schools.',
    AppKeys.reloadOptions: 'Reload options',
    AppKeys.missingProfileName: 'Please enter a full name.',
    AppKeys.missingProfileSelections: 'Please select all required information.',
    AppKeys.missingProfileId: 'This profile is missing profile_id.',
    AppKeys.profileCreateFailed: 'Could not create profile. Please try again.',
    AppKeys.profileUpdateFailed: 'Could not update profile. Please try again.',
    AppKeys.deleteProfileTitle: 'Delete profile?',
    AppKeys.deleteProfileMessage:
        'Are you sure you want to delete this profile?',
    AppKeys.profileDeleted: 'Profile deleted.',
    AppKeys.profileDeleteFailed: 'Could not delete profile. Please try again.',
    AppKeys.username: 'Username',
    AppKeys.fullName: 'Full Name',
    AppKeys.studentNameHint: "Enter student's full name",
    AppKeys.parentProfileNameHint: "Enter parent's full name",
    AppKeys.email: 'Email',
    AppKeys.parentProfilePhoneHint: "Enter parent's phone number",
    AppKeys.parentProfileEmailHint: "Enter parent's email",
    AppKeys.grade: 'Grade',
    AppKeys.program: 'Program',
    AppKeys.learningProgram: 'Learning Program',
    AppKeys.semester: 'Semester',
    AppKeys.chooseSchool: 'Choose school',
    AppKeys.chooseGrade: 'Choose grade',
    AppKeys.chooseProgram: 'Choose program',
    AppKeys.chooseSemester: 'Choose semester',
    AppKeys.noSchools: 'No schools to show.',
    AppKeys.active: 'ACTIVE',
    AppKeys.profileRole: 'Role',
    AppKeys.roleStudent: 'Student',
    AppKeys.roleParent: 'Parent',
    AppKeys.roleTeacher: 'Teacher',
    AppKeys.belovedChild: 'Little learner',
    AppKeys.notSelected: 'Not selected',
    AppKeys.profileIdCopied: 'Profile ID copied.',
    AppKeys.profileCodeLabel: 'Code',
    AppKeys.profileCodeCopied: 'Profile code copied.',
    AppKeys.profileTeacherNameHint: 'Enter teacher name',
    AppKeys.profileIdTypeLabel: 'Document type',
    AppKeys.profileIdTypeHint: 'Choose document type',
    AppKeys.profileIdTypeNone: 'None',
    AppKeys.profileIdValueLabel: 'ID',
    AppKeys.profileTeacherIdHint: 'Enter teacher staff ID or personal ID',
    AppKeys.profileStudentIdHint: 'Enter student record ID',
    AppKeys.idTypeMoetLabel: 'Student record ID',
    AppKeys.idTypeTeacherMoetLabel: 'Teacher staff ID',
    AppKeys.idTypePublicIdLabel: 'Personal identification number',
    AppKeys.noAccountForGrades: 'No account information to load grades.',
    AppKeys.gradeLoadFailed: 'Failed to load grades.',
    AppKeys.gradeQuestionTitle: 'Which grade is your\nchild in?',
  },
};
