import '../../app_keys.dart';

const welcomeStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.welcomeLogin: 'ĐĂNG NHẬP',
    AppKeys.welcomeSignup: 'ĐĂNG KÝ',
    AppKeys.welcomeTryIt: 'Thử Ngay!',
    AppKeys.start: 'BẮT ĐẦU',
    AppKeys.welcomeTaglineMath: 'Toán ',
    AppKeys.welcomeTaglineStudyAssessment: 'Học & Đánh Giá',
    AppKeys.welcomeAssessmentTitle: 'Đánh Giá',
    AppKeys.welcomeAssessmentSubtitle: 'Đánh giá năng lực',
    AppKeys.welcomeLearnMathTitle: 'Học Toán',
    AppKeys.welcomeLearnMathSubtitle: 'Đến lớp 5',
    AppKeys.welcomeParentTeacherTitle: 'Phụ Huynh/GV',
    AppKeys.welcomeParentTeacherSubtitle: 'Theo dõi tiến độ',
    AppKeys.welcomeGamesTitle: 'Game Toán',
    AppKeys.welcomeGamesSubtitle: 'Chơi và học',
  },
  'en': {
    AppKeys.welcomeLogin: 'LOGIN',
    AppKeys.welcomeSignup: 'SIGNUP',
    AppKeys.welcomeTryIt: 'Try It Now!',
    AppKeys.start: 'START',
    AppKeys.welcomeTaglineMath: 'Math ',
    AppKeys.welcomeTaglineStudyAssessment: 'Assess & Learn',
    AppKeys.welcomeAssessmentTitle: 'Assessments',
    AppKeys.welcomeAssessmentSubtitle: 'Skills assessment',
    AppKeys.welcomeLearnMathTitle: 'Learn Math',
    AppKeys.welcomeLearnMathSubtitle: 'Up to grade 5',
    AppKeys.welcomeParentTeacherTitle: 'Parents & Teachers',
    AppKeys.welcomeParentTeacherSubtitle: 'Track progress',
    AppKeys.welcomeGamesTitle: 'Math Games',
    AppKeys.welcomeGamesSubtitle: 'Play and learn',
  },
};
