import '../../app_keys.dart';

const welcomeStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.welcomeTitlePrefix: 'Học Toán cùng\n',
    AppKeys.welcomeTitleN: 'NUMI',
    AppKeys.welcomeSubtitlePrefix: 'Hãy cùng Numi',
    AppKeys.welcomeSubtitle: 'trở thành "phù thủy" tính toán nhé!',
    AppKeys.welcomeLogin: 'Đăng Nhập',
    AppKeys.start: 'BẮT ĐẦU',
    AppKeys.welcomeTaglineMath: 'Toán ',
    AppKeys.welcomeTaglineStudyAssessment: 'Học & Đánh giá',
    AppKeys.welcomeAssessmentTitle: 'Đánh Giá',
    AppKeys.welcomeAssessmentSubtitle: 'Đánh giá năng lực',
    AppKeys.welcomeLearnMathTitle: 'Học Toán',
    AppKeys.welcomeLearnMathSubtitle: 'Đến lớp 5',
    AppKeys.welcomeParentTeacherTitle: 'Phụ Huynh/GV',
    AppKeys.welcomeParentTeacherSubtitle: 'Theo dõi tiến độ',
    AppKeys.welcomeGamesTitle: 'Game Toán',
    AppKeys.welcomeGamesSubtitle: 'Chơi và học',
  },
  'en': {
    AppKeys.welcomeTitlePrefix: 'Learn math with\n',
    AppKeys.welcomeTitleN: 'NUMI',
    AppKeys.welcomeSubtitlePrefix: 'Join Numi',
    AppKeys.welcomeSubtitle: 'and become a math wizard!',
    AppKeys.welcomeLogin: 'LOG IN',
    AppKeys.start: 'START',
    AppKeys.welcomeTaglineMath: 'Math ',
    AppKeys.welcomeTaglineStudyAssessment: 'Learn & assessment',
    AppKeys.welcomeAssessmentTitle: 'Assessments',
    AppKeys.welcomeAssessmentSubtitle: 'Skills assessment',
    AppKeys.welcomeLearnMathTitle: 'Learn Math',
    AppKeys.welcomeLearnMathSubtitle: 'Up to grade 5',
    AppKeys.welcomeParentTeacherTitle: 'Parents & Teachers',
    AppKeys.welcomeParentTeacherSubtitle: 'Track progress',
    AppKeys.welcomeGamesTitle: 'Math Games',
    AppKeys.welcomeGamesSubtitle: 'Play and learn',
  },
};
