name: numi_flutter
description: NUMI mobile onboarding and phone verification app.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 2.4.13
  json_serializable: 6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env

