import '../../app_keys.dart';

const teacherClassroomExerciseStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.teacherAssignmentDefaultChapter: 'Phép cộng',
    AppKeys.teacherAssignmentDefaultLesson: 'Các số trong phạm vi 20',
    AppKeys.teacherAssignments: 'Bài Tập',
    AppKeys.teacherAssessments: 'Đánh Giá',
    AppKeys.teacherCreatedAssignments: 'Bài tập đã tạo',
    AppKeys.teacherCreatedAssessments: 'Đánh giá đã tạo',
    AppKeys.teacherAssignmentSearchHint: 'Tìm kiếm ...',
    AppKeys.teacherAssignmentNewest: 'Mới nhất',
    AppKeys.teacherAssignmentListLoadFailed: 'Tải danh sách bài tập thất bại.',
    AppKeys.teacherAssessmentListLoadFailed: 'Tải danh sách đánh giá thất bại.',
    AppKeys.teacherAssignmentDetailLoadFailed: 'Tải chi tiết bài tập thất bại.',
    AppKeys.teacherAssessmentDetailLoadFailed:
        'Tải chi tiết đánh giá thất bại.',
    AppKeys.teacherAssignmentCreateFailed:
        'Không thể tạo bài tập. Vui lòng thử lại.',
    AppKeys.teacherAssessmentCreateFailed:
        'Không thể tạo đánh giá. Vui lòng thử lại.',
    AppKeys.teacherNoAssignments: 'Chưa có bài tập nào.',
    AppKeys.teacherNoAssessments: 'Chưa có đánh giá nào.',
    AppKeys.teacherAssignmentId: 'ID: {id}',
    AppKeys.teacherAssignmentDueLabel: 'HẠN NỘP',
    AppKeys.teacherAssignmentQuestionCountLabel: 'SỐ CÂU HỎI',
    AppKeys.teacherAssignmentQuestionCountFormat: '{count} câu',
    AppKeys.teacherAssignmentQuestionContent: 'Nội dung câu hỏi',
    AppKeys.teacherAssignmentQuestionNumber: 'Câu {number}',
    AppKeys.teacherAssignmentEquationPrompt:
        'Giải phương trình x² - 5x + 6 = 0.',
    AppKeys.teacherAssignmentClassOption: 'Lớp 2A1',
    AppKeys.teacherAssignmentSelectClass: 'Chọn lớp học',
    AppKeys.teacherAssignmentClassSummaryName: 'Toán A1',
    AppKeys.teacherAssignmentClassStudentCount: '32 Học Sinh',
    AppKeys.teacherAssignmentClassStudentCountFormat: '{count} Học Sinh',
    AppKeys.teacherAssignmentClassGrade: 'Lớp 1',
    AppKeys.teacherAssignmentTitleHint: 'Tiêu Đề',
    AppKeys.teacherAssessmentTitleHint: 'Tiêu Đề Đánh Giá',
    AppKeys.teacherAssignmentTitleRequired: 'Vui lòng nhập tiêu đề bài tập.',
    AppKeys.teacherAssessmentTitleRequired: 'Vui lòng nhập tiêu đề đánh giá.',
    AppKeys.teacherAssignmentProgramLabel: 'Chương Trình',
    AppKeys.teacherAssignmentProgramRequired: 'Vui lòng chọn chương trình.',
    AppKeys.teacherAssignmentPublishLabel: 'Hiển thị',
    AppKeys.teacherAssignmentVisibilityPublic: 'PUBLIC',
    AppKeys.teacherAssignmentVisibilityPrivate: 'PRIVATE',
    AppKeys.teacherAssignmentDeadline: 'Hạn Nộp',
    AppKeys.teacherAssignmentStartDateHint: 'Ngày giờ bắt đầu',
    AppKeys.teacherAssignmentEndDateHint: 'Ngày giờ kết thúc',
    AppKeys.teacherAssignmentStartDateRequired: 'Vui lòng chọn ngày bắt đầu.',
    AppKeys.teacherAssignmentEndDateRequired: 'Vui lòng chọn ngày kết thúc.',
    AppKeys.teacherAssignmentFutureDateRequired:
        'Ngày đã chọn phải ở tương lai.',
    AppKeys.teacherAssignmentEndAfterStart:
        'Ngày kết thúc phải sau ngày bắt đầu.',
    AppKeys.teacherAssignmentChapterLabel: 'Chương Học',
    AppKeys.teacherAssignmentLessonLabel: 'Bài Học',
    AppKeys.teacherAssignmentDescriptionLabel: 'Mô tả',
    AppKeys.teacherAssignmentDescriptionHint: 'Mô tả thêm',
    AppKeys.teacherAssessmentDescriptionHint: 'Mô tả đánh giá',
    AppKeys.teacherAssignmentCreated: 'Đã tạo bài tập.',
    AppKeys.teacherAssessmentCreated: 'Đã tạo đánh giá.',
  },
  'en': {
    AppKeys.teacherAssignmentDefaultChapter: 'Addition',
    AppKeys.teacherAssignmentDefaultLesson: 'Numbers within 20',
    AppKeys.teacherAssignments: 'Assignments',
    AppKeys.teacherAssessments: 'Assessment',
    AppKeys.teacherCreatedAssignments: 'Created assignments',
    AppKeys.teacherCreatedAssessments: 'Created assessments',
    AppKeys.teacherAssignmentSearchHint: 'Search ...',
    AppKeys.teacherAssignmentNewest: 'Newest',
    AppKeys.teacherAssignmentListLoadFailed: 'Failed to load assignments.',
    AppKeys.teacherAssessmentListLoadFailed: 'Failed to load assessments.',
    AppKeys.teacherAssignmentDetailLoadFailed:
        'Failed to load assignment details.',
    AppKeys.teacherAssessmentDetailLoadFailed:
        'Failed to load assessment details.',
    AppKeys.teacherAssignmentCreateFailed:
        'Could not create assignment. Please try again.',
    AppKeys.teacherAssessmentCreateFailed:
        'Could not create assessment. Please try again.',
    AppKeys.teacherNoAssignments: 'No assignments yet.',
    AppKeys.teacherNoAssessments: 'No assessments yet.',
    AppKeys.teacherAssignmentId: 'ID: {id}',
    AppKeys.teacherAssignmentDueLabel: 'DUE DATE',
    AppKeys.teacherAssignmentQuestionCountLabel: 'Questions',
    AppKeys.teacherAssignmentQuestionCountFormat: '{count} questions',
    AppKeys.teacherAssignmentQuestionContent: 'Question content',
    AppKeys.teacherAssignmentQuestionNumber: 'Question {number}',
    AppKeys.teacherAssignmentEquationPrompt:
        'Solve the equation x² - 5x + 6 = 0.',
    AppKeys.teacherAssignmentClassOption: 'Class 2A1',
    AppKeys.teacherAssignmentSelectClass: 'Select classroom',
    AppKeys.teacherAssignmentClassSummaryName: 'Math A1',
    AppKeys.teacherAssignmentClassStudentCount: '32 Students',
    AppKeys.teacherAssignmentClassStudentCountFormat: '{count} Students',
    AppKeys.teacherAssignmentClassGrade: 'Grade 1',
    AppKeys.teacherAssignmentTitleHint: 'Title',
    AppKeys.teacherAssessmentTitleHint: 'Assessment title',
    AppKeys.teacherAssignmentTitleRequired: 'Please enter an assignment title.',
    AppKeys.teacherAssessmentTitleRequired: 'Please enter an assessment title.',
    AppKeys.teacherAssignmentProgramLabel: 'Program',
    AppKeys.teacherAssignmentProgramRequired: 'Please select a program.',
    AppKeys.teacherAssignmentPublishLabel: 'Visibility',
    AppKeys.teacherAssignmentVisibilityPublic: 'PUBLIC',
    AppKeys.teacherAssignmentVisibilityPrivate: 'PRIVATE',
    AppKeys.teacherAssignmentDeadline: 'Deadline',
    AppKeys.teacherAssignmentStartDateHint: 'Start date',
    AppKeys.teacherAssignmentEndDateHint: 'End date',
    AppKeys.teacherAssignmentStartDateRequired: 'Please select a start date.',
    AppKeys.teacherAssignmentEndDateRequired: 'Please select an end date.',
    AppKeys.teacherAssignmentFutureDateRequired:
        'The selected date must be in the future.',
    AppKeys.teacherAssignmentEndAfterStart:
        'End date must be after start date.',
    AppKeys.teacherAssignmentChapterLabel: 'Chapter',
    AppKeys.teacherAssignmentLessonLabel: 'Lesson',
    AppKeys.teacherAssignmentDescriptionLabel: 'Description',
    AppKeys.teacherAssignmentDescriptionHint: 'Additional description',
    AppKeys.teacherAssessmentDescriptionHint: 'Assessment description',
    AppKeys.teacherAssignmentCreated: 'Assignment created.',
    AppKeys.teacherAssessmentCreated: 'Assessment created.',
  },
};
