import '../../app_keys.dart';

const settingsStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.settingsTitle: 'CÃ i Äáº·t',
    AppKeys.accountTitle: 'TÃ i Khoáº£n',
    AppKeys.accountMenuTitle: 'TÃ i Khoáº£n',
    AppKeys.accountMenuSubtitle: 'Quáº£n lÃ½ thÃ´ng tin tÃ i khoáº£n',
    AppKeys.logout: 'Logout',
    AppKeys.logoutSubtitle: 'ÄÄƒng xuáº¥t khá»i tÃ i khoáº£n',
    AppKeys.passcodeMenuTitle: 'MÃ£ PIN',
    AppKeys.passcodeMenuSubtitleSet: 'Táº¡o mÃ£ PIN Ä‘á»ƒ khÃ³a á»©ng dá»¥ng',
    AppKeys.passcodeMenuSubtitleManage: 'Äá»•i hoáº·c xÃ³a mÃ£ PIN',
    AppKeys.createPasscodeTitle: 'Táº¡o MÃ£ PIN',
    AppKeys.confirmPasscodeTitle: 'Nháº­p Láº¡i MÃ£ PIN',
    AppKeys.unlockPasscodeTitle: 'Nháº­p MÃ£ PIN',
    AppKeys.verifyPasscodeTitle: 'XÃ¡c Minh MÃ£ PIN',
    AppKeys.createPasscodeSubtitle:
        'Táº¡o mÃ£ PIN Ä‘á»ƒ\nÄ‘Äƒng nháº­p nhanh chÃ³ng',
    AppKeys.confirmPasscodeSubtitle: 'Nháº­p láº¡i mÃ£ PIN Ä‘á»ƒ\nxÃ¡c nháº­n',
    AppKeys.unlockPasscodeSubtitle:
        'Nháº­p mÃ£ PIN Ä‘á»ƒ\nÄ‘Äƒng nháº­p nhanh chÃ³ng',
    AppKeys.verifyPasscodeSubtitle: 'Nháº­p mÃ£ PIN Ä‘á»ƒ\nxÃ¡c nháº­n',
    AppKeys.changePasscodeTitle: 'Äá»•i MÃ£ PIN',
    AppKeys.enterCurrentPasscodeTitle: 'Nháº­p MÃ£ PIN Hiá»‡n Táº¡i',
    AppKeys.passcodeContinue: 'Tiáº¿p Tá»¥c',
    AppKeys.passcodeUnlock: 'Má»Ÿ KhÃ³a',
    AppKeys.passcodeSkip: 'Bá» Qua',
    AppKeys.passcodeRemove: 'XÃ³a MÃ£ PIN',
    AppKeys.passcodeSetUp: 'Táº¡o MÃ£ PIN',
    AppKeys.passcodeChange: 'Äá»•i MÃ£ PIN',
    AppKeys.passcodeMismatch: 'MÃ£ PIN khÃ´ng khá»›p. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.passcodeIncorrect: 'MÃ£ PIN khÃ´ng Ä‘Ãºng. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.passcodeSaveFailed:
        'KhÃ´ng thá»ƒ lÆ°u mÃ£ PIN. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.passcodeSessionExpired:
        'PhiÃªn Ä‘Äƒng nháº­p Ä‘Ã£ háº¿t háº¡n. Vui lÃ²ng Ä‘Äƒng nháº­p láº¡i.',
    AppKeys.passcodeRemoveFailed:
        'KhÃ´ng thá»ƒ xÃ³a mÃ£ PIN. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.passcodeSet: 'ÄÃ£ táº¡o mÃ£ PIN.',
    AppKeys.passcodeChanged: 'ÄÃ£ Ä‘á»•i mÃ£ PIN.',
    AppKeys.passcodeRemoved: 'ÄÃ£ xÃ³a mÃ£ PIN.',
    AppKeys.missingAccount: 'Thiáº¿u thÃ´ng tin tÃ i khoáº£n.',
    AppKeys.accountNameRequired: 'Vui lÃ²ng nháº­p tÃªn tÃ i khoáº£n.',
    AppKeys.accountUpdated: 'ÄÃ£ cáº­p nháº­t tÃ i khoáº£n.',
    AppKeys.accountUpdateFailed: 'KhÃ´ng thá»ƒ cáº­p nháº­t tÃ i khoáº£n.',
    AppKeys.switchingProfile: 'Äang chuyá»ƒn há»“ sÆ¡...',
    AppKeys.switchingLanguage: 'Äang Ä‘á»•i ngÃ´n ngá»¯...',
  },
  'en': {
    AppKeys.settingsTitle: 'Settings',
    AppKeys.accountTitle: 'Account',
    AppKeys.accountMenuTitle: 'Account',
    AppKeys.accountMenuSubtitle: 'Manage account information',
    AppKeys.logout: 'Logout',
    AppKeys.logoutSubtitle: 'Sign out of your account',
    AppKeys.passcodeMenuTitle: 'Passcode',
    AppKeys.passcodeMenuSubtitleSet: 'Create a PIN to lock the app',
    AppKeys.passcodeMenuSubtitleManage: 'Change or remove your PIN',
    AppKeys.createPasscodeTitle: 'Create PIN',
    AppKeys.confirmPasscodeTitle: 'Confirm PIN',
    AppKeys.unlockPasscodeTitle: 'Enter PIN',
    AppKeys.verifyPasscodeTitle: 'Verify PIN',
    AppKeys.createPasscodeSubtitle: 'Create a PIN for\nquick login',
    AppKeys.confirmPasscodeSubtitle: 'Enter your PIN again\nto confirm',
    AppKeys.unlockPasscodeSubtitle: 'Enter your PIN for\nquick login',
    AppKeys.verifyPasscodeSubtitle: 'Enter your PIN\nto confirm',
    AppKeys.changePasscodeTitle: 'Change PIN',
    AppKeys.enterCurrentPasscodeTitle: 'Enter Current PIN',
    AppKeys.passcodeContinue: 'Continue',
    AppKeys.passcodeUnlock: 'Unlock',
    AppKeys.passcodeSkip: 'Skip',
    AppKeys.passcodeRemove: 'Remove PIN',
    AppKeys.passcodeSetUp: 'Set Up PIN',
    AppKeys.passcodeChange: 'Change PIN',
    AppKeys.passcodeMismatch: 'PINs do not match. Please try again.',
    AppKeys.passcodeIncorrect: 'Incorrect PIN. Please try again.',
    AppKeys.passcodeSaveFailed: 'Could not save PIN. Please try again.',
    AppKeys.passcodeSessionExpired:
        'Your login session expired. Please log in again.',
    AppKeys.passcodeRemoveFailed: 'Could not remove PIN. Please try again.',
    AppKeys.passcodeSet: 'PIN created.',
    AppKeys.passcodeChanged: 'PIN changed.',
    AppKeys.passcodeRemoved: 'PIN removed.',
    AppKeys.missingAccount: 'Missing account information.',
    AppKeys.accountNameRequired: 'Please enter an account name.',
    AppKeys.accountUpdated: 'Account updated.',
    AppKeys.accountUpdateFailed: 'Could not update account.',
    AppKeys.switchingProfile: 'Switching profile...',
    AppKeys.switchingLanguage: 'Changing language...',
  },
};
