import '../../app_keys.dart';

const settingsStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.settingsTitle: 'Cài Đặt',
    AppKeys.accountTitle: 'Tài Khoản',
    AppKeys.accountMenuTitle: 'Tài Khoản',
    AppKeys.accountMenuSubtitle: 'Quản lý thông tin tài khoản',
    AppKeys.logout: 'Logout',
    AppKeys.logoutSubtitle: 'Đăng xuất khỏi tài khoản',
    AppKeys.passcodeMenuTitle: 'Mã PIN',
    AppKeys.passcodeMenuSubtitleSet: 'Tạo mã PIN để khóa ứng dụng',
    AppKeys.passcodeMenuSubtitleManage: 'Đổi hoặc xóa mã PIN',
    AppKeys.createPasscodeTitle: 'Tạo Mã PIN',
    AppKeys.confirmPasscodeTitle: 'Nhập Lại Mã PIN',
    AppKeys.unlockPasscodeTitle: 'Nhập Mã PIN',
    AppKeys.verifyPasscodeTitle: 'Xác Minh Mã PIN',
    AppKeys.createPasscodeSubtitle: 'Tạo mã PIN để\nđăng nhập nhanh chóng',
    AppKeys.confirmPasscodeSubtitle: 'Nhập lại mã PIN để\nxác nhận',
    AppKeys.unlockPasscodeSubtitle: 'Nhập mã PIN để\nđăng nhập nhanh chóng',
    AppKeys.verifyPasscodeSubtitle: 'Nhập mã PIN để\nxác nhận',
    AppKeys.changePasscodeTitle: 'Đổi Mã PIN',
    AppKeys.enterCurrentPasscodeTitle: 'Nhập Mã PIN Hiện Tại',
    AppKeys.passcodeContinue: 'Tiếp Tục',
    AppKeys.passcodeUnlock: 'Mở Khóa',
    AppKeys.passcodeSkip: 'Bỏ Qua',
    AppKeys.passcodeRemove: 'Xóa Mã PIN',
    AppKeys.passcodeSetUp: 'Tạo Mã PIN',
    AppKeys.passcodeChange: 'Đổi Mã PIN',
    AppKeys.passcodeMismatch: 'Mã PIN không khớp. Vui lòng thử lại.',
    AppKeys.passcodeIncorrect: 'Mã PIN không đúng. Vui lòng thử lại.',
    AppKeys.passcodeSaveFailed: 'Không thể lưu mã PIN. Vui lòng thử lại.',
    AppKeys.passcodeSessionExpired:
        'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
    AppKeys.passcodeRemoveFailed: 'Không thể xóa mã PIN. Vui lòng thử lại.',
    AppKeys.passcodeSet: 'Đã tạo mã PIN.',
    AppKeys.passcodeChanged: 'Đã đổi mã PIN.',
    AppKeys.passcodeRemoved: 'Đã xóa mã PIN.',
    AppKeys.missingAccount: 'Thiếu thông tin tài khoản.',
    AppKeys.accountNameRequired: 'Vui lòng nhập tên tài khoản.',
    AppKeys.accountUpdated: 'Đã cập nhật tài khoản.',
    AppKeys.accountUpdateFailed: 'Không thể cập nhật tài khoản.',
    AppKeys.switchingProfile: 'Đang chuyển hồ sơ...',
    AppKeys.switchingLanguage: 'Đang đổi ngôn ngữ...',
  },
  'en': {
    AppKeys.settingsTitle: 'Settings',
    AppKeys.accountTitle: 'Account',
    AppKeys.accountMenuTitle: 'Account',
    AppKeys.accountMenuSubtitle: 'Manage account information',
    AppKeys.logout: 'Logout',
    AppKeys.logoutSubtitle: 'Sign out of your account',
    AppKeys.passcodeMenuTitle: 'Passcode',
    AppKeys.passcodeMenuSubtitleSet: 'Create a PIN to lock the app',
    AppKeys.passcodeMenuSubtitleManage: 'Change or remove your PIN',
    AppKeys.createPasscodeTitle: 'Create PIN',
    AppKeys.confirmPasscodeTitle: 'Confirm PIN',
    AppKeys.unlockPasscodeTitle: 'Enter PIN',
    AppKeys.verifyPasscodeTitle: 'Verify PIN',
    AppKeys.createPasscodeSubtitle: 'Create a PIN for\nquick login',
    AppKeys.confirmPasscodeSubtitle: 'Enter your PIN again\nto confirm',
    AppKeys.unlockPasscodeSubtitle: 'Enter your PIN for\nquick login',
    AppKeys.verifyPasscodeSubtitle: 'Enter your PIN\nto confirm',
    AppKeys.changePasscodeTitle: 'Change PIN',
    AppKeys.enterCurrentPasscodeTitle: 'Enter Current PIN',
    AppKeys.passcodeContinue: 'Continue',
    AppKeys.passcodeUnlock: 'Unlock',
    AppKeys.passcodeSkip: 'Skip',
    AppKeys.passcodeRemove: 'Remove PIN',
    AppKeys.passcodeSetUp: 'Set Up PIN',
    AppKeys.passcodeChange: 'Change PIN',
    AppKeys.passcodeMismatch: 'PINs do not match. Please try again.',
    AppKeys.passcodeIncorrect: 'Incorrect PIN. Please try again.',
    AppKeys.passcodeSaveFailed: 'Could not save PIN. Please try again.',
    AppKeys.passcodeSessionExpired:
        'Your login session expired. Please log in again.',
    AppKeys.passcodeRemoveFailed: 'Could not remove PIN. Please try again.',
    AppKeys.passcodeSet: 'PIN created.',
    AppKeys.passcodeChanged: 'PIN changed.',
    AppKeys.passcodeRemoved: 'PIN removed.',
    AppKeys.missingAccount: 'Missing account information.',
    AppKeys.accountNameRequired: 'Please enter an account name.',
    AppKeys.accountUpdated: 'Account updated.',
    AppKeys.accountUpdateFailed: 'Could not update account.',
    AppKeys.switchingProfile: 'Switching profile...',
    AppKeys.switchingLanguage: 'Changing language...',
  },
};
