import '../../app_keys.dart';

const homeCommonStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.navHome: 'HOME',
    AppKeys.navClassroom: 'LỚP HỌC',
    AppKeys.navStudy: 'HỌC',
    AppKeys.navMembers: 'THÀNH VIÊN',
    AppKeys.navLearning: 'HỌC',
    AppKeys.learningTabTitle: 'Học',
    AppKeys.navGames: 'GAMES',
    AppKeys.navSettings: 'CÀI ĐẶT',
    AppKeys.assessment: 'KIỂM TRA',
    AppKeys.newHomeAssessmentTest: 'Đánh Giá\nTrình Độ',
    AppKeys.newHomeLearningPractice: 'Học Và\nLuyện Tập',
    AppKeys.newHomeChartLevel: 'Lớp',
    AppKeys.newHomeChartActivity: 'Trend',
    AppKeys.viewAll: 'Xem tất cả',
  },
  'en': {
    AppKeys.navHome: 'HOME',
    AppKeys.navClassroom: 'CLASS',
    AppKeys.navStudy: 'STUDY',
    AppKeys.navMembers: 'MEMBERS',
    AppKeys.navLearning: 'LEARNING',
    AppKeys.learningTabTitle: 'Learning',
    AppKeys.navGames: 'GAMES',
    AppKeys.navSettings: 'SETTINGS',
    AppKeys.assessment: 'ASSESSMENT',
    AppKeys.newHomeAssessmentTest: 'Assessment Test',
    AppKeys.newHomeLearningPractice: 'Learning & Practice',
    AppKeys.newHomeChartLevel: 'Grade',
    AppKeys.newHomeChartActivity: 'Trend',
    AppKeys.viewAll: 'View all',
  },
};
