import '../../app_keys.dart';

const homeCommonStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.navHome: 'HOME',
    AppKeys.navClassroom: 'Lá»šP Há»ŒC',
    AppKeys.navHomework: 'BÃ€I Táº¬P',
    AppKeys.navStudy: 'Há»ŒC',
    AppKeys.navMembers: 'THÃ€NH VIÃŠN',
    AppKeys.navReview: 'Ã”N Táº¬P',
    AppKeys.navAssessment: 'ÄÃNH GIÃ',
    AppKeys.navRoom: 'PHÃ’NG',
    AppKeys.navProgram: 'Ã”N Táº¬P',
    AppKeys.navGames: 'GAMES',
    AppKeys.navHistory: 'Lá»ŠCH Sá»¬',
    AppKeys.navReport: 'BÃO CÃO',
    AppKeys.navSettings: 'CÃ€I Äáº¶T',
    AppKeys.assessment: 'KIá»‚M TRA',
    AppKeys.assessmentDescription:
        'CÃ¹ng AI kiá»ƒm tra kháº£ nÄƒng toÃ¡n há»c\nvÆ°á»£t trá»™i riÃªng báº¡n.',
    AppKeys.startNow: 'Báº¯t Ä‘áº§u ngay',
    AppKeys.practice: 'Luyá»‡n táº­p',
    AppKeys.homeHeroTitle: 'TOÃN AI',
    AppKeys.homeHeroSubtitle: 'NhÆ° Tháº§n Äá»“ng',
    AppKeys.homeHeroTextbookLabel: 'Theo\nSÃ¡ch GiÃ¡o Khoa',
    AppKeys.homeHeroPrompt: 'BÃ© trÃ¬nh Ä‘á»™ nÃ o?',
    AppKeys.homeHeroAssessment: 'ÄÃ¡nh GiÃ¡',
    AppKeys.assessmentAction: 'ÄÃ¡nh GiÃ¡',
    AppKeys.viewAll: 'Xem táº¥t cáº£',
    AppKeys.viewAllUpper: 'XEM Táº¤T Cáº¢',
    AppKeys.progressAchievementTitle: 'Tiáº¿n Ä‘á»™ vÆ°á»£t báº­c',
    AppKeys.todayCompletedExercises: 'ÄÃ£ hoÃ n thÃ nh 12 bÃ i táº­p hÃ´m nay',
  },
  'en': {
    AppKeys.navHome: 'HOME',
    AppKeys.navClassroom: 'CLASS',
    AppKeys.navHomework: 'HOMEWORK',
    AppKeys.navStudy: 'STUDY',
    AppKeys.navMembers: 'MEMBERS',
    AppKeys.navReview: 'REVIEW',
    AppKeys.navAssessment: 'REVIEW',
    AppKeys.navRoom: 'ROOM',
    AppKeys.navProgram: 'PROGRAM',
    AppKeys.navGames: 'GAMES',
    AppKeys.navHistory: 'HISTORY',
    AppKeys.navReport: 'REPORT',
    AppKeys.navSettings: 'SETTINGS',
    AppKeys.assessment: 'ASSESSMENT',
    AppKeys.assessmentDescription:
        'Use AI to check your unique\nmath strengths.',
    AppKeys.startNow: 'Start now',
    AppKeys.practice: 'Practice',
    AppKeys.homeHeroTitle: 'AI MATH',
    AppKeys.homeHeroSubtitle: 'Like a Prodigy',
    AppKeys.homeHeroTextbookLabel: 'Textbook\nAligned',
    AppKeys.homeHeroPrompt: "What's your level?",
    AppKeys.homeHeroAssessment: 'Assessment',
    AppKeys.assessmentAction: 'Assessment',
    AppKeys.viewAll: 'View all',
    AppKeys.viewAllUpper: 'VIEW ALL',
    AppKeys.progressAchievementTitle: 'Great progress',
    AppKeys.todayCompletedExercises: 'Completed 12 exercises today',
  },
};
