import '../../app_keys.dart';

const homeCommonStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.navHome: 'HOME',
    AppKeys.navClassroom: 'LỚP HỌC',
    AppKeys.navClassroomExercise: 'BÀI TẬP',
    AppKeys.navStudy: 'HỌC',
    AppKeys.navMembers: 'THÀNH VIÊN',
    AppKeys.navReview: 'ÔN TẬP',
    AppKeys.navAssessment: 'ĐÁNH GIÁ',
    AppKeys.navRoom: 'PHÒNG',
    AppKeys.navProgram: 'CHƯƠNG TRÌNH',
    AppKeys.navGames: 'GAMES',
    AppKeys.navHistory: 'LỊCH SỬ',
    AppKeys.navReport: 'BÁO CÁO',
    AppKeys.navSettings: 'CÀI ĐẶT',
    AppKeys.assessment: 'KIỂM TRA',
    AppKeys.assessmentDescription:
        'Cùng AI kiểm tra khả năng toán học\nvượt trội riêng bạn.',
    AppKeys.startNow: 'Bắt đầu ngay',
    AppKeys.practice: 'Luyện tập',
    AppKeys.homeHeroTitle: 'TOÁN AI',
    AppKeys.homeHeroSubtitle: 'Như Thần Đồng',
    AppKeys.homeHeroTextbookLabel: 'Theo\nSách Giáo Khoa',
    AppKeys.homeHeroPrompt: 'Bé trình độ nào?',
    AppKeys.homeHeroAssessment: 'Đánh Giá',
    AppKeys.assessmentAction: 'Đánh Giá',
    AppKeys.viewAll: 'Xem tất cả',
    AppKeys.viewAllUpper: 'XEM TẤT CẢ',
    AppKeys.progressAchievementTitle: 'Tiến độ vượt bậc',
    AppKeys.todayCompletedExercises: 'Đã hoàn thành 12 bài tập hôm nay',
  },
  'en': {
    AppKeys.navHome: 'HOME',
    AppKeys.navClassroom: 'CLASS',
    AppKeys.navClassroomExercise: 'HOMEWORK',
    AppKeys.navStudy: 'STUDY',
    AppKeys.navMembers: 'MEMBERS',
    AppKeys.navReview: 'PRACTICE',
    AppKeys.navAssessment: 'ASSESS',
    AppKeys.navRoom: 'ROOM',
    AppKeys.navProgram: 'PROGRAM',
    AppKeys.navGames: 'GAMES',
    AppKeys.navHistory: 'HISTORY',
    AppKeys.navReport: 'REPORT',
    AppKeys.navSettings: 'SETTINGS',
    AppKeys.assessment: 'ASSESSMENT',
    AppKeys.assessmentDescription:
        'Use AI to check your unique\nmath strengths.',
    AppKeys.startNow: 'Start now',
    AppKeys.practice: 'Practice',
    AppKeys.homeHeroTitle: 'AI MATH',
    AppKeys.homeHeroSubtitle: 'Like a Prodigy',
    AppKeys.homeHeroTextbookLabel: 'Textbook\nAligned',
    AppKeys.homeHeroPrompt: "What's your level?",
    AppKeys.homeHeroAssessment: 'Assessment',
    AppKeys.assessmentAction: 'Assessment',
    AppKeys.viewAll: 'View all',
    AppKeys.viewAllUpper: 'VIEW ALL',
    AppKeys.progressAchievementTitle: 'Great progress',
    AppKeys.todayCompletedExercises: 'Completed 12 exercises today',
  },
};
