import '../../app_keys.dart';

const parentHomeStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.parentAssessmentTabTitle: 'Đánh Giá',
    AppKeys.parentLearningStreak: 'Chuỗi ngày học',
    AppKeys.parentAssessmentTitle: 'Đánh Giá',
    AppKeys.parentAssessmentSubtitle: 'Xác định năng lực và trình độ hiện tại',
    AppKeys.parentLearningProgress: 'Tiến trình học tập',
    AppKeys.learningProgressTitle: 'Tiến độ học tập',
    AppKeys.learningProgressAllAssessments: 'Tất cả bài đánh giá',
    AppKeys.learningProgressFilterTime: 'Lọc thời gian',
    AppKeys.learningProgressFilter: 'Bộ lọc',
    AppKeys.learningProgressScoreTitle: 'Điểm số theo bài đánh giá',
    AppKeys.learningProgressAssessmentCount: '{count} bài đánh giá',
    AppKeys.learningProgressAverageScore: 'Điểm trung bình: {score}',
    AppKeys.learningProgressFromDate: 'Từ ngày',
    AppKeys.learningProgressToDate: 'Đến ngày',
    AppKeys.learningProgressApplyFilter: 'Áp dụng',
    AppKeys.learningProgressClearFilter: 'Xóa bộ lọc',
    AppKeys.learningProgressImprovingTitle: 'Con đang tiến bộ tốt!',
    AppKeys.learningProgressImprovingMessage:
        'Điểm trung bình tăng {delta} điểm so với giai đoạn trước.',
    AppKeys.learningProgressDecliningTitle: 'Con cần cố gắng thêm',
    AppKeys.learningProgressDecliningMessage:
        'Điểm trung bình giảm {delta} điểm so với giai đoạn trước.',
    AppKeys.learningProgressStableTitle: 'Phong độ học tập ổn định',
    AppKeys.learningProgressStableMessage:
        'Điểm trung bình không thay đổi nhiều so với giai đoạn trước.',
    AppKeys.learningProgressNoData:
        'Chưa có bài đánh giá trong khoảng thời gian này.',
    AppKeys.learningProgressShare: 'Chia sẻ tiến độ',
    AppKeys.learningProgressShared: 'Đã sao chép tóm tắt tiến độ.',
    AppKeys.parentRoadmapTitle: 'Game road map',
    AppKeys.parentRoadmapSubtitle: 'Phiêu lưu học tập qua từng cấp độ',
    AppKeys.parentJoinRoomTitle: 'Tham gia phòng học',
    AppKeys.parentJoinRoomSubtitle: 'Tương tác và học cùng giáo viên',
    AppKeys.parentRoomTitle: 'Phòng',
    AppKeys.parentQuizLoadFailed: 'Chưa tải được lịch sử đánh giá.',
    AppKeys.parentTryAgain: 'Thử lại',
    AppKeys.parentNoClassroom: 'Chưa tham gia lớp',
    AppKeys.parentNoTeacher: 'Chưa có giáo viên',
    AppKeys.parentChildDashboardLoadFailed:
        'Chưa tải được đầy đủ thông tin học tập của các bé.',
    AppKeys.parentTeacherFeedback:
        'Chào phụ huynh, em gửi nhận xét tuần này của bé {student}. Bé đã có tiến bộ và hoàn thành tốt các hoạt động trên lớp.',
    AppKeys.parentTeacherReminder:
        'Bé {student} còn một số hoạt động cần hoàn thành. Nhờ gia đình nhắc bé ôn tập và làm bài đúng hạn.',
    AppKeys.parentTasksTitle: 'Nhiệm vụ',
    AppKeys.parentTasksCountTitle: 'Nhiệm vụ({count})',
    AppKeys.parentMessagesTitle: 'Tin nhắn',
    AppKeys.parentWeekdaySun: 'CN',
    AppKeys.parentWeekdayMon: 'T2',
    AppKeys.parentWeekdayTue: 'T3',
    AppKeys.parentWeekdayWed: 'T4',
    AppKeys.parentWeekdayThu: 'T5',
    AppKeys.parentWeekdayFri: 'T6',
    AppKeys.parentWeekdaySat: 'T7',
    AppKeys.homeMessageTeacherOne: 'Cô Nguyễn Anh',
    AppKeys.homeMessageTeacherTwo: 'Thầy Minh Hoàng',
    AppKeys.homeMessageClassOne: 'Toán 2A1',
    AppKeys.homeMessageClassTwo: 'Toán 3A1',
    AppKeys.homeMessageTimeOne: '10:45 AM',
    AppKeys.homeMessageTimeTwo: 'Hôm qua',
    AppKeys.homeMessageStudentOne: 'UYENVO',
    AppKeys.homeMessageStudentTwo: 'HENRY',
    AppKeys.homeMessageBodyOne:
        'Chào chị Jenny, em gửi nhận xét tuần này của bé uyenvo. Bé đã hoàn thành',
    AppKeys.homeMessageBodyTwo:
        'Nhắc nhở: Ngày mai henry có buổi dã ngoại, phụ huynh nhớ chuẩn bị thêm...',
    AppKeys.parentNoStudentTitle: 'Chưa có hồ sơ',
    AppKeys.parentNoStudentMessage:
        'Quý phụ huynh cần tạo hồ sơ cho con để tham gia vào các lớp phù hợp.',
    AppKeys.parentCreateStudentNow: 'Tạo hồ sơ ngay',
    AppKeys.parentCreateStudentLater: 'Để sau',
    AppKeys.parentSelectStudentMessage:
        'Quý phụ huynh cần chọn hồ sơ hoặc tạo hồ sơ cho bé để tham gia vào các lớp phù hợp.',
    AppKeys.parentCreateStudent: 'Tạo hồ sơ',
    AppKeys.parentInfoTitle: 'Hồ sơ',
    AppKeys.parentChildrenCount: 'Thành viên ({count})',
    AppKeys.parentRoomAssignmentsTitle: 'Bài tập, kiểm tra',
  },
  'en': {
    AppKeys.parentAssessmentTabTitle: 'Assessment',
    AppKeys.parentLearningStreak: 'Learning streak',
    AppKeys.parentAssessmentTitle: 'Assessment',
    AppKeys.parentAssessmentSubtitle:
        'Identify the current ability and learning level',
    AppKeys.parentLearningProgress: 'Learning progress',
    AppKeys.learningProgressTitle: 'Learning progress',
    AppKeys.learningProgressAllAssessments: 'All assessments',
    AppKeys.learningProgressFilterTime: 'Filter by time',
    AppKeys.learningProgressFilter: 'Filter',
    AppKeys.learningProgressScoreTitle: 'Scores by assessment',
    AppKeys.learningProgressAssessmentCount: '{count} assessments',
    AppKeys.learningProgressAverageScore: 'Average score: {score}',
    AppKeys.learningProgressFromDate: 'From date',
    AppKeys.learningProgressToDate: 'To date',
    AppKeys.learningProgressApplyFilter: 'Apply',
    AppKeys.learningProgressClearFilter: 'Clear filter',
    AppKeys.learningProgressImprovingTitle: 'Great progress!',
    AppKeys.learningProgressImprovingMessage:
        'The average score increased by {delta} points from the previous period.',
    AppKeys.learningProgressDecliningTitle: 'Keep practicing',
    AppKeys.learningProgressDecliningMessage:
        'The average score decreased by {delta} points from the previous period.',
    AppKeys.learningProgressStableTitle: 'Steady learning progress',
    AppKeys.learningProgressStableMessage:
        'The average score is holding steady compared with the previous period.',
    AppKeys.learningProgressNoData:
        'There are no assessments in this time period.',
    AppKeys.learningProgressShare: 'Share progress',
    AppKeys.learningProgressShared: 'Progress summary copied.',
    AppKeys.parentRoadmapTitle: 'Game road map',
    AppKeys.parentRoadmapSubtitle: 'Learn through an adventure of levels',
    AppKeys.parentJoinRoomTitle: 'Join a classroom',
    AppKeys.parentJoinRoomSubtitle: 'Interact and learn with a teacher',
    AppKeys.parentRoomTitle: 'Room',
    AppKeys.parentQuizLoadFailed: 'Could not load assessment history.',
    AppKeys.parentTryAgain: 'Try again',
    AppKeys.parentNoClassroom: 'Not in a classroom',
    AppKeys.parentNoTeacher: 'No teacher yet',
    AppKeys.parentChildDashboardLoadFailed:
        'Some learning information could not be loaded.',
    AppKeys.parentTeacherFeedback:
        'Hello, here is this week\'s feedback for {student}. Your child has made progress and completed the classroom activities well.',
    AppKeys.parentTeacherReminder:
        '{student} still has a few activities to complete. Please remind your child to review and finish them on time.',
    AppKeys.parentTasksTitle: 'Tasks',
    AppKeys.parentTasksCountTitle: 'Tasks({count})',
    AppKeys.parentMessagesTitle: 'Messages',
    AppKeys.parentWeekdaySun: 'Sun',
    AppKeys.parentWeekdayMon: 'Mon',
    AppKeys.parentWeekdayTue: 'Tue',
    AppKeys.parentWeekdayWed: 'Wed',
    AppKeys.parentWeekdayThu: 'Thu',
    AppKeys.parentWeekdayFri: 'Fri',
    AppKeys.parentWeekdaySat: 'Sat',
    AppKeys.homeMessageTeacherOne: 'Ms. Nguyen Anh',
    AppKeys.homeMessageTeacherTwo: 'Mr. Minh Hoang',
    AppKeys.homeMessageClassOne: 'Math 2A1',
    AppKeys.homeMessageClassTwo: 'Math 3A1',
    AppKeys.homeMessageTimeOne: '10:45 AM',
    AppKeys.homeMessageTimeTwo: 'Yesterday',
    AppKeys.homeMessageStudentOne: 'UYENVO',
    AppKeys.homeMessageStudentTwo: 'HENRY',
    AppKeys.homeMessageBodyOne:
        "Hi Jenny, here is uyenvo's feedback for this week. They have completed",
    AppKeys.homeMessageBodyTwo:
        'Reminder: Henry has a field trip tomorrow. Please remember to prepare...',
    AppKeys.parentNoStudentTitle: 'No profile selected',
    AppKeys.parentNoStudentMessage:
        'Create a child profile to join suitable classrooms.',
    AppKeys.parentCreateStudentNow: 'Create profile now',
    AppKeys.parentCreateStudentLater: 'Later',
    AppKeys.parentSelectStudentMessage:
        'Choose a child profile or create one to join suitable classrooms.',
    AppKeys.parentCreateStudent: 'Create profile',
    AppKeys.parentInfoTitle: 'Profile',
    AppKeys.parentChildrenCount: 'Members ({count})',
    AppKeys.parentRoomAssignmentsTitle: 'Assignments, tests',
  },
};
