import '../../app_keys.dart';

const teacherHomeworkStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.teacherAssignments: 'BÃ i Táº­p',
    AppKeys.teacherAssessments: 'ÄÃ¡nh GiÃ¡',
    AppKeys.teacherCreatedAssignments: 'BÃ i táº­p Ä‘Ã£ táº¡o',
    AppKeys.teacherCreatedAssessments: 'ÄÃ¡nh giÃ¡ Ä‘Ã£ táº¡o',
    AppKeys.teacherAssignmentSearchHint: 'TÃ¬m kiáº¿m ...',
    AppKeys.teacherAssignmentNewest: 'Má»›i nháº¥t',
    AppKeys.teacherAssignmentListLoadFailed:
        'Táº£i danh sÃ¡ch bÃ i táº­p tháº¥t báº¡i.',
    AppKeys.teacherAssessmentListLoadFailed:
        'Táº£i danh sÃ¡ch Ä‘Ã¡nh giÃ¡ tháº¥t báº¡i.',
    AppKeys.teacherAssignmentDetailLoadFailed:
        'Táº£i chi tiáº¿t bÃ i táº­p tháº¥t báº¡i.',
    AppKeys.teacherAssessmentDetailLoadFailed:
        'Táº£i chi tiáº¿t Ä‘Ã¡nh giÃ¡ tháº¥t báº¡i.',
    AppKeys.teacherAssignmentCreateFailed:
        'KhÃ´ng thá»ƒ táº¡o bÃ i táº­p. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.teacherAssessmentCreateFailed:
        'KhÃ´ng thá»ƒ táº¡o Ä‘Ã¡nh giÃ¡. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.teacherAssignmentPickerSoon:
        'Lá»±a chá»n nÃ y sáº½ sá»›m cÃ³. Báº¡n váº«n cÃ³ thá»ƒ táº¡o bÃ i táº­p.',
    AppKeys.teacherNoAssignments: 'ChÆ°a cÃ³ bÃ i táº­p nÃ o.',
    AppKeys.teacherNoAssessments: 'ChÆ°a cÃ³ Ä‘Ã¡nh giÃ¡ nÃ o.',
    AppKeys.teacherAssignmentGeometryTitle:
        'BÃ i táº­p vá» nhÃ : HÃ¬nh há»c cÆ¡ báº£n',
    AppKeys.teacherAssignmentId: 'ID: {id}',
    AppKeys.teacherAssignmentClassName: 'ToÃ¡n 1A2',
    AppKeys.teacherAssignmentReviewTitle: 'BÃ i Táº­p Ã”n Luyá»‡n',
    AppKeys.teacherAssignmentChapterRange: 'ChÆ°Æ¡ng 3, BÃ i 5-6',
    AppKeys.teacherAssignmentDueLabel: 'Háº N Ná»˜P',
    AppKeys.teacherAssignmentDueValue: '21:00 31/05/2026',
    AppKeys.teacherAssignmentQuestionCountLabel: 'Sá» CÃ‚U Há»ŽI',
    AppKeys.teacherAssignmentQuestionCountValue: '10 cÃ¢u',
    AppKeys.teacherAssignmentQuestionCountFormat: '{count} cÃ¢u',
    AppKeys.teacherAssignmentQuestionContent: 'Ná»™i dung cÃ¢u há»i',
    AppKeys.teacherAssignmentQuestionNumber: 'CÃ¢u {number}',
    AppKeys.teacherAssignmentEquationPrompt:
        'Giáº£i phÆ°Æ¡ng trÃ¬nh xÂ² - 5x + 6 = 0.',
    AppKeys.teacherAssignmentClassOption: 'Lá»›p 2A1',
    AppKeys.teacherAssignmentSelectClass: 'Chá»n lá»›p há»c',
    AppKeys.teacherAssignmentClassSummaryName: 'ToÃ¡n A1',
    AppKeys.teacherAssignmentClassStudentCount: '32 Há»c Sinh',
    AppKeys.teacherAssignmentClassStudentCountFormat: '{count} Há»c Sinh',
    AppKeys.teacherAssignmentClassGrade: 'Lá»›p 1',
    AppKeys.teacherAssignmentClassProgram: 'CÃ¡nh Diá»u',
    AppKeys.teacherAssignmentClassDescription: 'Lá»›p CÃ¡ Biá»‡t',
    AppKeys.teacherAssignmentVolumeOne: 'Táº­p 1',
    AppKeys.teacherAssignmentVolumeTwo: 'Táº­p 2',
    AppKeys.teacherAssignmentTitleHint: 'TiÃªu Äá»',
    AppKeys.teacherAssessmentTitleHint: 'TiÃªu Äá» ÄÃ¡nh GiÃ¡',
    AppKeys.teacherAssignmentProgramLabel: 'ChÆ°Æ¡ng TrÃ¬nh',
    AppKeys.teacherAssignmentProgramValue: 'CÃ¡nh Diá»u 1',
    AppKeys.teacherAssignmentProgramRequired:
        'Vui lÃ²ng chá»n chÆ°Æ¡ng trÃ¬nh.',
    AppKeys.teacherAssignmentPublishLabel: 'Hiá»ƒn thá»‹',
    AppKeys.teacherAssignmentVisibilityPublic: 'PUBLIC',
    AppKeys.teacherAssignmentVisibilityPrivate: 'PRIVATE',
    AppKeys.teacherAssignmentDeadline: 'Háº¡n Ná»™p',
    AppKeys.teacherAssignmentStartDateHint: 'NgÃ y giá» báº¯t Ä‘áº§u',
    AppKeys.teacherAssignmentEndDateHint: 'NgÃ y giá» káº¿t thÃºc',
    AppKeys.teacherAssignmentStartDateRequired:
        'Vui lÃ²ng chá»n ngÃ y báº¯t Ä‘áº§u.',
    AppKeys.teacherAssignmentEndDateRequired:
        'Vui lÃ²ng chá»n ngÃ y káº¿t thÃºc.',
    AppKeys.teacherAssignmentFutureDateRequired:
        'NgÃ y Ä‘Ã£ chá»n pháº£i á»Ÿ tÆ°Æ¡ng lai.',
    AppKeys.teacherAssignmentEndAfterStart:
        'NgÃ y káº¿t thÃºc pháº£i sau ngÃ y báº¯t Ä‘áº§u.',
    AppKeys.teacherAssignmentChapterLabel: 'ChÆ°Æ¡ng Há»c',
    AppKeys.teacherAssignmentLessonLabel: 'BÃ i Há»c',
    AppKeys.teacherAssignmentDescriptionLabel: 'MÃ´ táº£',
    AppKeys.teacherAssignmentDescriptionHint: 'MÃ´ táº£ thÃªm',
    AppKeys.teacherAssessmentDescriptionHint: 'MÃ´ táº£ Ä‘Ã¡nh giÃ¡',
    AppKeys.teacherAssignmentCreated: 'ÄÃ£ táº¡o bÃ i táº­p.',
    AppKeys.teacherAssessmentCreated: 'ÄÃ£ táº¡o Ä‘Ã¡nh giÃ¡.',
  },
  'en': {
    AppKeys.teacherAssignments: 'Assignments',
    AppKeys.teacherAssessments: 'Assessment',
    AppKeys.teacherCreatedAssignments: 'Created assignments',
    AppKeys.teacherCreatedAssessments: 'Created assessments',
    AppKeys.teacherAssignmentSearchHint: 'Search ...',
    AppKeys.teacherAssignmentNewest: 'Newest',
    AppKeys.teacherAssignmentListLoadFailed: 'Failed to load assignments.',
    AppKeys.teacherAssessmentListLoadFailed: 'Failed to load assessments.',
    AppKeys.teacherAssignmentDetailLoadFailed:
        'Failed to load assignment details.',
    AppKeys.teacherAssessmentDetailLoadFailed:
        'Failed to load assessment details.',
    AppKeys.teacherAssignmentCreateFailed:
        'Could not create assignment. Please try again.',
    AppKeys.teacherAssessmentCreateFailed:
        'Could not create assessment. Please try again.',
    AppKeys.teacherAssignmentPickerSoon:
        'This selector is coming soon. You can still create the assignment.',
    AppKeys.teacherNoAssignments: 'No assignments yet.',
    AppKeys.teacherNoAssessments: 'No assessments yet.',
    AppKeys.teacherAssignmentGeometryTitle: 'Homework: Basic geometry',
    AppKeys.teacherAssignmentId: 'ID: {id}',
    AppKeys.teacherAssignmentClassName: 'Math 1A2',
    AppKeys.teacherAssignmentReviewTitle: 'Review Homework',
    AppKeys.teacherAssignmentChapterRange: 'Chapter 3, Lessons 5-6',
    AppKeys.teacherAssignmentDueLabel: 'DUE DATE',
    AppKeys.teacherAssignmentDueValue: '21:00 05/31/2026',
    AppKeys.teacherAssignmentQuestionCountLabel: 'QUESTIONS',
    AppKeys.teacherAssignmentQuestionCountValue: '10 questions',
    AppKeys.teacherAssignmentQuestionCountFormat: '{count} questions',
    AppKeys.teacherAssignmentQuestionContent: 'Question content',
    AppKeys.teacherAssignmentQuestionNumber: 'Question {number}',
    AppKeys.teacherAssignmentEquationPrompt:
        'Solve the equation xÂ² - 5x + 6 = 0.',
    AppKeys.teacherAssignmentClassOption: 'Class 2A1',
    AppKeys.teacherAssignmentSelectClass: 'Select classroom',
    AppKeys.teacherAssignmentClassSummaryName: 'Math A1',
    AppKeys.teacherAssignmentClassStudentCount: '32 Students',
    AppKeys.teacherAssignmentClassStudentCountFormat: '{count} Students',
    AppKeys.teacherAssignmentClassGrade: 'Grade 1',
    AppKeys.teacherAssignmentClassProgram: 'Canh Dieu',
    AppKeys.teacherAssignmentClassDescription: 'Special class',
    AppKeys.teacherAssignmentVolumeOne: 'Book 1',
    AppKeys.teacherAssignmentVolumeTwo: 'Book 2',
    AppKeys.teacherAssignmentTitleHint: 'Title',
    AppKeys.teacherAssessmentTitleHint: 'Assessment title',
    AppKeys.teacherAssignmentProgramLabel: 'Program',
    AppKeys.teacherAssignmentProgramValue: 'Canh Dieu 1',
    AppKeys.teacherAssignmentProgramRequired: 'Please select a program.',
    AppKeys.teacherAssignmentPublishLabel: 'Visibility',
    AppKeys.teacherAssignmentVisibilityPublic: 'PUBLIC',
    AppKeys.teacherAssignmentVisibilityPrivate: 'PRIVATE',
    AppKeys.teacherAssignmentDeadline: 'Deadline',
    AppKeys.teacherAssignmentStartDateHint: 'Start date and time',
    AppKeys.teacherAssignmentEndDateHint: 'End date and time',
    AppKeys.teacherAssignmentStartDateRequired: 'Please select a start date.',
    AppKeys.teacherAssignmentEndDateRequired: 'Please select an end date.',
    AppKeys.teacherAssignmentFutureDateRequired:
        'The selected date must be in the future.',
    AppKeys.teacherAssignmentEndAfterStart:
        'End date must be after start date.',
    AppKeys.teacherAssignmentChapterLabel: 'Chapter',
    AppKeys.teacherAssignmentLessonLabel: 'Lesson',
    AppKeys.teacherAssignmentDescriptionLabel: 'Description',
    AppKeys.teacherAssignmentDescriptionHint: 'Additional description',
    AppKeys.teacherAssessmentDescriptionHint: 'Assessment description',
    AppKeys.teacherAssignmentCreated: 'Assignment created.',
    AppKeys.teacherAssessmentCreated: 'Assessment created.',
  },
};
