import '../../app_keys.dart';

const studyStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.reviewTitle: 'Lá»™ trÃ¬nh há»c táº­p',
    AppKeys.exercises: 'BÃ i táº­p',
    AppKeys.days: 'NgÃ y',
    AppKeys.chapterMissingProfileInfo:
        'Há»“ sÆ¡ thiáº¿u lá»›p, chÆ°Æ¡ng trÃ¬nh hoáº·c há»c ká»³.',
    AppKeys.chapterLoadFailed: 'Táº£i danh sÃ¡ch chÆ°Æ¡ng tháº¥t báº¡i.',
    AppKeys.chapterLoadErrorTitle: 'KhÃ´ng táº£i Ä‘Æ°á»£c chÆ°Æ¡ng',
    AppKeys.test: 'Kiá»ƒm tra',
    AppKeys.clearSelection: 'Bá» chá»n',
    AppKeys.startChapterTestMessage:
        'Báº¯t Ä‘áº§u kiá»ƒm tra chÆ°Æ¡ng {chapter}.',
    AppKeys.startSelectedTestMessage:
        'Báº¯t Ä‘áº§u kiá»ƒm tra {count} chÆ°Æ¡ng.',
    AppKeys.chapter: 'ChÆ°Æ¡ng',
    AppKeys.lessons: 'bÃ i há»c',
    AppKeys.chapterNumber: 'ChÆ°Æ¡ng {number}',
    AppKeys.lockedLessonMessage: 'BÃ i {number}: {title} sáº½ má»Ÿ sau.',
    AppKeys.learningPathChapterLesson: 'ChÆ°Æ¡ng {chapter}, BÃ i {lesson}',
    AppKeys.improveMathTypePrompt:
        'Báº¡n muá»‘n cáº£i thiá»‡n dáº¡ng toÃ¡n nÃ y?',
    AppKeys.reviewLessonAction: 'Ã”n táº­p',
    AppKeys.practiceLesson18Title: 'PhÃ©p cá»™ng trong pháº¡m vi 10',
    AppKeys.practiceLesson19Title:
        'PhÃ©p cá»™ng trong pháº¡m vi 10 (tiáº¿p theo)',
    AppKeys.practiceLesson20Title: 'Luyá»‡n táº­p',
    AppKeys.practiceLesson21Title:
        'PhÃ©p cá»™ng trong pháº¡m vi 10 (tiáº¿p theo)',
    AppKeys.practiceLesson22Title: 'Luyá»‡n táº­p',
    AppKeys.practiceLesson23Title:
        'PhÃ©p cá»™ng trong pháº¡m vi 10 (tiáº¿p theo)',
    AppKeys.practiceLesson24Title: 'Luyá»‡n táº­p',
    AppKeys.practiceLesson25Title: 'Báº£ng cá»™ng trong pháº¡m vi 10',
    AppKeys.practiceLesson26Title: 'Luyá»‡n táº­p',
    AppKeys.practiceLesson27Title: 'PhÃ©p trá»« trong pháº¡m vi 10',
    AppKeys.historyTitle: 'Lá»‹ch Sá»­',
    AppKeys.searchHint: 'TÃ¬m kiáº¿m ...',
    AppKeys.assessmentTab: 'Kiá»ƒm tra',
    AppKeys.practiceTab: 'Luyá»‡n táº­p',
    AppKeys.historyLoadFailed: 'Táº£i lá»‹ch sá»­ tháº¥t báº¡i.',
    AppKeys.historyLoadErrorTitle: 'ChÆ°a táº£i Ä‘Æ°á»£c lá»‹ch sá»­',
    AppKeys.noHistoryTitle: 'ChÆ°a cÃ³ bÃ i phÃ¹ há»£p',
    AppKeys.noHistoryMessage: 'Äá»•i tá»« khÃ³a Ä‘á»ƒ xem cÃ¡c bÃ i khÃ¡c.',
    AppKeys.missingQuizId: 'BÃ i kiá»ƒm tra nÃ y thiáº¿u quiz_id.',
    AppKeys.testAgain: 'LÃ m Láº¡i',
    AppKeys.teacherStudyTitle: 'Há»ŒC',
    AppKeys.teacherStudyAllClasses: 'Táº¥t cáº£',
    AppKeys.teacherStudyLoadFailed:
        'Táº£i danh sÃ¡ch bÃ i táº­p vÃ  Ä‘Ã¡nh giÃ¡ tháº¥t báº¡i.',
    AppKeys.teacherStudyNoResults: 'KhÃ´ng tÃ¬m tháº¥y ná»™i dung phÃ¹ há»£p.',
    AppKeys.teacherStudyDueDate: 'Háº¡n ná»™p: {date}',
    AppKeys.teacherStudyMonth: 'TH{month}',
    AppKeys.testAgainCreateMissingQuiz:
        'KhÃ´ng tÃ¬m tháº¥y bÃ i test trÆ°á»›c Ä‘Ã³.',
    AppKeys.testAgainCreateFailed:
        'KhÃ´ng thá»ƒ táº¡o bÃ i má»›i. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.testAgainDialogTitle: 'Táº¡o bÃ i má»›i tháº¥t báº¡i',
    AppKeys.missingUserOrProfileForHistory:
        'Thiáº¿u user hoáº·c profile Ä‘á»ƒ táº£i lá»‹ch sá»­.',
    AppKeys.missingQuizIdShort: 'Thiáº¿u quiz ID.',
  },
  'en': {
    AppKeys.reviewTitle: 'Learning journey',
    AppKeys.exercises: 'Exercises',
    AppKeys.days: 'Days',
    AppKeys.chapterMissingProfileInfo:
        'Profile is missing grade, program, or semester.',
    AppKeys.chapterLoadFailed: 'Failed to load chapters.',
    AppKeys.chapterLoadErrorTitle: 'Could not load chapters',
    AppKeys.test: 'Test',
    AppKeys.clearSelection: 'Clear',
    AppKeys.startChapterTestMessage: 'Starting test for chapter {chapter}.',
    AppKeys.startSelectedTestMessage: 'Starting test for {count} chapters.',
    AppKeys.chapter: 'Chapter',
    AppKeys.lessons: 'lessons',
    AppKeys.chapterNumber: 'Chapter {number}',
    AppKeys.lockedLessonMessage: 'Lesson {number}: {title} opens later.',
    AppKeys.learningPathChapterLesson: 'Chapter {chapter}, Lesson {lesson}',
    AppKeys.improveMathTypePrompt: 'Would you like to improve this math skill?',
    AppKeys.reviewLessonAction: 'Review',
    AppKeys.practiceLesson18Title: 'Addition within 10',
    AppKeys.practiceLesson19Title: 'Addition within 10 (continued)',
    AppKeys.practiceLesson20Title: 'Practice',
    AppKeys.practiceLesson21Title: 'Addition within 10 (continued)',
    AppKeys.practiceLesson22Title: 'Practice',
    AppKeys.practiceLesson23Title: 'Addition within 10 (continued)',
    AppKeys.practiceLesson24Title: 'Practice',
    AppKeys.practiceLesson25Title: 'Addition facts within 10',
    AppKeys.practiceLesson26Title: 'Practice',
    AppKeys.practiceLesson27Title: 'Subtraction within 10',
    AppKeys.historyTitle: 'History',
    AppKeys.searchHint: 'Search ...',
    AppKeys.assessmentTab: 'Assessment',
    AppKeys.practiceTab: 'Practice',
    AppKeys.historyLoadFailed: 'Failed to load history.',
    AppKeys.historyLoadErrorTitle: 'Could not load history',
    AppKeys.noHistoryTitle: 'No matching items',
    AppKeys.noHistoryMessage: 'Change the keyword to view other items.',
    AppKeys.missingQuizId: 'This test is missing quiz_id.',
    AppKeys.testAgain: 'Try Again',
    AppKeys.teacherStudyTitle: 'STUDY',
    AppKeys.teacherStudyAllClasses: 'All',
    AppKeys.teacherStudyLoadFailed:
        'Failed to load assignments and assessments.',
    AppKeys.teacherStudyNoResults: 'No matching content found.',
    AppKeys.teacherStudyDueDate: 'Due: {date}',
    AppKeys.teacherStudyMonth: 'M{month}',
    AppKeys.testAgainCreateMissingQuiz: 'Could not find the previous test.',
    AppKeys.testAgainCreateFailed:
        'Could not create a new test. Please try again.',
    AppKeys.testAgainDialogTitle: 'New test failed',
    AppKeys.missingUserOrProfileForHistory:
        'Missing user or profile to load history.',
    AppKeys.missingQuizIdShort: 'Missing quiz ID.',
  },
};
