import '../../app_keys.dart';

const studyStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.noChapterTitle: 'Chưa có chương',
    AppKeys.noChapterMessage: 'Chưa có lộ trình ôn tập cho hồ sơ này.',
    AppKeys.startTest: 'Bắt đầu kiểm tra ({count})',
    AppKeys.practiceChapterTwoTitle: 'PHÉP CỘNG, PHÉP TRỪ TRONG PHẠM VI 10',
    AppKeys.reviewTitle: 'Lộ trình học tập',
    AppKeys.exercises: 'Bài tập',
    AppKeys.days: 'Ngày',
    AppKeys.chapterMissingProfileInfo:
        'Hồ sơ thiếu lớp, chương trình hoặc học kỳ.',
    AppKeys.chapterLoadFailed: 'Tải danh sách chương thất bại.',
    AppKeys.chapterLoadErrorTitle: 'Không tải được chương',
    AppKeys.test: 'Kiểm tra',
    AppKeys.clearSelection: 'Bỏ chọn',
    AppKeys.startChapterTestMessage: 'Bắt đầu kiểm tra chương {chapter}.',
    AppKeys.startSelectedTestMessage: 'Bắt đầu kiểm tra {count} chương.',
    AppKeys.chapter: 'Chương',
    AppKeys.lessons: 'bài học',
    AppKeys.chapterNumber: 'Chương {number}',
    AppKeys.lockedLessonMessage: 'Bài {number}: {title} sẽ mở sau.',
    AppKeys.learningPathChapterLesson: 'Chương {chapter}, Bài {lesson}',
    AppKeys.improveMathTypePrompt: 'Bạn muốn cải thiện dạng toán này?',
    AppKeys.reviewLessonAction: 'Ôn tập',
    AppKeys.practiceLesson18Title: 'Phép cộng trong phạm vi 10',
    AppKeys.practiceLesson19Title: 'Phép cộng trong phạm vi 10 (tiếp theo)',
    AppKeys.practiceLesson20Title: 'Luyện tập',
    AppKeys.practiceLesson21Title: 'Phép cộng trong phạm vi 10 (tiếp theo)',
    AppKeys.practiceLesson22Title: 'Luyện tập',
    AppKeys.practiceLesson23Title: 'Phép cộng trong phạm vi 10 (tiếp theo)',
    AppKeys.practiceLesson24Title: 'Luyện tập',
    AppKeys.practiceLesson25Title: 'Bảng cộng trong phạm vi 10',
    AppKeys.practiceLesson26Title: 'Luyện tập',
    AppKeys.practiceLesson27Title: 'Phép trừ trong phạm vi 10',
    AppKeys.historyTitle: 'Lịch Sử',
    AppKeys.searchHint: 'Tìm kiếm ...',
    AppKeys.assessmentTab: 'Kiểm tra',
    AppKeys.practiceTab: 'Luyện tập',
    AppKeys.historyLoadFailed: 'Tải lịch sử thất bại.',
    AppKeys.historyLoadErrorTitle: 'Chưa tải được lịch sử',
    AppKeys.noHistoryTitle: 'Chưa có bài phù hợp',
    AppKeys.noHistoryMessage: 'Đổi từ khóa để xem các bài khác.',
    AppKeys.missingQuizId: 'Bài kiểm tra này thiếu quiz_id.',
    AppKeys.testAgain: 'Làm Lại',
    AppKeys.teacherStudyTitle: 'Học',
    AppKeys.teacherStudyAllClasses: 'Tất cả',
    AppKeys.teacherStudyLoadFailed:
        'Tải danh sách bài tập và đánh giá thất bại.',
    AppKeys.teacherStudyNoResults: 'Không tìm thấy nội dung phù hợp.',
    AppKeys.teacherStudyDueDate: 'Hạn nộp: {date}',
    AppKeys.teacherStudyMonth: 'TH{month}',
    AppKeys.testAgainCreateMissingQuiz: 'Không tìm thấy bài test trước đó.',
    AppKeys.testAgainCreateFailed: 'Không thể tạo bài mới. Vui lòng thử lại.',
    AppKeys.testAgainDialogTitle: 'Tạo bài mới thất bại',
    AppKeys.missingUserOrProfileForHistory:
        'Thiếu user hoặc profile để tải lịch sử.',
    AppKeys.missingQuizIdShort: 'Thiếu quiz ID.',
  },
  'en': {
    AppKeys.noChapterTitle: 'No chapters',
    AppKeys.noChapterMessage:
        'No review journey is available for this profile.',
    AppKeys.startTest: 'Start test ({count})',
    AppKeys.practiceChapterTwoTitle: 'ADDITION AND SUBTRACTION WITHIN 10',
    AppKeys.reviewTitle: 'Learning journey',
    AppKeys.exercises: 'Exercises',
    AppKeys.days: 'Days',
    AppKeys.chapterMissingProfileInfo:
        'Profile is missing grade, program, or semester.',
    AppKeys.chapterLoadFailed: 'Failed to load chapters.',
    AppKeys.chapterLoadErrorTitle: 'Could not load chapters',
    AppKeys.test: 'Test',
    AppKeys.clearSelection: 'Clear',
    AppKeys.startChapterTestMessage: 'Starting test for chapter {chapter}.',
    AppKeys.startSelectedTestMessage: 'Starting test for {count} chapters.',
    AppKeys.chapter: 'Chapter',
    AppKeys.lessons: 'lessons',
    AppKeys.chapterNumber: 'Chapter {number}',
    AppKeys.lockedLessonMessage: 'Lesson {number}: {title} opens later.',
    AppKeys.learningPathChapterLesson: 'Chapter {chapter}, Lesson {lesson}',
    AppKeys.improveMathTypePrompt: 'Would you like to improve this math skill?',
    AppKeys.reviewLessonAction: 'Review',
    AppKeys.practiceLesson18Title: 'Addition within 10',
    AppKeys.practiceLesson19Title: 'Addition within 10 (continued)',
    AppKeys.practiceLesson20Title: 'Practice',
    AppKeys.practiceLesson21Title: 'Addition within 10 (continued)',
    AppKeys.practiceLesson22Title: 'Practice',
    AppKeys.practiceLesson23Title: 'Addition within 10 (continued)',
    AppKeys.practiceLesson24Title: 'Practice',
    AppKeys.practiceLesson25Title: 'Addition facts within 10',
    AppKeys.practiceLesson26Title: 'Practice',
    AppKeys.practiceLesson27Title: 'Subtraction within 10',
    AppKeys.historyTitle: 'History',
    AppKeys.searchHint: 'Search ...',
    AppKeys.assessmentTab: 'Assessment',
    AppKeys.practiceTab: 'Practice',
    AppKeys.historyLoadFailed: 'Failed to load history.',
    AppKeys.historyLoadErrorTitle: 'Could not load history',
    AppKeys.noHistoryTitle: 'No matching items',
    AppKeys.noHistoryMessage: 'Change the keyword to view other items.',
    AppKeys.missingQuizId: 'This test is missing quiz_id.',
    AppKeys.testAgain: 'Try Again',
    AppKeys.teacherStudyTitle: 'Study',
    AppKeys.teacherStudyAllClasses: 'All',
    AppKeys.teacherStudyLoadFailed:
        'Failed to load assignments and assessments.',
    AppKeys.teacherStudyNoResults: 'No matching content found.',
    AppKeys.teacherStudyDueDate: 'Due: {date}',
    AppKeys.teacherStudyMonth: 'M{month}',
    AppKeys.testAgainCreateMissingQuiz: 'Could not find the previous test.',
    AppKeys.testAgainCreateFailed:
        'Could not create a new test. Please try again.',
    AppKeys.testAgainDialogTitle: 'New test failed',
    AppKeys.missingUserOrProfileForHistory:
        'Missing user or profile to load history.',
    AppKeys.missingQuizIdShort: 'Missing quiz ID.',
  },
};
