import '../../app_keys.dart';

const examStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.assessmentGenerationFailed: 'Tạo bài đánh giá thất bại.',
    AppKeys.noGrades: 'Chưa có lớp học nào để hiển thị.',
    AppKeys.completedResultTitle: 'Hoàn Thành',
    AppKeys.incomplete: 'Chưa xong',
    AppKeys.mathAssessment: 'Bài kiểm tra Toán',
    AppKeys.kindergartenMathAssessment: 'Bài kiểm tra Toán Mẫu giáo',
    AppKeys.gradeMathAssessment: 'Bài kiểm tra Toán Lớp {grade}',
    AppKeys.assessmentListKindergartenTitle: 'Đánh Giá - Mẫu Giáo',
    AppKeys.assessmentListGradeTitle: 'Đánh Giá - Lớp {grade}',
    AppKeys.gradeLevelExamTitle: 'Bài Học - Lớp {grade} Level {level}',
    AppKeys.gradeRoadmapKindergarten: 'Mẫu giáo',
    AppKeys.gradeRoadmapGrade: 'Lớp {grade}',
    AppKeys.gradeRoadmapLevel: 'Level',
    AppKeys.gradeRoadmapCurrent: 'Đang học',
    AppKeys.gradeRoadmapCompleted: 'Đã hoàn thành',
    AppKeys.gradeRoadmapLocked: 'Chưa mở khóa',
    AppKeys.gradeRoadmapLoadFailed: 'Không tải được lộ trình level.',
    AppKeys.excellent: 'Tuyệt vời!',
    AppKeys.good: 'Tốt',
    AppKeys.niceTry: 'Cố gắng tốt',
    AppKeys.failed: 'Chưa đạt',
    AppKeys.examDetailLoadFailed: 'Tải chi tiết bài kiểm tra thất bại.',
    AppKeys.examDetailTitle: 'Chi Tiết',
    AppKeys.assessmentReviewHeaderTitle: 'Đề - {id}',
    AppKeys.emptyExamQuestions: 'Bài kiểm tra chưa có câu hỏi.',
    AppKeys.totalQuestions: 'Tổng câu',
    AppKeys.correct: 'Đúng',
    AppKeys.incorrect: 'Sai',
    AppKeys.questionNumber: 'Câu {number}',
    AppKeys.previous: 'Trước',
    AppKeys.next: 'Tiếp',
    AppKeys.correctStatus: 'Chính Xác',
    AppKeys.incorrectStatus: 'Chưa Đúng',
    AppKeys.answer: 'Đáp án: {answer}',
    AppKeys.examDetailErrorTitle: 'Không tải được chi tiết bài kiểm tra.',
    AppKeys.createQuestionFailed: 'Không thể tạo câu hỏi. Vui lòng thử lại.',
    AppKeys.missingExamToSubmit: 'Không tìm thấy bài test để nộp.',
    AppKeys.submitExamFailed: 'Nộp bài thất bại. Vui lòng thử lại.',
    AppKeys.unansweredSubmitTitle: 'Bạn có câu hỏi chưa trả lời',
    AppKeys.unansweredSubmitMessage: 'Bạn có chắc muốn nộp bài không?',
    AppKeys.stayUpper: 'Ở LẠI',
    AppKeys.submitUpper: 'NỘP BÀI',
    AppKeys.submittingForYou: 'đợi Numi nộp bài cho bạn nhé!',
    AppKeys.generatingAssessment: 'Để Numi tạo bài kiểm tra cho bạn nhé',
    AppKeys.assessmentHeaderTitle: 'Đánh giá',
    AppKeys.questionProgress: 'CÂU {current}/{total}',
    AppKeys.previousQuestionUpper: 'CÂU TRƯỚC',
    AppKeys.submittingUpper: 'ĐANG NỘP',
    AppKeys.excellentResultTitle: 'Xuất Sắc',
    AppKeys.goodResultTitle: 'Tốt',
    AppKeys.incompleteResultTitle: 'Chưa Hoàn Thành',
    AppKeys.generatingNewExam: 'đợi Numi tạo bài mới cho bạn nhé!',
    AppKeys.assessmentResultTitle: 'Kết Quả',
    AppKeys.assessmentResultHeaderTitle: 'Đánh Giá',
    AppKeys.practiceResultHeaderTitle: 'Luyện Tập',
    AppKeys.placementResultLevel: 'Trình độ',
    AppKeys.placementResultGradeHeading: 'GRADE',
    AppKeys.placementResultKindergarten: 'MẪU GIÁO',
    AppKeys.placementResultGrade: 'LỚP {grade}',
    AppKeys.placementResultGradeLevel: 'Cấp độ {level}',
    AppKeys.placementResultCorrectSummary:
        'Bạn đã trả lời đúng {correct}/{total} câu hỏi',
    AppKeys.placementResultReview: 'CHI TIẾT',
    AppKeys.placementResultPracticeAgain: 'Luyện tập lại',
    AppKeys.placementResultNext: 'TIẾP THEO',
    AppKeys.placementResultWeaknessesTitle: 'Điểm con cần cải thiện',
    AppKeys.placementResultYouAreHere: 'Bạn đang ở',
    AppKeys.placementResultChartGrade: 'Lớp',
    AppKeys.placementResultActivity: 'Trend',
    AppKeys.examReviewRetryTab: 'Ôn Lại',
    AppKeys.examReviewResultTab: 'Kết Quả',
    AppKeys.examReviewPracticeBannerTitle: 'AI LEARNING',
    AppKeys.examReviewGradeLevelBadge: '{grade} - Level {level}',
    AppKeys.examReviewWeakTopicsTitle: 'Nhận Xét',
    AppKeys.examReviewPerfectScoreMessage: 'Bạn đang làm rất tốt!',
    AppKeys.examReviewLoadFailed: 'Không tải được nhận xét. Vui lòng thử lại.',
    AppKeys.examReviewPracticeBannerAction: 'LUYỆN TẬP',
    AppKeys.scoreUpper: 'ĐIỂM SỐ',
    AppKeys.numiAiReview: 'Numi AI nhận xét',
    AppKeys.defaultAiReview:
        'Bé làm rất tốt phần phép cộng, hãy tiếp tục phát huy nhé! Chúng ta chỉ cần thôi.',
    AppKeys.defaultAiReviewHighlight: 'phép cộng',
    AppKeys.assessmentUpper: 'Đánh Giá',
    AppKeys.practiceUpper: 'Luyện Tập',
    AppKeys.examHasNoQuestions: 'Exam không có câu hỏi.',
  },
  'en': {
    AppKeys.assessmentGenerationFailed: 'Failed to create the assessment.',
    AppKeys.noGrades: 'No grades to show.',
    AppKeys.completedResultTitle: 'Completed',
    AppKeys.incomplete: 'Incomplete',
    AppKeys.mathAssessment: 'Math assessment',
    AppKeys.kindergartenMathAssessment: 'Kindergarten math assessment',
    AppKeys.gradeMathAssessment: 'Grade {grade} math assessment',
    AppKeys.assessmentListKindergartenTitle: 'Assessment - Kindergarten',
    AppKeys.assessmentListGradeTitle: 'Assessment - Grade {grade}',
    AppKeys.gradeLevelExamTitle: 'Learning - Grade {grade} Level {level}',
    AppKeys.gradeRoadmapKindergarten: 'Kindergarten',
    AppKeys.gradeRoadmapGrade: 'Grade {grade}',
    AppKeys.gradeRoadmapLevel: 'Level',
    AppKeys.gradeRoadmapCurrent: 'Current',
    AppKeys.gradeRoadmapCompleted: 'Completed',
    AppKeys.gradeRoadmapLocked: 'Locked',
    AppKeys.gradeRoadmapLoadFailed: 'Could not load the level roadmap.',
    AppKeys.excellent: 'Excellent!',
    AppKeys.good: 'Good',
    AppKeys.niceTry: 'Nice try',
    AppKeys.failed: 'Failed',
    AppKeys.examDetailLoadFailed: 'Failed to load test details.',
    AppKeys.examDetailTitle: 'Detail',
    AppKeys.assessmentReviewHeaderTitle: 'Test - {id}',
    AppKeys.emptyExamQuestions: 'This test has no questions.',
    AppKeys.totalQuestions: 'Questions',
    AppKeys.correct: 'Correct',
    AppKeys.incorrect: 'Wrong',
    AppKeys.questionNumber: 'Question {number}',
    AppKeys.previous: 'Previous',
    AppKeys.next: 'Next',
    AppKeys.correctStatus: 'Correct',
    AppKeys.incorrectStatus: 'Incorrect',
    AppKeys.answer: 'Answer: {answer}',
    AppKeys.examDetailErrorTitle: 'Could not load test details.',
    AppKeys.createQuestionFailed:
        'Could not create questions. Please try again.',
    AppKeys.missingExamToSubmit: 'Could not find a test to submit.',
    AppKeys.submitExamFailed: 'Failed to submit. Please try again.',
    AppKeys.unansweredSubmitTitle: 'Some questions are unanswered',
    AppKeys.unansweredSubmitMessage: 'Are you sure you want to submit now?',
    AppKeys.stayUpper: 'STAY',
    AppKeys.submitUpper: 'SUBMIT',
    AppKeys.submittingForYou: 'Numi is submitting your test...',
    AppKeys.generatingAssessment: 'Let Numi create your test',
    AppKeys.assessmentHeaderTitle: 'Assessment',
    AppKeys.questionProgress: 'QUESTION {current}/{total}',
    AppKeys.previousQuestionUpper: 'PREVIOUS',
    AppKeys.submittingUpper: 'SUBMITTING',
    AppKeys.excellentResultTitle: 'Excellent',
    AppKeys.goodResultTitle: 'Good',
    AppKeys.incompleteResultTitle: 'Not Completed',
    AppKeys.generatingNewExam: 'Numi is creating a new test...',
    AppKeys.assessmentResultTitle: 'Result',
    AppKeys.assessmentResultHeaderTitle: 'Assessment',
    AppKeys.practiceResultHeaderTitle: 'Practice',
    AppKeys.placementResultLevel: 'Level',
    AppKeys.placementResultGradeHeading: 'GRADE',
    AppKeys.placementResultKindergarten: 'KINDERGARTEN',
    AppKeys.placementResultGrade: 'GRADE {grade}',
    AppKeys.placementResultGradeLevel: 'Level {level}',
    AppKeys.placementResultCorrectSummary:
        'You answered {correct}/{total} questions correctly',
    AppKeys.placementResultReview: 'REVIEW',
    AppKeys.placementResultPracticeAgain: 'Practice again',
    AppKeys.placementResultNext: 'NEXT',
    AppKeys.placementResultWeaknessesTitle: 'Child Weaknesses',
    AppKeys.placementResultYouAreHere: 'You are here',
    AppKeys.placementResultChartGrade: 'Grade',
    AppKeys.placementResultActivity: 'Trend',
    AppKeys.examReviewRetryTab: 'Revise',
    AppKeys.examReviewResultTab: 'Results',
    AppKeys.examReviewPracticeBannerTitle: 'AI LEARNING',
    AppKeys.examReviewGradeLevelBadge: '{grade} - Level {level}',
    AppKeys.examReviewWeakTopicsTitle: 'Review',
    AppKeys.examReviewPerfectScoreMessage: 'You are doing good!',
    AppKeys.examReviewLoadFailed:
        'Could not load the review. Please try again.',
    AppKeys.examReviewPracticeBannerAction: 'PRACTICE',
    AppKeys.scoreUpper: 'SCORE',
    AppKeys.numiAiReview: 'Numi AI review',
    AppKeys.defaultAiReview:
        'Your child did very well with addition. Keep going, and practice subtraction with regrouping a little more.',
    AppKeys.defaultAiReviewHighlight: 'addition',
    AppKeys.assessmentUpper: 'Review',
    AppKeys.practiceUpper: 'Practice',
    AppKeys.examHasNoQuestions: 'Exam has no questions.',
  },
};
