import '../../app_keys.dart';

const examStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.assessmentGenerationFailed: 'Tạo bài đánh giá thất bại.',
    AppKeys.noGrades: 'Chưa có lớp học nào để hiển thị.',
    AppKeys.completedResultTitle: 'Hoàn Thành',
    AppKeys.incomplete: 'Chưa xong',
    AppKeys.mathAssessment: 'Bài kiểm tra Toán',
    AppKeys.kindergartenMathAssessment: 'Bài kiểm tra Toán Mẫu giáo',
    AppKeys.gradeMathAssessment: 'Bài kiểm tra Toán Lớp {grade}',
    AppKeys.mathPractice: 'Bài luyện tập Toán',
    AppKeys.mathReview: 'Bài ôn tập Toán',
    AppKeys.excellent: 'Tuyệt vời!',
    AppKeys.good: 'Tốt',
    AppKeys.niceTry: 'Cố gắng tốt',
    AppKeys.failed: 'Chưa đạt',
    AppKeys.examDetailLoadFailed: 'Tải chi tiết bài kiểm tra thất bại.',
    AppKeys.examDetailTitle: 'Chi Tiết',
    AppKeys.emptyExamQuestions: 'Bài kiểm tra chưa có câu hỏi.',
    AppKeys.totalQuestions: 'Tổng câu',
    AppKeys.correct: 'Đúng',
    AppKeys.incorrect: 'Sai',
    AppKeys.questionNumber: 'Câu {number}',
    AppKeys.viewResult: 'Xem Kết Quả',
    AppKeys.previous: 'Trước',
    AppKeys.next: 'Tiếp',
    AppKeys.correctStatus: 'Chính Xác',
    AppKeys.incorrectStatus: 'Chưa Đúng',
    AppKeys.showAnswerUpper: 'ĐÁP ÁN',
    AppKeys.hideAnswerUpper: 'ẨN ĐÁP ÁN',
    AppKeys.noAnswer: 'Chưa có đáp án.',
    AppKeys.answer: 'Đáp án: {answer}',
    AppKeys.examDetailErrorTitle: 'Không tải được chi tiết bài kiểm tra.',
    AppKeys.createQuestionFailed: 'Không thể tạo câu hỏi. Vui lòng thử lại.',
    AppKeys.missingExamToSubmit: 'Không tìm thấy bài test để nộp.',
    AppKeys.submitExamFailed: 'Nộp bài thất bại. Vui lòng thử lại.',
    AppKeys.unansweredSubmitTitle: 'Bạn có câu hỏi chưa trả lời',
    AppKeys.unansweredSubmitMessage: 'Bạn có chắc muốn nộp bài không?',
    AppKeys.stayUpper: 'Ở LẠI',
    AppKeys.submitUpper: 'NỘP BÀI',
    AppKeys.submittingForYou: 'đợi Numi nộp bài cho bạn nhé!',
    AppKeys.generatingAssessment: 'Để Numi tạo bài kiểm tra cho bạn nhé',
    AppKeys.aiChallenge: 'Thử thách AI',
    AppKeys.assessmentHeaderTitle: 'Đánh giá',
    AppKeys.questionProgress: 'CÂU {current}/{total}',
    AppKeys.previousQuestionUpper: 'CÂU TRƯỚC',
    AppKeys.submittingUpper: 'ĐANG NỘP',
    AppKeys.excellentResultTitle: 'Xuất Sắc',
    AppKeys.goodResultTitle: 'Tốt',
    AppKeys.incompleteResultTitle: 'Chưa Hoàn Thành',
    AppKeys.excellentResultMessage: '',
    AppKeys.generatingNewExam: 'đợi Numi tạo bài mới cho bạn nhé!',
    AppKeys.assessmentResultTitle: 'Kết Quả',
    AppKeys.placementResultCongratulations: 'Chúc mừng!',
    AppKeys.placementResultLevel: 'Bạn đạt trình độ',
    AppKeys.placementResultKindergarten: 'MẪU GIÁO',
    AppKeys.placementResultGrade: 'LỚP {grade}',
    AppKeys.placementResultCorrectSummary:
        'Bạn đã trả lời đúng {correct}/{total} câu hỏi',
    AppKeys.placementResultViewDetails: 'Xem chi tiết',
    AppKeys.placementResultPracticeAgain: 'Luyện tập lại',
    AppKeys.scoreUpper: 'ĐIỂM SỐ',
    AppKeys.numiAiReview: 'Numi AI nhận xét',
    AppKeys.defaultAiReview:
        'Bé làm rất tốt phần phép cộng, hãy tiếp tục phát huy nhé! Chúng ta chỉ cần thôi.',
    AppKeys.defaultAiReviewHighlight: 'phép cộng',
    AppKeys.assessmentUpper: 'Đánh Giá',
    AppKeys.practiceUpper: 'Luyện Tập',
    AppKeys.examHasNoQuestions: 'Exam không có câu hỏi.',
  },
  'en': {
    AppKeys.assessmentGenerationFailed: 'Failed to create the assessment.',
    AppKeys.noGrades: 'No grades to show.',
    AppKeys.completedResultTitle: 'Completed',
    AppKeys.incomplete: 'Incomplete',
    AppKeys.mathAssessment: 'Math assessment',
    AppKeys.kindergartenMathAssessment: 'Kindergarten math assessment',
    AppKeys.gradeMathAssessment: 'Grade {grade} math assessment',
    AppKeys.mathPractice: 'Math practice',
    AppKeys.mathReview: 'Math review',
    AppKeys.excellent: 'Excellent!',
    AppKeys.good: 'Good',
    AppKeys.niceTry: 'Nice try',
    AppKeys.failed: 'Failed',
    AppKeys.examDetailLoadFailed: 'Failed to load test details.',
    AppKeys.examDetailTitle: 'Detail',
    AppKeys.emptyExamQuestions: 'This test has no questions.',
    AppKeys.totalQuestions: 'Questions',
    AppKeys.correct: 'Correct',
    AppKeys.incorrect: 'Wrong',
    AppKeys.questionNumber: 'Question {number}',
    AppKeys.viewResult: 'View Result',
    AppKeys.previous: 'Previous',
    AppKeys.next: 'Next',
    AppKeys.correctStatus: 'Correct',
    AppKeys.incorrectStatus: 'Incorrect',
    AppKeys.showAnswerUpper: 'ANSWER',
    AppKeys.hideAnswerUpper: 'HIDE ANSWER',
    AppKeys.noAnswer: 'No answer available.',
    AppKeys.answer: 'Answer: {answer}',
    AppKeys.examDetailErrorTitle: 'Could not load test details.',
    AppKeys.createQuestionFailed:
        'Could not create questions. Please try again.',
    AppKeys.missingExamToSubmit: 'Could not find a test to submit.',
    AppKeys.submitExamFailed: 'Failed to submit. Please try again.',
    AppKeys.unansweredSubmitTitle: 'Some questions are unanswered',
    AppKeys.unansweredSubmitMessage: 'Are you sure you want to submit now?',
    AppKeys.stayUpper: 'STAY',
    AppKeys.submitUpper: 'SUBMIT',
    AppKeys.submittingForYou: 'Numi is submitting your test...',
    AppKeys.generatingAssessment: 'Let Numi create your test',
    AppKeys.aiChallenge: 'AI Challenge',
    AppKeys.assessmentHeaderTitle: 'Assessment',
    AppKeys.questionProgress: 'QUESTION {current}/{total}',
    AppKeys.previousQuestionUpper: 'PREVIOUS',
    AppKeys.submittingUpper: 'SUBMITTING',
    AppKeys.excellentResultTitle: 'Excellent',
    AppKeys.goodResultTitle: 'Good',
    AppKeys.incompleteResultTitle: 'Not Completed',
    AppKeys.excellentResultMessage: '',
    AppKeys.generatingNewExam: 'Numi is creating a new test...',
    AppKeys.assessmentResultTitle: 'Result',
    AppKeys.placementResultCongratulations: 'Congratulations!',
    AppKeys.placementResultLevel: 'Your level is',
    AppKeys.placementResultKindergarten: 'KINDERGARTEN',
    AppKeys.placementResultGrade: 'GRADE {grade}',
    AppKeys.placementResultCorrectSummary:
        'You answered {correct}/{total} questions correctly',
    AppKeys.placementResultViewDetails: 'View details',
    AppKeys.placementResultPracticeAgain: 'Practice again',
    AppKeys.scoreUpper: 'SCORE',
    AppKeys.numiAiReview: 'Numi AI review',
    AppKeys.defaultAiReview:
        'Your child did very well with addition. Keep going, and practice subtraction with regrouping a little more.',
    AppKeys.defaultAiReviewHighlight: 'addition',
    AppKeys.assessmentUpper: 'Review',
    AppKeys.practiceUpper: 'Practice',
    AppKeys.examHasNoQuestions: 'Exam has no questions.',
  },
};
