import '../../app_keys.dart';

const studentClassroomStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.studentMissingProfileId: 'Hồ sơ học sinh thiếu profile_id.',
    AppKeys.studentRetry: 'Thử lại',
    AppKeys.studentNoClassSearchResults: 'Không tìm thấy lớp học',
    AppKeys.studentNoClassSearchResultsMessage:
        'Kiểm tra lại mã lớp hoặc tên lớp rồi thử lại.',
    AppKeys.studentEnterClassCodeTitle: 'Nhập mã hoặc tên lớp',
    AppKeys.studentEnterClassCodeMessage:
        'Kết quả lớp học phù hợp sẽ hiển thị tại đây.',
    AppKeys.studentAlreadyJoinedClass: 'Bạn đã tham gia lớp học này.',
    AppKeys.studentClassroom: 'Lớp học',
    AppKeys.studentJoinNewClassroom: 'Tham gia lớp mới',
    AppKeys.studentJoinAnotherClassroom: 'Tham gia lớp khác',
    AppKeys.studentJoinClassroomSoon: 'Tính năng tham gia lớp sẽ sớm có mặt.',
    AppKeys.studentClassroomLoadFailed: 'Tải danh sách lớp học thất bại.',
    AppKeys.studentClassCodeHint: 'Nhập mã lớp',
    AppKeys.studentSearchClass: 'Tìm kiếm lớp học',
    AppKeys.studentSearchResults: 'Kết quả tìm kiếm',
    AppKeys.studentDefaultSchoolFilter: 'Trường Lưu Tấn Phát',
    AppKeys.studentGradeFilter: 'Lớp {grade}',
    AppKeys.studentClassSearchFailed: 'Tìm kiếm lớp học thất bại.',
    AppKeys.studentClassSearchLoading: 'Đang tìm lớp phù hợp...',
    AppKeys.studentClassSearchRetry:
        'Không thể hoàn tất tìm kiếm. Kiểm tra kết nối rồi thử lại.',
    AppKeys.studentClassFilterLoadFailed:
        'Không thể tải bộ lọc. Bạn vẫn có thể tìm bằng mã hoặc tên lớp.',
    AppKeys.studentClassMissingCode: 'Lớp học này chưa có mã tham gia.',
    AppKeys.studentJoinClassSuccess: 'Đã gửi yêu cầu tham gia lớp.',
    AppKeys.studentJoinClassFailed: 'Không thể gửi yêu cầu tham gia lớp.',
    AppKeys.studentClassJoinRequestPending:
        'Lớp học này đã có lời mời hoặc yêu cầu đang chờ.',
    AppKeys.studentClassCodeLabel: 'CODE: {code}',
    AppKeys.studentClassRelationshipMember: 'ĐÃ THAM GIA',
    AppKeys.studentClassRelationshipPendingInvitation: 'ĐÃ ĐƯỢC MỜI',
    AppKeys.studentClassRelationshipPendingRequest: 'ĐANG CHỜ',
    AppKeys.studentClassRelationshipNone: 'CHƯA THAM GIA',
    AppKeys.studentClassInvitations: 'Lời mời lớp học',
    AppKeys.studentViewAllInvitations: 'Xem tất cả ({count})',
    AppKeys.studentViewAllClassrooms: 'Xem tất cả ({count})',
    AppKeys.parentSwitchStudentTitle: 'Chuyển sang hồ sơ học sinh',
    AppKeys.parentSwitchStudentMessage:
        'Tính năng lớp học chỉ dùng được với hồ sơ học sinh. Vui lòng chuyển sang hồ sơ học sinh để tiếp tục.',
    AppKeys.parentSwitchStudentAction: 'Chọn hồ sơ',
    AppKeys.studentInviteSubtitle: '{name} mời bạn',
    AppKeys.studentInviteSubtitleFallback: 'Giáo viên mời bạn',
    AppKeys.studentInvitationLoadFailed: 'Không thể tải lời mời lớp học.',
    AppKeys.studentInvitationAcceptSuccess: 'Đã tham gia lớp học.',
    AppKeys.studentInvitationRejectSuccess: 'Đã từ chối lời mời.',
    AppKeys.studentJoinClassroomUpper: 'THAM GIA LỚP HỌC',
    AppKeys.studentClassDetailTitle: 'Lớp Học',
    AppKeys.studentClassTeacherRole: 'GIÁO VIÊN',
    AppKeys.studentClassLearningCategories: 'Phân loại học tập',
    AppKeys.studentClassAssignments: 'Bài tập về nhà',
    AppKeys.studentClassAssignmentsSubtitle: '3 nhiệm vụ mới',
    AppKeys.studentClassAssignmentsCountFormat: '{count} bài tập',
    AppKeys.studentClassQuizzes: 'Bài kiểm tra',
    AppKeys.studentClassQuizzesSubtitle: 'Thử thách mới',
    AppKeys.studentClassMaterials: 'Tài liệu',
    AppKeys.studentClassMaterialsSubtitle: '12 thư mục',
    AppKeys.studentClassGrades: 'Bảng điểm',
    AppKeys.studentClassGradesSubtitle: 'Điểm TB: 8.5',
    AppKeys.studentClassUpcomingDeadlines: 'Sắp tới hạn',
    AppKeys.studentClassAll: 'Tất cả',
    AppKeys.studentClassReview15Minutes: 'Ôn tập 15 phút',
    AppKeys.studentClassDeadlineSample: 'Hạn nộp: 21:00 31/05/2026',
    AppKeys.studentClassComingSoon: 'Tính năng sẽ sớm có mặt.',
  },
  'en': {
    AppKeys.studentMissingProfileId: 'Student profile is missing profile_id.',
    AppKeys.studentRetry: 'Try again',
    AppKeys.studentNoClassSearchResults: 'No classrooms found',
    AppKeys.studentNoClassSearchResultsMessage:
        'Check the class code or class name and try again.',
    AppKeys.studentEnterClassCodeTitle: 'Enter a code or class name',
    AppKeys.studentEnterClassCodeMessage:
        'Matching classroom results will appear here.',
    AppKeys.studentAlreadyJoinedClass: 'You have already joined this class.',
    AppKeys.studentClassroom: 'Classroom',
    AppKeys.studentJoinNewClassroom: 'Join new classroom',
    AppKeys.studentJoinAnotherClassroom: 'Join another classroom',
    AppKeys.studentJoinClassroomSoon: 'Classroom joining is coming soon.',
    AppKeys.studentClassroomLoadFailed: 'Failed to load classrooms.',
    AppKeys.studentClassCodeHint: 'Enter class code',
    AppKeys.studentSearchClass: 'Search classrooms',
    AppKeys.studentSearchResults: 'Search results',
    AppKeys.studentDefaultSchoolFilter: 'Luu Tan Phat School',
    AppKeys.studentGradeFilter: 'Grade {grade}',
    AppKeys.studentClassSearchFailed: 'Failed to search classrooms.',
    AppKeys.studentClassSearchLoading: 'Searching for matching classes...',
    AppKeys.studentClassSearchRetry:
        'The search could not be completed. Check your connection and try again.',
    AppKeys.studentClassFilterLoadFailed:
        'Filters could not be loaded. You can still search by code or class name.',
    AppKeys.studentClassMissingCode: 'This classroom has no join code yet.',
    AppKeys.studentJoinClassSuccess: 'Class join request sent.',
    AppKeys.studentJoinClassFailed: 'Could not send class join request.',
    AppKeys.studentClassJoinRequestPending:
        'This classroom already has a pending invitation or request.',
    AppKeys.studentClassCodeLabel: 'CODE: {code}',
    AppKeys.studentClassRelationshipMember: 'JOINED',
    AppKeys.studentClassRelationshipPendingInvitation: 'INVITED',
    AppKeys.studentClassRelationshipPendingRequest: 'PENDING',
    AppKeys.studentClassRelationshipNone: 'NOT JOINED',
    AppKeys.studentClassInvitations: 'Class invitations',
    AppKeys.studentViewAllInvitations: 'View all ({count})',
    AppKeys.studentViewAllClassrooms: 'View all ({count})',
    AppKeys.parentSwitchStudentTitle: 'Switch to a student profile',
    AppKeys.parentSwitchStudentMessage:
        'Classroom features are only available for student profiles. Please switch to a student profile to continue.',
    AppKeys.parentSwitchStudentAction: 'Choose profile',
    AppKeys.studentInviteSubtitle: '{name} invited you',
    AppKeys.studentInviteSubtitleFallback: 'Your teacher invited you',
    AppKeys.studentInvitationLoadFailed: 'Could not load class invitations.',
    AppKeys.studentInvitationAcceptSuccess: 'Joined classroom.',
    AppKeys.studentInvitationRejectSuccess: 'Invitation rejected.',
    AppKeys.studentJoinClassroomUpper: 'JOIN CLASSROOM',
    AppKeys.studentClassDetailTitle: 'Class',
    AppKeys.studentClassTeacherRole: 'TEACHER',
    AppKeys.studentClassLearningCategories: 'Learning categories',
    AppKeys.studentClassAssignments: 'Homework',
    AppKeys.studentClassAssignmentsSubtitle: '3 new tasks',
    AppKeys.studentClassAssignmentsCountFormat: '{count} assignments',
    AppKeys.studentClassQuizzes: 'Quizzes',
    AppKeys.studentClassQuizzesSubtitle: 'New challenge',
    AppKeys.studentClassMaterials: 'Materials',
    AppKeys.studentClassMaterialsSubtitle: '12 folders',
    AppKeys.studentClassGrades: 'Grades',
    AppKeys.studentClassGradesSubtitle: 'Average score: 8.5',
    AppKeys.studentClassUpcomingDeadlines: 'Upcoming deadlines',
    AppKeys.studentClassAll: 'All',
    AppKeys.studentClassReview15Minutes: '15-minute review',
    AppKeys.studentClassDeadlineSample: 'Due: 21:00 05/31/2026',
    AppKeys.studentClassComingSoon: 'This feature is coming soon.',
  },
};
