import '../../app_keys.dart';

const studentClassroomStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.studentClassroom: 'Lá»›p há»c',
    AppKeys.studentJoinNewClassroom: 'Tham gia lá»›p má»›i',
    AppKeys.studentJoinAnotherClassroom: 'Tham gia lá»›p khÃ¡c',
    AppKeys.studentJoinClassroomSoon:
        'TÃ­nh nÄƒng tham gia lá»›p sáº½ sá»›m cÃ³ máº·t.',
    AppKeys.studentClassroomLoadFailed:
        'Táº£i danh sÃ¡ch lá»›p há»c tháº¥t báº¡i.',
    AppKeys.studentClassCodeHint: 'Nháº­p mÃ£ lá»›p',
    AppKeys.studentSearchClass: 'TÃ¬m kiáº¿m lá»›p há»c',
    AppKeys.studentSearchResults: 'Káº¿t quáº£ tÃ¬m kiáº¿m',
    AppKeys.studentDefaultSchoolFilter: 'TrÆ°á»ng LÆ°u Táº¥n PhÃ¡t',
    AppKeys.studentGradeFilter: 'Lá»›p {grade}',
    AppKeys.studentClassSearchFailed: 'TÃ¬m kiáº¿m lá»›p há»c tháº¥t báº¡i.',
    AppKeys.studentClassSearchLoading: 'Äang tÃ¬m lá»›p phÃ¹ há»£p...',
    AppKeys.studentClassSearchRetry:
        'KhÃ´ng thá»ƒ hoÃ n táº¥t tÃ¬m kiáº¿m. Kiá»ƒm tra káº¿t ná»‘i rá»“i thá»­ láº¡i.',
    AppKeys.studentClassFilterLoadFailed:
        'KhÃ´ng thá»ƒ táº£i bá»™ lá»c. Báº¡n váº«n cÃ³ thá»ƒ tÃ¬m báº±ng mÃ£ hoáº·c tÃªn lá»›p.',
    AppKeys.studentClassMissingCode: 'Lá»›p há»c nÃ y chÆ°a cÃ³ mÃ£ tham gia.',
    AppKeys.studentJoinClassSuccess: 'ÄÃ£ gá»­i yÃªu cáº§u tham gia lá»›p.',
    AppKeys.studentJoinClassFailed:
        'KhÃ´ng thá»ƒ gá»­i yÃªu cáº§u tham gia lá»›p.',
    AppKeys.studentClassJoinRequestPending:
        'Lá»›p há»c nÃ y Ä‘Ã£ cÃ³ lá»i má»i hoáº·c yÃªu cáº§u Ä‘ang chá».',
    AppKeys.studentClassCodeLabel: 'CODE: {code}',
    AppKeys.studentClassRelationshipMember: 'ÄÃƒ THAM GIA',
    AppKeys.studentClassRelationshipPendingInvitation: 'ÄÃƒ ÄÆ¯á»¢C Má»œI',
    AppKeys.studentClassRelationshipPendingRequest: 'ÄANG CHá»œ',
    AppKeys.studentClassRelationshipNone: 'CHÆ¯A THAM GIA',
    AppKeys.studentClassInvitations: 'Lá»i má»i lá»›p há»c',
    AppKeys.studentViewAllInvitations: 'Xem táº¥t cáº£ ({count})',
    AppKeys.studentViewAllClassrooms: 'Xem táº¥t cáº£ ({count})',
    AppKeys.parentSwitchStudentTitle: 'Chuyá»ƒn sang há»“ sÆ¡ há»c sinh',
    AppKeys.parentSwitchStudentMessage:
        'TÃ­nh nÄƒng lá»›p há»c chá»‰ dÃ¹ng Ä‘Æ°á»£c vá»›i há»“ sÆ¡ há»c sinh. Vui lÃ²ng chuyá»ƒn sang há»“ sÆ¡ há»c sinh Ä‘á»ƒ tiáº¿p tá»¥c.',
    AppKeys.parentSwitchStudentAction: 'Chá»n há»“ sÆ¡',
    AppKeys.studentInviteSubtitle: '{name} má»i báº¡n',
    AppKeys.studentInviteSubtitleFallback: 'GiÃ¡o viÃªn má»i báº¡n',
    AppKeys.studentInvitationLoadFailed:
        'KhÃ´ng thá»ƒ táº£i lá»i má»i lá»›p há»c.',
    AppKeys.studentInvitationAcceptSuccess: 'ÄÃ£ tham gia lá»›p há»c.',
    AppKeys.studentInvitationRejectSuccess: 'ÄÃ£ tá»« chá»‘i lá»i má»i.',
    AppKeys.studentJoinClassroomUpper: 'THAM GIA Lá»šP Há»ŒC',
    AppKeys.studentClassDetailTitle: 'Lá»›p Há»c',
    AppKeys.studentClassTeacherRole: 'GIÃO VIÃŠN',
    AppKeys.studentClassLearningCategories: 'PhÃ¢n loáº¡i há»c táº­p',
    AppKeys.studentClassAssignments: 'BÃ i táº­p vá» nhÃ ',
    AppKeys.studentClassAssignmentsSubtitle: '3 nhiá»‡m vá»¥ má»›i',
    AppKeys.studentClassAssignmentsCountFormat: '{count} bÃ i táº­p',
    AppKeys.studentClassQuizzes: 'BÃ i kiá»ƒm tra',
    AppKeys.studentClassQuizzesSubtitle: 'Thá»­ thÃ¡ch má»›i',
    AppKeys.studentClassMaterials: 'TÃ i liá»‡u',
    AppKeys.studentClassMaterialsSubtitle: '12 thÆ° má»¥c',
    AppKeys.studentClassGrades: 'Báº£ng Ä‘iá»ƒm',
    AppKeys.studentClassGradesSubtitle: 'Äiá»ƒm TB: 8.5',
    AppKeys.studentClassUpcomingDeadlines: 'Sáº¯p tá»›i háº¡n',
    AppKeys.studentClassAll: 'Táº¥t cáº£',
    AppKeys.studentClassReview15Minutes: 'Ã”n táº­p 15 phÃºt',
    AppKeys.studentClassDeadlineSample: 'Háº¡n ná»™p: 21:00 31/05/2026',
    AppKeys.studentClassComingSoon: 'TÃ­nh nÄƒng sáº½ sá»›m cÃ³ máº·t.',
  },
  'en': {
    AppKeys.studentClassroom: 'Classroom',
    AppKeys.studentJoinNewClassroom: 'Join new classroom',
    AppKeys.studentJoinAnotherClassroom: 'Join another classroom',
    AppKeys.studentJoinClassroomSoon: 'Classroom joining is coming soon.',
    AppKeys.studentClassroomLoadFailed: 'Failed to load classrooms.',
    AppKeys.studentClassCodeHint: 'Enter class code',
    AppKeys.studentSearchClass: 'Search classrooms',
    AppKeys.studentSearchResults: 'Search results',
    AppKeys.studentDefaultSchoolFilter: 'Luu Tan Phat School',
    AppKeys.studentGradeFilter: 'Grade {grade}',
    AppKeys.studentClassSearchFailed: 'Failed to search classrooms.',
    AppKeys.studentClassSearchLoading: 'Searching for matching classes...',
    AppKeys.studentClassSearchRetry:
        'The search could not be completed. Check your connection and try again.',
    AppKeys.studentClassFilterLoadFailed:
        'Filters could not be loaded. You can still search by code or class name.',
    AppKeys.studentClassMissingCode: 'This classroom has no join code yet.',
    AppKeys.studentJoinClassSuccess: 'Class join request sent.',
    AppKeys.studentJoinClassFailed: 'Could not send class join request.',
    AppKeys.studentClassJoinRequestPending:
        'This classroom already has a pending invitation or request.',
    AppKeys.studentClassCodeLabel: 'CODE: {code}',
    AppKeys.studentClassRelationshipMember: 'JOINED',
    AppKeys.studentClassRelationshipPendingInvitation: 'INVITED',
    AppKeys.studentClassRelationshipPendingRequest: 'PENDING',
    AppKeys.studentClassRelationshipNone: 'NOT JOINED',
    AppKeys.studentClassInvitations: 'Class invitations',
    AppKeys.studentViewAllInvitations: 'View all ({count})',
    AppKeys.studentViewAllClassrooms: 'View all ({count})',
    AppKeys.parentSwitchStudentTitle: 'Switch to a student profile',
    AppKeys.parentSwitchStudentMessage:
        'Classroom features are only available for student profiles. Please switch to a student profile to continue.',
    AppKeys.parentSwitchStudentAction: 'Choose profile',
    AppKeys.studentInviteSubtitle: '{name} invited you',
    AppKeys.studentInviteSubtitleFallback: 'Your teacher invited you',
    AppKeys.studentInvitationLoadFailed: 'Could not load class invitations.',
    AppKeys.studentInvitationAcceptSuccess: 'Joined classroom.',
    AppKeys.studentInvitationRejectSuccess: 'Invitation rejected.',
    AppKeys.studentJoinClassroomUpper: 'JOIN CLASSROOM',
    AppKeys.studentClassDetailTitle: 'Class',
    AppKeys.studentClassTeacherRole: 'TEACHER',
    AppKeys.studentClassLearningCategories: 'Learning categories',
    AppKeys.studentClassAssignments: 'Homework',
    AppKeys.studentClassAssignmentsSubtitle: '3 new tasks',
    AppKeys.studentClassAssignmentsCountFormat: '{count} assignments',
    AppKeys.studentClassQuizzes: 'Quizzes',
    AppKeys.studentClassQuizzesSubtitle: 'New challenge',
    AppKeys.studentClassMaterials: 'Materials',
    AppKeys.studentClassMaterialsSubtitle: '12 folders',
    AppKeys.studentClassGrades: 'Grades',
    AppKeys.studentClassGradesSubtitle: 'Average score: 8.5',
    AppKeys.studentClassUpcomingDeadlines: 'Upcoming deadlines',
    AppKeys.studentClassAll: 'All',
    AppKeys.studentClassReview15Minutes: '15-minute review',
    AppKeys.studentClassDeadlineSample: 'Due: 21:00 05/31/2026',
    AppKeys.studentClassComingSoon: 'This feature is coming soon.',
  },
};
