import '../../app_keys.dart';

const studentClassroomStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.studentMissingProfileId: 'Hồ sơ học sinh thiếu profile_id.',
    AppKeys.studentRetry: 'Thử lại',
    AppKeys.studentNoClassSearchResults: 'Không tìm thấy lớp học',
    AppKeys.studentNoClassSearchResultsMessage:
        'Kiểm tra lại mã lớp hoặc tên lớp rồi thử lại.',
    AppKeys.studentEnterClassCodeTitle: 'Nhập mã hoặc tên lớp',
    AppKeys.studentEnterClassCodeMessage:
        'Kết quả lớp học phù hợp sẽ hiển thị tại đây.',
    AppKeys.studentAlreadyJoinedClass: 'Bạn đã tham gia lớp học này.',
    AppKeys.studentClassroom: 'Lớp học',
    AppKeys.studentJoinAnotherClassroom: 'Tham gia lớp khác',
    AppKeys.studentJoinClassroom: 'Tham gia lớp học',
    AppKeys.studentClassroomLoadFailed: 'Tải danh sách lớp học thất bại.',
    AppKeys.studentClassCodeHint: 'Nhập mã lớp',
    AppKeys.studentSearchClass: 'Tìm kiếm lớp học',
    AppKeys.studentSearchResults: 'Kết quả tìm kiếm',
    AppKeys.studentGradeFilter: 'Lớp {grade}',
    AppKeys.studentClassSearchFailed: 'Tìm kiếm lớp học thất bại.',
    AppKeys.studentClassSearchLoading: 'Đang tìm lớp phù hợp...',
    AppKeys.studentClassSearchRetry:
        'Không thể hoàn tất tìm kiếm. Kiểm tra kết nối rồi thử lại.',
    AppKeys.studentClassFilterLoadFailed:
        'Không thể tải bộ lọc. Bạn vẫn có thể tìm bằng mã hoặc tên lớp.',
    AppKeys.studentClassMissingCode: 'Lớp học này chưa có mã tham gia.',
    AppKeys.studentJoinClassFailed: 'Không thể gửi yêu cầu tham gia lớp.',
    AppKeys.studentClassJoinRequestPending:
        'Lớp học này đã có lời mời hoặc yêu cầu đang chờ.',
    AppKeys.studentClassCodeLabel: 'CODE: {code}',
    AppKeys.studentClassRelationshipMember: 'ĐÃ THAM GIA',
    AppKeys.studentClassRelationshipPendingInvitation: 'ĐÃ ĐƯỢC MỜI',
    AppKeys.studentClassRelationshipPendingRequest: 'ĐANG CHỜ',
    AppKeys.studentClassRelationshipNone: 'CHƯA THAM GIA',
    AppKeys.parentSwitchStudentAction: 'Chọn hồ sơ',
    AppKeys.studentClassDetailTitle: 'Lớp Học',
    AppKeys.studentClassTeacherRole: 'GIÁO VIÊN',
    AppKeys.studentClassLearningCategories: 'Phân loại học tập',
    AppKeys.studentClassAssignments: 'Bài tập về nhà',
    AppKeys.studentClassAssignmentsCountFormat: '{count} bài tập',
    AppKeys.studentClassExams: 'Bài kiểm tra',
    AppKeys.studentClassExamsSubtitle: 'Thử thách mới',
    AppKeys.studentClassMaterials: 'Tài liệu',
    AppKeys.studentClassMaterialsSubtitle: '12 thư mục',
    AppKeys.studentClassGrades: 'Bảng điểm',
    AppKeys.studentClassGradesSubtitle: 'Điểm TB: 8.5',
    AppKeys.studentClassUpcomingDeadlines: 'Sắp tới hạn',
    AppKeys.studentClassAll: 'Tất cả',
    AppKeys.studentClassComingSoon: 'Tính năng sẽ sớm có mặt.',
  },
  'en': {
    AppKeys.studentMissingProfileId: 'Student profile is missing profile_id.',
    AppKeys.studentRetry: 'Try again',
    AppKeys.studentNoClassSearchResults: 'No classrooms found',
    AppKeys.studentNoClassSearchResultsMessage:
        'Check the class code or class name and try again.',
    AppKeys.studentEnterClassCodeTitle: 'Enter a code or class name',
    AppKeys.studentEnterClassCodeMessage:
        'Matching classroom results will appear here.',
    AppKeys.studentAlreadyJoinedClass: 'You have already joined this class.',
    AppKeys.studentClassroom: 'Classroom',
    AppKeys.studentJoinAnotherClassroom: 'Join another classroom',
    AppKeys.studentJoinClassroom: 'Join classroom',
    AppKeys.studentClassroomLoadFailed: 'Failed to load classrooms.',
    AppKeys.studentClassCodeHint: 'Enter class code',
    AppKeys.studentSearchClass: 'Search classrooms',
    AppKeys.studentSearchResults: 'Search results',
    AppKeys.studentGradeFilter: 'Grade {grade}',
    AppKeys.studentClassSearchFailed: 'Failed to search classrooms.',
    AppKeys.studentClassSearchLoading: 'Searching for matching classes...',
    AppKeys.studentClassSearchRetry:
        'The search could not be completed. Check your connection and try again.',
    AppKeys.studentClassFilterLoadFailed:
        'Filters could not be loaded. You can still search by code or class name.',
    AppKeys.studentClassMissingCode: 'This classroom has no join code yet.',
    AppKeys.studentJoinClassFailed: 'Could not send class join request.',
    AppKeys.studentClassJoinRequestPending:
        'This classroom already has a pending invitation or request.',
    AppKeys.studentClassCodeLabel: 'CODE: {code}',
    AppKeys.studentClassRelationshipMember: 'JOINED',
    AppKeys.studentClassRelationshipPendingInvitation: 'INVITED',
    AppKeys.studentClassRelationshipPendingRequest: 'PENDING',
    AppKeys.studentClassRelationshipNone: 'NOT JOINED',
    AppKeys.parentSwitchStudentAction: 'Choose profile',
    AppKeys.studentClassDetailTitle: 'Class',
    AppKeys.studentClassTeacherRole: 'TEACHER',
    AppKeys.studentClassLearningCategories: 'Learning categories',
    AppKeys.studentClassAssignments: 'Homework',
    AppKeys.studentClassAssignmentsCountFormat: '{count} assignments',
    AppKeys.studentClassExams: 'Exams',
    AppKeys.studentClassExamsSubtitle: 'New challenge',
    AppKeys.studentClassMaterials: 'Materials',
    AppKeys.studentClassMaterialsSubtitle: '12 folders',
    AppKeys.studentClassGrades: 'Grades',
    AppKeys.studentClassGradesSubtitle: 'Average score: 8.5',
    AppKeys.studentClassUpcomingDeadlines: 'Upcoming deadlines',
    AppKeys.studentClassAll: 'All',
    AppKeys.studentClassComingSoon: 'This feature is coming soon.',
  },
};
