import '../../app_keys.dart';

const teacherClassroomStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.teacherClassOpenFailed: 'KhÃ´ng má»Ÿ Ä‘Æ°á»£c lá»›p há»c nÃ y.',
    AppKeys.teacherClassFallback: 'Lá»›p há»c',
    AppKeys.teacherStudentCount: '{count} Há»c sinh',
    AppKeys.teacherCreateClassTitle: 'Táº¡o Lá»›p',
    AppKeys.teacherClassMissingInfo:
        'Vui lÃ²ng nháº­p Ä‘á»§ thÃ´ng tin lá»›p há»c.',
    AppKeys.teacherClassImageLabel: 'áº¢nh Ä‘áº¡i diá»‡n lá»›p há»c',
    AppKeys.teacherGradeLevel: 'Khá»‘i lá»›p',
    AppKeys.teacherClassName: 'TÃªn lá»›p há»c',
    AppKeys.teacherClassNameHint: 'VÃ­ dá»¥: 1A2, 2A3,...',
    AppKeys.teacherClassDescription:
        'MÃ´ táº£ lá»›p há»c (khÃ´ng báº¯t buá»™c)',
    AppKeys.teacherClassDescriptionHint:
        'Giá»›i thiá»‡u má»¥c tiÃªu cá»§a lá»›p...',
    AppKeys.teacherCreating: 'Äang táº¡o...',
    AppKeys.teacherCreate: 'Táº¡o',
    AppKeys.teacherNoOptions: 'ChÆ°a cÃ³ lá»±a chá»n',
    AppKeys.teacherClassDetailTitle: 'Lá»›p Há»c',
    AppKeys.teacherProgramFallback: 'ChÆ°Æ¡ng trÃ¬nh',
    AppKeys.teacherDescriptionFallback: 'ThÃ´ng tin lá»›p',
    AppKeys.teacherClassInfoFallback: 'Lá»›p há»c',
    AppKeys.teacherClassHideLess: 'áº©n bá»›t',
    AppKeys.teacherCopiedClassLink: 'ÄÃ£ sao chÃ©p liÃªn káº¿t lá»›p há»c.',
    AppKeys.teacherCopiedClassCode: 'ÄÃ£ sao chÃ©p mÃ£ lá»›p.',
    AppKeys.teacherMemberManagement: 'Quáº£n lÃ½ thÃ nh viÃªn',
    AppKeys.teacherMemberSummary:
        '{members} thÃ nh viÃªn\n{requests} yÃªu cáº§u má»›i',
    AppKeys.teacherMemberSummaryNoRequests: '{members} thÃ nh viÃªn',
    AppKeys.teacherMembersTitle: 'ThÃ nh ViÃªn',
    AppKeys.teacherSearchClassroomHint: 'TÃ¬m kiáº¿m ...',
    AppKeys.teacherEmptyClassroomList: 'ChÆ°a cÃ³ lá»›p há»c nÃ o.',
    AppKeys.teacherJoinRequests: 'YÃªu cáº§u tham gia ({count})',
    AppKeys.teacherNoJoinRequests: 'ChÆ°a cÃ³ yÃªu cáº§u tham gia.',
    AppKeys.teacherPendingApproval: 'Äang Ä‘á»£i phÃª duyá»‡t',
    AppKeys.teacherJoinedStudentsTitle: 'Há»c sinh Ä‘Ã£ tham gia ({count})',
    AppKeys.teacherSearchStudentTitle: 'ThÃªm há»c sinh',
    AppKeys.teacherSearchStudentHint: 'Nháº­p tÃªn hoáº·c mÃ£ há»c sinh',
    AppKeys.teacherNoStudentResults:
        'KhÃ´ng tÃ¬m tháº¥y há»c sinh phÃ¹ há»£p.',
    AppKeys.teacherSearchStudentFailed: 'TÃ¬m kiáº¿m há»c sinh tháº¥t báº¡i.',
    AppKeys.teacherSelectedStudents: 'ÄÃ£ chá»n {count} há»c sinh',
    AppKeys.teacherSendInviteRequest: 'Gá»­i lá»i má»i',
    AppKeys.teacherInviteRequestQueued:
        'ÄÃ£ gá»­i lá»i má»i cho {count} há»c sinh.',
    AppKeys.teacherClassFunctions: 'Chá»©c NÄƒng Lá»›p Há»c',
    AppKeys.teacherJoinedStudents: 'Há»c sinh Ä‘Ã£ tham gia ({count})',
    AppKeys.teacherNoJoinedStudents: 'ChÆ°a cÃ³ há»c sinh tham gia.',
    AppKeys.teacherStudentFallback: 'Há»c sinh',
  },
  'en': {
    AppKeys.teacherClassOpenFailed: 'Could not open this class.',
    AppKeys.teacherClassFallback: 'Class',
    AppKeys.teacherStudentCount: '{count} students',
    AppKeys.teacherCreateClassTitle: 'Create Class',
    AppKeys.teacherClassMissingInfo: 'Please enter all class information.',
    AppKeys.teacherClassImageLabel: 'Class image',
    AppKeys.teacherGradeLevel: 'Grade level',
    AppKeys.teacherClassName: 'Class name',
    AppKeys.teacherClassNameHint: 'Example: 1A2, 2A3,...',
    AppKeys.teacherClassDescription: 'Class description (optional)',
    AppKeys.teacherClassDescriptionHint: 'Introduce the class goals...',
    AppKeys.teacherCreating: 'Creating...',
    AppKeys.teacherCreate: 'Create',
    AppKeys.teacherNoOptions: 'No options available',
    AppKeys.teacherClassDetailTitle: 'Class',
    AppKeys.teacherProgramFallback: 'Program',
    AppKeys.teacherDescriptionFallback: 'Class information',
    AppKeys.teacherClassInfoFallback: 'Class',
    AppKeys.teacherClassHideLess: 'Hide details',
    AppKeys.teacherCopiedClassLink: 'Class link copied.',
    AppKeys.teacherCopiedClassCode: 'Class code copied.',
    AppKeys.teacherMemberManagement: 'Manage members',
    AppKeys.teacherMemberSummary: '{members} members\n{requests} new requests',
    AppKeys.teacherMemberSummaryNoRequests: '{members} members',
    AppKeys.teacherMembersTitle: 'Members',
    AppKeys.teacherSearchClassroomHint: 'Search ...',
    AppKeys.teacherEmptyClassroomList: 'No classrooms yet.',
    AppKeys.teacherJoinRequests: 'Join Requests ({count})',
    AppKeys.teacherNoJoinRequests: 'No join requests yet.',
    AppKeys.teacherPendingApproval: 'Pending approval',
    AppKeys.teacherJoinedStudentsTitle: 'Joined students ({count})',
    AppKeys.teacherSearchStudentTitle: 'Add students',
    AppKeys.teacherSearchStudentHint: 'Enter student name or ID',
    AppKeys.teacherNoStudentResults: 'No matching students found.',
    AppKeys.teacherSearchStudentFailed: 'Student search failed.',
    AppKeys.teacherSelectedStudents: '{count} students selected',
    AppKeys.teacherSendInviteRequest: 'Send invite',
    AppKeys.teacherInviteRequestQueued: 'Invite sent to {count} students.',
    AppKeys.teacherClassFunctions: 'Class Functions',
    AppKeys.teacherJoinedStudents: 'Joined students ({count})',
    AppKeys.teacherNoJoinedStudents: 'No students have joined yet.',
    AppKeys.teacherStudentFallback: 'Student',
  },
};
