import '../../app_keys.dart';

const teacherClassroomStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.teacherClassOpenFailed: 'Không mở được lớp học này.',
    AppKeys.teacherClassFallback: 'Lớp học',
    AppKeys.teacherStudentCount: '{count} Học sinh',
    AppKeys.teacherCreateClassTitle: 'Tạo Lớp',
    AppKeys.teacherClassMissingInfo: 'Vui lòng nhập đủ thông tin lớp học.',
    AppKeys.teacherClassImageLabel: 'Ảnh đại diện lớp học',
    AppKeys.teacherGradeLevel: 'Khối lớp',
    AppKeys.teacherClassName: 'Tên lớp học',
    AppKeys.teacherClassNameHint: 'Ví dụ: 1A2, 2A3,...',
    AppKeys.teacherClassDescription: 'Mô tả lớp học (không bắt buộc)',
    AppKeys.teacherClassDescriptionHint: 'Giới thiệu mục tiêu của lớp...',
    AppKeys.teacherCreating: 'Đang tạo...',
    AppKeys.teacherCreate: 'Tạo',
    AppKeys.teacherNoOptions: 'Chưa có lựa chọn',
    AppKeys.teacherClassDetailTitle: 'Lớp Học',
    AppKeys.teacherProgramFallback: 'Chương trình',
    AppKeys.teacherDescriptionFallback: 'Thông tin lớp',
    AppKeys.teacherClassInfoFallback: 'Lớp học',
    AppKeys.teacherClassHideLess: 'ẩn bớt',
    AppKeys.teacherCopiedClassLink: 'Đã sao chép liên kết lớp học.',
    AppKeys.teacherCopiedClassCode: 'Đã sao chép mã lớp.',
    AppKeys.teacherMemberManagement: 'Quản lý thành viên',
    AppKeys.teacherMemberSummary:
        '{members} thành viên\n{requests} yêu cầu mới',
    AppKeys.teacherMemberSummaryNoRequests: '{members} thành viên',
    AppKeys.teacherMembersTitle: 'Thành Viên',
    AppKeys.teacherSearchClassroomHint: 'Tìm kiếm ...',
    AppKeys.teacherEmptyClassroomList: 'Chưa có lớp học nào.',
    AppKeys.teacherJoinRequests: 'Yêu cầu tham gia ({count})',
    AppKeys.teacherNoJoinRequests: 'Chưa có yêu cầu tham gia.',
    AppKeys.teacherPendingApproval: 'Đang đợi phê duyệt',
    AppKeys.teacherJoinedStudentsTitle: 'Học sinh đã tham gia ({count})',
    AppKeys.teacherSearchStudentTitle: 'Thêm học sinh',
    AppKeys.teacherSearchStudentHint: 'Nhập tên hoặc mã học sinh',
    AppKeys.teacherNoStudentResults: 'Không tìm thấy học sinh phù hợp.',
    AppKeys.teacherSearchStudentFailed: 'Tìm kiếm học sinh thất bại.',
    AppKeys.teacherSelectedStudents: 'Đã chọn {count} học sinh',
    AppKeys.teacherSendInviteRequest: 'Gửi lời mời',
    AppKeys.teacherInviteRequestQueued: 'Đã gửi lời mời cho {count} học sinh.',
    AppKeys.teacherClassFunctions: 'Chức Năng Lớp Học',
    AppKeys.teacherJoinedStudents: 'Học sinh đã tham gia ({count})',
    AppKeys.teacherNoJoinedStudents: 'Chưa có học sinh tham gia.',
    AppKeys.teacherStudentFallback: 'Học sinh',
  },
  'en': {
    AppKeys.teacherClassOpenFailed: 'Could not open this class.',
    AppKeys.teacherClassFallback: 'Class',
    AppKeys.teacherStudentCount: '{count} students',
    AppKeys.teacherCreateClassTitle: 'Create Class',
    AppKeys.teacherClassMissingInfo: 'Please enter all class information.',
    AppKeys.teacherClassImageLabel: 'Class image',
    AppKeys.teacherGradeLevel: 'Grade level',
    AppKeys.teacherClassName: 'Class name',
    AppKeys.teacherClassNameHint: 'Example: 1A2, 2A3,...',
    AppKeys.teacherClassDescription: 'Class description (optional)',
    AppKeys.teacherClassDescriptionHint: 'Introduce the class goals...',
    AppKeys.teacherCreating: 'Creating...',
    AppKeys.teacherCreate: 'Create',
    AppKeys.teacherNoOptions: 'No options available',
    AppKeys.teacherClassDetailTitle: 'Class',
    AppKeys.teacherProgramFallback: 'Program',
    AppKeys.teacherDescriptionFallback: 'Class information',
    AppKeys.teacherClassInfoFallback: 'Class',
    AppKeys.teacherClassHideLess: 'Hide details',
    AppKeys.teacherCopiedClassLink: 'Class link copied.',
    AppKeys.teacherCopiedClassCode: 'Class code copied.',
    AppKeys.teacherMemberManagement: 'Manage members',
    AppKeys.teacherMemberSummary: '{members} members\n{requests} new requests',
    AppKeys.teacherMemberSummaryNoRequests: '{members} members',
    AppKeys.teacherMembersTitle: 'Members',
    AppKeys.teacherSearchClassroomHint: 'Search ...',
    AppKeys.teacherEmptyClassroomList: 'No classrooms yet.',
    AppKeys.teacherJoinRequests: 'Join Requests ({count})',
    AppKeys.teacherNoJoinRequests: 'No join requests yet.',
    AppKeys.teacherPendingApproval: 'Pending approval',
    AppKeys.teacherJoinedStudentsTitle: 'Joined students ({count})',
    AppKeys.teacherSearchStudentTitle: 'Add students',
    AppKeys.teacherSearchStudentHint: 'Enter student name or ID',
    AppKeys.teacherNoStudentResults: 'No matching students found.',
    AppKeys.teacherSearchStudentFailed: 'Student search failed.',
    AppKeys.teacherSelectedStudents: '{count} students selected',
    AppKeys.teacherSendInviteRequest: 'Send invite',
    AppKeys.teacherInviteRequestQueued: 'Invite sent to {count} students.',
    AppKeys.teacherClassFunctions: 'Class Functions',
    AppKeys.teacherJoinedStudents: 'Joined students ({count})',
    AppKeys.teacherNoJoinedStudents: 'No students have joined yet.',
    AppKeys.teacherStudentFallback: 'Student',
  },
};
