import '../app_keys.dart';

const authStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.phoneLoginTitle: 'Sá»‘ Ä‘iá»‡n thoáº¡i',
    AppKeys.phoneLoginBrandName: 'NUMINUMI',
    AppKeys.phoneLoginSubtitle:
        'Nháº­p sá»‘ Ä‘iá»‡n thoáº¡i Ä‘á»ƒ\nÄ‘Äƒng kÃ½ hoáº·c Ä‘Äƒng nháº­p !',
    AppKeys.phoneNumberUpper: 'Sá» ÄIá»†N THOáº I',
    AppKeys.phoneHint: 'Nháº­p sá»‘ Ä‘iá»‡n thoáº¡i',
    AppKeys.chooseCountry: 'Chá»n quá»‘c gia',
    AppKeys.creatingAccount: 'Äang táº¡o tÃ i khoáº£n...',
    AppKeys.checking: 'Äang kiá»ƒm tra...',
    AppKeys.phoneRequired: 'Vui lÃ²ng nháº­p sá»‘ Ä‘iá»‡n thoáº¡i.',
    AppKeys.invalidPhone: 'Sá»‘ Ä‘iá»‡n thoáº¡i chÆ°a há»£p lá»‡.',
    AppKeys.phoneTooShort: 'Sá»‘ Ä‘iá»‡n thoáº¡i chÆ°a Ä‘á»§ kÃ½ tá»±.',
    AppKeys.restoringSession: 'Äang kiá»ƒm tra phiÃªn Ä‘Äƒng nháº­p...',
    AppKeys.newAccountPrompt:
        'ÄÃ¢y lÃ  tÃ i khoáº£n Má»šI. Tiáº¿p tá»¥c Ä‘Äƒng kÃ½?',
    AppKeys.signup: 'ÄÄƒng kÃ½',
    AppKeys.login: 'ÄÄƒng nháº­p',
    AppKeys.loginWithPin: 'ÄÄƒng nháº­p vá»›i PIN',
    AppKeys.otpWithin30Seconds:
        'Báº¡n sáº½ nháº­n Ä‘Æ°á»£c mÃ£ trong vÃ²ng 30 giÃ¢y',
    AppKeys.otpTitle: 'MÃƒ XÃC NHáº¬N',
    AppKeys.otpSentMessage: 'MÃ£ OTP vá»«a gá»­i: {code}',
    AppKeys.otpConfirming: 'Äang xÃ¡c thá»±c...',
    AppKeys.otpConfirm: 'XÃ¡c nháº­n',
    AppKeys.resendOtp: 'Gá»­i láº¡i mÃ£',
    AppKeys.resendOtpAfter: 'Gá»­i láº¡i mÃ£ sau {seconds} giÃ¢y',
    AppKeys.signupNameHint: 'vd: quoc, quyen',
    AppKeys.signupEmailHint: 'example@numinumi.com',
    AppKeys.signupNameLabel: 'TÃªn',
    AppKeys.signupNameInvalid:
        'TÃªn chá»‰ Ä‘Æ°á»£c gá»“m chá»¯, sá»‘ vÃ  khoáº£ng tráº¯ng.',
    AppKeys.signupEmailLabel: 'Email',
    AppKeys.signupRoleLabel: 'Báº¡n lÃ ',
    AppKeys.signupRoleStudent: 'Há»c Sinh',
    AppKeys.signupRoleParent: 'Phá»¥ huynh',
    AppKeys.signupRoleTeacher: 'GiÃ¡o viÃªn',
    AppKeys.signupGenderLabel: 'Giá»›i tÃ­nh',
    AppKeys.signupGenderHint: 'Chá»n',
    AppKeys.signupGenderSelectRoleHint: 'Chá»n vai trÃ² trÆ°á»›c',
    AppKeys.signupGenderStudentMale: 'Nam',
    AppKeys.signupGenderStudentFemale: 'Ná»¯',
    AppKeys.signupGenderParentFather: 'Bá»‘',
    AppKeys.signupGenderParentMother: 'Máº¹',
    AppKeys.signupGenderTeacherMale: 'Tháº§y',
    AppKeys.signupGenderTeacherFemale: 'CÃ´',
    AppKeys.signupNameLabelFather: 'TÃªn Bá»‘',
    AppKeys.signupNameLabelMother: 'TÃªn Máº¹',
    AppKeys.signupNameLabelTeacherMale: 'TÃªn Tháº§y',
    AppKeys.signupNameLabelTeacherFemale: 'TÃªn CÃ´',
    AppKeys.signupEmailDescription:
        'Nháº­p email Ä‘á»ƒ theo dÃµi káº¿t quáº£ kiá»ƒm tra vÃ  hÃ nh\ntrÃ¬nh há»c táº­p cá»§a bÃ©',
    AppKeys.phoneNumber: 'Sá»‘ Äiá»‡n Thoáº¡i',
    AppKeys.authPhoneCheckFailed:
        'KhÃ´ng thá»ƒ kiá»ƒm tra sá»‘ Ä‘iá»‡n thoáº¡i.',
    AppKeys.signupOtpFailed:
        'KhÃ´ng thá»ƒ gá»­i OTP Ä‘Äƒng kÃ½. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.loginOtpFailed: 'KhÃ´ng thá»ƒ gá»­i OTP. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.invalidOtp: 'MÃ£ OTP khÃ´ng Ä‘Ãºng. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.missingOtpUser: 'Response OTP thiáº¿u thÃ´ng tin user.',
    AppKeys.verifyOtpFailed:
        'KhÃ´ng thá»ƒ xÃ¡c thá»±c OTP. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.childNameRequired: 'Vui lÃ²ng nháº­p tÃªn cá»§a bÃ©.',
    AppKeys.signupFailed: 'KhÃ´ng thá»ƒ Ä‘Äƒng kÃ½. Vui lÃ²ng thá»­ láº¡i.',
  },
  'en': {
    AppKeys.phoneLoginTitle: 'Phone number',
    AppKeys.phoneLoginBrandName: 'NUMINUMI',
    AppKeys.phoneLoginSubtitle:
        'Enter your phone number to\nsign up or log in!',
    AppKeys.phoneNumberUpper: 'PHONE NUMBER',
    AppKeys.phoneHint: 'Enter phone number',
    AppKeys.chooseCountry: 'Choose country',
    AppKeys.creatingAccount: 'Creating account...',
    AppKeys.checking: 'Checking...',
    AppKeys.phoneRequired: 'Please enter a phone number.',
    AppKeys.invalidPhone: 'The phone number is invalid.',
    AppKeys.phoneTooShort: 'The phone number is too short.',
    AppKeys.restoringSession: 'Checking login session...',
    AppKeys.newAccountPrompt: 'This is a NEW account. Continue to sign up?',
    AppKeys.signup: 'Sign up',
    AppKeys.login: 'Log in',
    AppKeys.loginWithPin: 'Log in with PIN',
    AppKeys.otpWithin30Seconds: 'You will receive a code within 30 seconds',
    AppKeys.otpTitle: 'VERIFICATION CODE',
    AppKeys.otpSentMessage: 'OTP code sent: {code}',
    AppKeys.otpConfirming: 'Verifying...',
    AppKeys.otpConfirm: 'Confirm',
    AppKeys.resendOtp: 'Resend code',
    AppKeys.resendOtpAfter: 'Resend code in {seconds}s',
    AppKeys.signupNameHint: 'ex: quoc, quyen',
    AppKeys.signupEmailHint: 'example@numinumi.com',
    AppKeys.signupNameLabel: 'First Name',
    AppKeys.signupNameInvalid:
        'First name can only include letters, numbers, and spaces.',
    AppKeys.signupEmailLabel: 'Email',
    AppKeys.signupRoleLabel: 'You are',
    AppKeys.signupRoleStudent: 'Student',
    AppKeys.signupRoleParent: 'Parent',
    AppKeys.signupRoleTeacher: 'Teacher',
    AppKeys.signupGenderLabel: 'Gender',
    AppKeys.signupGenderHint: 'Select',
    AppKeys.signupGenderSelectRoleHint: 'Select role first',
    AppKeys.signupGenderStudentMale: 'Male',
    AppKeys.signupGenderStudentFemale: 'Female',
    AppKeys.signupGenderParentFather: 'Father',
    AppKeys.signupGenderParentMother: 'Mother',
    AppKeys.signupGenderTeacherMale: 'Male teacher',
    AppKeys.signupGenderTeacherFemale: 'Female teacher',
    AppKeys.signupNameLabelFather: "Father's First Name",
    AppKeys.signupNameLabelMother: "Mother's First Name",
    AppKeys.signupNameLabelTeacherMale: "Teacher's First Name",
    AppKeys.signupNameLabelTeacherFemale: "Teacher's First Name",
    AppKeys.signupEmailDescription:
        "Enter an email to follow your child's assessment results\nand learning journey",
    AppKeys.phoneNumber: 'Phone Number',
    AppKeys.authPhoneCheckFailed: 'Could not check this phone number.',
    AppKeys.signupOtpFailed: 'Could not send signup OTP. Please try again.',
    AppKeys.loginOtpFailed: 'Could not send OTP. Please try again.',
    AppKeys.invalidOtp: 'The OTP is incorrect. Please try again.',
    AppKeys.missingOtpUser: 'OTP response is missing user information.',
    AppKeys.verifyOtpFailed: 'Could not verify OTP. Please try again.',
    AppKeys.childNameRequired: "Please enter your child's name.",
    AppKeys.signupFailed: 'Could not sign up. Please try again.',
  },
};
