import '../app_keys.dart';

const authStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.signingUp: 'Đang đăng ký...',
    AppKeys.phoneHint: 'Nhập số điện thoại',
    AppKeys.loginNameHint: 'Số điện thoại hoặc email',
    AppKeys.chooseCountry: 'Chọn quốc gia',
    AppKeys.phoneRequired: 'Vui lòng nhập số điện thoại.',
    AppKeys.invalidPhone: 'Số điện thoại chưa hợp lệ.',
    AppKeys.invalidEmail: 'Email chưa hợp lệ.',
    AppKeys.phoneTooShort: 'Số điện thoại chưa đủ ký tự.',
    AppKeys.restoringSession: 'Đang kiểm tra phiên đăng nhập...',
    AppKeys.signup: 'Đăng ký',
    AppKeys.login: 'Đăng nhập',
    AppKeys.loginWithPin: 'Đăng nhập bằng PIN',
    AppKeys.authSwitchToSignupPrompt: 'Chưa có tài khoản?',
    AppKeys.authSwitchToLoginPrompt: 'Đã có tài khoản?',
    AppKeys.trustedDeviceTitle: 'Xác minh thiết bị mới',
    AppKeys.trustedDeviceSubtitle:
        'Chọn một thiết bị tin cậy để phê duyệt lần đăng nhập này.',
    AppKeys.trustedDeviceSend: 'Gửi mã',
    AppKeys.trustedDeviceSending: 'Đang gửi...',
    AppKeys.trustedDeviceEmpty:
        'Không tìm thấy thiết bị đã xác minh cho tài khoản này.',
    AppKeys.trustedDeviceLoadFailed:
        'Không thể tải danh sách thiết bị. Vui lòng thử lại.',
    AppKeys.otpConfirming: 'Đang xác thực...',
    AppKeys.otpConfirm: 'Xác nhận',
    AppKeys.resendOtp: 'Gửi lại mã',
    AppKeys.resendOtpAfter: 'Gửi lại mã sau {seconds} giây',
    AppKeys.signupNameHint: 'vd: quoc, quyen',
    AppKeys.signupNameLabel: 'Tên',
    AppKeys.signupNameInvalid: 'Tên chỉ được gồm chữ, số và khoảng trắng.',
    AppKeys.signupUsernameExists: 'Tên này đã tồn tại. Vui lòng chọn tên khác.',
    AppKeys.signupRoleLabel: 'Bạn là',
    AppKeys.signupRoleStudent: 'Học Sinh',
    AppKeys.signupRoleParent: 'Phụ huynh',
    AppKeys.signupRoleTeacher: 'Giáo viên',
    AppKeys.signupGenderLabel: 'Giới tính',
    AppKeys.signupGenderHint: 'Chọn',
    AppKeys.signupGenderSelectRoleHint: 'Chọn vai trò trước',
    AppKeys.signupGenderStudentMale: 'Nam',
    AppKeys.signupGenderStudentFemale: 'Nữ',
    AppKeys.signupGenderParentFather: 'Bố',
    AppKeys.signupGenderParentMother: 'Mẹ',
    AppKeys.signupGenderTeacherMale: 'Thầy',
    AppKeys.signupGenderTeacherFemale: 'Cô',
    AppKeys.signupNameLabelFather: 'Tên Bố',
    AppKeys.signupNameLabelMother: 'Tên Mẹ',
    AppKeys.signupNameLabelTeacherMale: 'Tên Thầy',
    AppKeys.signupNameLabelTeacherFemale: 'Tên Cô',
    AppKeys.signupTermsPrivacyPrefix: 'Tôi đồng ý với Điều khoản sử dụng và',
    AppKeys.signupPrivacyPolicyLabel: 'Chính sách bảo mật',
    AppKeys.signupPrivacyPolicyOpenFailed: 'Không thể mở Chính sách bảo mật.',
    AppKeys.signupInformationAccuracy:
        'Tôi xác nhận thông tin đăng ký là chính xác.',
    AppKeys.phoneNumber: 'Số Điện Thoại',
    AppKeys.authPhoneCheckFailed: 'Không thể kiểm tra số điện thoại.',
    AppKeys.authLoginNameCheckFailed: 'Không thể kiểm tra tài khoản.',
    AppKeys.loginNameNotRegistered:
        'Số điện thoại hoặc email này chưa có tài khoản. Vui lòng đăng ký.',
    AppKeys.signupPhoneAlreadyRegistered:
        'Số điện thoại này đã có tài khoản. Vui lòng đăng nhập.',
    AppKeys.signupEmailAlreadyRegistered:
        'Email này đã có tài khoản. Vui lòng đăng nhập.',
    AppKeys.signupOtpFailed: 'Không thể gửi OTP đăng ký. Vui lòng thử lại.',
    AppKeys.signupOtpUnavailable:
        'Xác thực OTP hiện không khả dụng cho email hoặc số điện thoại này.',
    AppKeys.loginOtpFailed: 'Không thể gửi OTP. Vui lòng thử lại.',
    AppKeys.pinLoginFailed:
        'Không thể đăng nhập bằng PIN. Vui lòng đăng nhập lại.',
    AppKeys.invalidOtp: 'Mã OTP không đúng. Vui lòng thử lại.',
    AppKeys.missingOtpUser: 'Response OTP thiếu thông tin user.',
    AppKeys.verifyOtpFailed: 'Không thể xác thực OTP. Vui lòng thử lại.',
    AppKeys.childNameRequired: 'Vui lòng nhập tên của bé.',
    AppKeys.signupFailed: 'Không thể đăng ký. Vui lòng thử lại.',
  },
  'en': {
    AppKeys.signingUp: 'Signing up...',
    AppKeys.phoneHint: 'Enter phone number',
    AppKeys.loginNameHint: 'Phone number or email',
    AppKeys.chooseCountry: 'Choose country',
    AppKeys.phoneRequired: 'Please enter a phone number.',
    AppKeys.invalidPhone: 'The phone number is invalid.',
    AppKeys.invalidEmail: 'The email address is invalid.',
    AppKeys.phoneTooShort: 'The phone number is too short.',
    AppKeys.restoringSession: 'Checking login session...',
    AppKeys.signup: 'Sign up',
    AppKeys.login: 'Login',
    AppKeys.loginWithPin: 'Login with PIN',
    AppKeys.authSwitchToSignupPrompt: "Don't have an account?",
    AppKeys.authSwitchToLoginPrompt: 'Already have an account?',
    AppKeys.trustedDeviceTitle: 'Verify your new device',
    AppKeys.trustedDeviceSubtitle:
        'Choose a trusted device to approve this login.',
    AppKeys.trustedDeviceSend: 'Send code',
    AppKeys.trustedDeviceSending: 'Sending...',
    AppKeys.trustedDeviceEmpty:
        'No verified devices were found for this account.',
    AppKeys.trustedDeviceLoadFailed:
        'Could not load trusted devices. Please try again.',
    AppKeys.otpConfirming: 'Verifying...',
    AppKeys.otpConfirm: 'Confirm',
    AppKeys.resendOtp: 'Resend code',
    AppKeys.resendOtpAfter: 'Resend code in {seconds}s',
    AppKeys.signupNameHint: 'ex: quoc, quyen',
    AppKeys.signupNameLabel: 'First Name',
    AppKeys.signupNameInvalid:
        'First name can only include letters, numbers, and spaces.',
    AppKeys.signupUsernameExists:
        'This name already exists. Please choose another name.',
    AppKeys.signupRoleLabel: 'You are',
    AppKeys.signupRoleStudent: 'Student',
    AppKeys.signupRoleParent: 'Parent',
    AppKeys.signupRoleTeacher: 'Teacher',
    AppKeys.signupGenderLabel: 'Gender',
    AppKeys.signupGenderHint: 'Select',
    AppKeys.signupGenderSelectRoleHint: 'Select role first',
    AppKeys.signupGenderStudentMale: 'Male',
    AppKeys.signupGenderStudentFemale: 'Female',
    AppKeys.signupGenderParentFather: 'Father',
    AppKeys.signupGenderParentMother: 'Mother',
    AppKeys.signupGenderTeacherMale: 'Male teacher',
    AppKeys.signupGenderTeacherFemale: 'Female teacher',
    AppKeys.signupNameLabelFather: "Father's First Name",
    AppKeys.signupNameLabelMother: "Mother's First Name",
    AppKeys.signupNameLabelTeacherMale: "Teacher's First Name",
    AppKeys.signupNameLabelTeacherFemale: "Teacher's First Name",
    AppKeys.signupTermsPrivacyPrefix: 'I agree to the Terms of Use and',
    AppKeys.signupPrivacyPolicyLabel: 'Privacy Policy',
    AppKeys.signupPrivacyPolicyOpenFailed: 'Could not open the Privacy Policy.',
    AppKeys.signupInformationAccuracy:
        'I confirm that my registration information is accurate.',
    AppKeys.phoneNumber: 'Phone Number',
    AppKeys.authPhoneCheckFailed: 'Could not check this phone number.',
    AppKeys.authLoginNameCheckFailed: 'Could not check this account.',
    AppKeys.loginNameNotRegistered:
        'This phone number or email does not have an account. Please sign up.',
    AppKeys.signupPhoneAlreadyRegistered:
        'This phone number already has an account.',
    AppKeys.signupEmailAlreadyRegistered: 'This email already has an account.',
    AppKeys.signupOtpFailed: 'Could not send signup OTP. Please try again.',
    AppKeys.signupOtpUnavailable:
        'OTP verification is unavailable for this email or phone number.',
    AppKeys.loginOtpFailed: 'Could not send OTP. Please try again.',
    AppKeys.pinLoginFailed: 'Could not log in with PIN. Please log in again.',
    AppKeys.invalidOtp: 'The OTP is incorrect. Please try again.',
    AppKeys.missingOtpUser: 'OTP response is missing user information.',
    AppKeys.verifyOtpFailed: 'Could not verify OTP. Please try again.',
    AppKeys.childNameRequired: "Please enter your child's name.",
    AppKeys.signupFailed: 'Could not sign up. Please try again.',
  },
};
