import '../app_keys.dart';

const authStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.phoneLoginTitle: 'Số điện thoại',
    AppKeys.phoneLoginBrandName: 'NUMINUMI',
    AppKeys.phoneLoginSubtitle:
        'Nhập số điện thoại để\nđăng ký hoặc đăng nhập !',
    AppKeys.phoneNumberUpper: 'SỐ ĐIỆN THOẠI',
    AppKeys.phoneHint: 'Nhập số điện thoại',
    AppKeys.chooseCountry: 'Chọn quốc gia',
    AppKeys.creatingAccount: 'Đang tạo tài khoản...',
    AppKeys.checking: 'Đang kiểm tra...',
    AppKeys.phoneRequired: 'Vui lòng nhập số điện thoại.',
    AppKeys.invalidPhone: 'Số điện thoại chưa hợp lệ.',
    AppKeys.phoneTooShort: 'Số điện thoại chưa đủ ký tự.',
    AppKeys.restoringSession: 'Đang kiểm tra phiên đăng nhập...',
    AppKeys.newAccountPrompt: 'Đây là tài khoản MỚI. Tiếp tục đăng ký?',
    AppKeys.signup: 'Đăng ký',
    AppKeys.login: 'Đăng nhập',
    AppKeys.loginWithPin: 'Đăng nhập với PIN',
    AppKeys.authSwitchToSignupPrompt: 'Chưa có tài khoản?',
    AppKeys.authSwitchToLoginPrompt: 'Đã có tài khoản?',
    AppKeys.otpWithin30Seconds: 'Bạn sẽ nhận được mã trong vòng 30 giây',
    AppKeys.otpTitle: 'MÃ XÁC NHẬN',
    AppKeys.otpSentMessage: 'Mã OTP vừa gửi: {code}',
    AppKeys.otpConfirming: 'Đang xác thực...',
    AppKeys.otpConfirm: 'Xác nhận',
    AppKeys.resendOtp: 'Gửi lại mã',
    AppKeys.resendOtpAfter: 'Gửi lại mã sau {seconds} giây',
    AppKeys.signupNameHint: 'vd: quoc, quyen',
    AppKeys.signupEmailHint: 'example@numinumi.com',
    AppKeys.signupNameLabel: 'Tên',
    AppKeys.signupNameInvalid: 'Tên chỉ được gồm chữ, số và khoảng trắng.',
    AppKeys.signupUsernameExists: 'Tên này đã tồn tại. Vui lòng chọn tên khác.',
    AppKeys.signupEmailLabel: 'Email',
    AppKeys.signupRoleLabel: 'Bạn là',
    AppKeys.signupRoleStudent: 'Học Sinh',
    AppKeys.signupRoleParent: 'Phụ huynh',
    AppKeys.signupRoleTeacher: 'Giáo viên',
    AppKeys.signupGenderLabel: 'Giới tính',
    AppKeys.signupGenderHint: 'Chọn',
    AppKeys.signupGenderSelectRoleHint: 'Chọn vai trò trước',
    AppKeys.signupGenderStudentMale: 'Nam',
    AppKeys.signupGenderStudentFemale: 'Nữ',
    AppKeys.signupGenderParentFather: 'Bố',
    AppKeys.signupGenderParentMother: 'Mẹ',
    AppKeys.signupGenderTeacherMale: 'Thầy',
    AppKeys.signupGenderTeacherFemale: 'Cô',
    AppKeys.signupNameLabelFather: 'Tên Bố',
    AppKeys.signupNameLabelMother: 'Tên Mẹ',
    AppKeys.signupNameLabelTeacherMale: 'Tên Thầy',
    AppKeys.signupNameLabelTeacherFemale: 'Tên Cô',
    AppKeys.signupEmailDescription:
        'Nhập email để theo dõi kết quả kiểm tra và hành\ntrình học tập của bé',
    AppKeys.phoneNumber: 'Số Điện Thoại',
    AppKeys.authPhoneCheckFailed: 'Không thể kiểm tra số điện thoại.',
    AppKeys.loginPhoneNotRegistered:
        'Số điện thoại này chưa có tài khoản. Vui lòng đăng ký.',
    AppKeys.signupPhoneAlreadyRegistered:
        'Số điện thoại này đã có tài khoản. Vui lòng đăng nhập.',
    AppKeys.signupOtpFailed: 'Không thể gửi OTP đăng ký. Vui lòng thử lại.',
    AppKeys.loginOtpFailed: 'Không thể gửi OTP. Vui lòng thử lại.',
    AppKeys.pinLoginFailed:
        'Không thể đăng nhập bằng PIN. Vui lòng đăng nhập bằng số điện thoại.',
    AppKeys.invalidOtp: 'Mã OTP không đúng. Vui lòng thử lại.',
    AppKeys.missingOtpUser: 'Response OTP thiếu thông tin user.',
    AppKeys.verifyOtpFailed: 'Không thể xác thực OTP. Vui lòng thử lại.',
    AppKeys.childNameRequired: 'Vui lòng nhập tên của bé.',
    AppKeys.signupFailed: 'Không thể đăng ký. Vui lòng thử lại.',
  },
  'en': {
    AppKeys.phoneLoginTitle: 'Phone number',
    AppKeys.phoneLoginBrandName: 'NUMINUMI',
    AppKeys.phoneLoginSubtitle:
        'Enter your phone number to\nsign up or log in!',
    AppKeys.phoneNumberUpper: 'PHONE NUMBER',
    AppKeys.phoneHint: 'Enter phone number',
    AppKeys.chooseCountry: 'Choose country',
    AppKeys.creatingAccount: 'Creating account...',
    AppKeys.checking: 'Checking...',
    AppKeys.phoneRequired: 'Please enter a phone number.',
    AppKeys.invalidPhone: 'The phone number is invalid.',
    AppKeys.phoneTooShort: 'The phone number is too short.',
    AppKeys.restoringSession: 'Checking login session...',
    AppKeys.newAccountPrompt: 'This is a NEW account. Continue to sign up?',
    AppKeys.signup: 'Sign up',
    AppKeys.login: 'Log in',
    AppKeys.loginWithPin: 'Log in with PIN',
    AppKeys.authSwitchToSignupPrompt: "Don't have an account?",
    AppKeys.authSwitchToLoginPrompt: 'Already have an account?',
    AppKeys.otpWithin30Seconds: 'You will receive a code within 30 seconds',
    AppKeys.otpTitle: 'VERIFICATION CODE',
    AppKeys.otpSentMessage: 'OTP code sent: {code}',
    AppKeys.otpConfirming: 'Verifying...',
    AppKeys.otpConfirm: 'Confirm',
    AppKeys.resendOtp: 'Resend code',
    AppKeys.resendOtpAfter: 'Resend code in {seconds}s',
    AppKeys.signupNameHint: 'ex: quoc, quyen',
    AppKeys.signupEmailHint: 'example@numinumi.com',
    AppKeys.signupNameLabel: 'First Name',
    AppKeys.signupNameInvalid:
        'First name can only include letters, numbers, and spaces.',
    AppKeys.signupUsernameExists:
        'This name already exists. Please choose another name.',
    AppKeys.signupEmailLabel: 'Email',
    AppKeys.signupRoleLabel: 'You are',
    AppKeys.signupRoleStudent: 'Student',
    AppKeys.signupRoleParent: 'Parent',
    AppKeys.signupRoleTeacher: 'Teacher',
    AppKeys.signupGenderLabel: 'Gender',
    AppKeys.signupGenderHint: 'Select',
    AppKeys.signupGenderSelectRoleHint: 'Select role first',
    AppKeys.signupGenderStudentMale: 'Male',
    AppKeys.signupGenderStudentFemale: 'Female',
    AppKeys.signupGenderParentFather: 'Father',
    AppKeys.signupGenderParentMother: 'Mother',
    AppKeys.signupGenderTeacherMale: 'Male teacher',
    AppKeys.signupGenderTeacherFemale: 'Female teacher',
    AppKeys.signupNameLabelFather: "Father's First Name",
    AppKeys.signupNameLabelMother: "Mother's First Name",
    AppKeys.signupNameLabelTeacherMale: "Teacher's First Name",
    AppKeys.signupNameLabelTeacherFemale: "Teacher's First Name",
    AppKeys.signupEmailDescription:
        "Enter an email to follow your child's assessment results\nand learning journey",
    AppKeys.phoneNumber: 'Phone Number',
    AppKeys.authPhoneCheckFailed: 'Could not check this phone number.',
    AppKeys.loginPhoneNotRegistered:
        'This phone number does not have an account. Please sign up.',
    AppKeys.signupPhoneAlreadyRegistered:
        'This phone number already has an account. Please log in.',
    AppKeys.signupOtpFailed: 'Could not send signup OTP. Please try again.',
    AppKeys.loginOtpFailed: 'Could not send OTP. Please try again.',
    AppKeys.pinLoginFailed:
        'Could not log in with PIN. Please log in with your phone number.',
    AppKeys.invalidOtp: 'The OTP is incorrect. Please try again.',
    AppKeys.missingOtpUser: 'OTP response is missing user information.',
    AppKeys.verifyOtpFailed: 'Could not verify OTP. Please try again.',
    AppKeys.childNameRequired: "Please enter your child's name.",
    AppKeys.signupFailed: 'Could not sign up. Please try again.',
  },
};
