import '../app_keys.dart';

const commonStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.appName: 'NUMI',
    AppKeys.loading: 'Đang tải...',
    AppKeys.close: 'Đóng',
    AppKeys.cancel: 'Hủy',
    AppKeys.save: 'Lưu',
    AppKeys.retry: 'Thử lại',
    AppKeys.retryUpper: 'THỬ LẠI',
    AppKeys.accept: 'Chấp nhận',
    AppKeys.reject: 'Từ chối',
    AppKeys.delete: 'Xóa',
    AppKeys.update: 'Cập nhật',
    AppKeys.add: 'Thêm',
    AppKeys.back: 'Quay lại',
    AppKeys.skipUpper: 'BỎ QUA',
    AppKeys.continueUpper: 'TIẾP TỤC',
    AppKeys.language: 'Ngôn ngữ',
    AppKeys.languageTitle: 'Ngôn Ngữ',
    AppKeys.languageMenuSubtitle: 'Đổi ngôn ngữ hiển thị',
    AppKeys.languageVietnamese: 'Tiếng Việt',
    AppKeys.languageEnglish: 'English',
    AppKeys.welcomeTitlePrefix: 'Học Toán cùng\n',
    AppKeys.welcomeTitleN: 'NUMI',
    AppKeys.welcomeSubtitlePrefix: 'Hãy cùng Numi',
    AppKeys.welcomeSubtitle: 'trở thành "phù thủy" tính toán nhé!',
    AppKeys.start: 'BẮT ĐẦU',
    AppKeys.continueLabel: 'Tiếp tục',
    AppKeys.avatarUpper: 'ẢNH ĐẠI DIỆN',
    AppKeys.chooseAvatar: 'Chọn ảnh đại diện',
    AppKeys.signingUp: 'Đang đăng ký...',
    AppKeys.studentMissingProfileId: 'Hồ sơ học sinh thiếu profile_id.',
    AppKeys.studentRetry: 'Thử lại',
    AppKeys.studentNoClassSearchResults: 'Không tìm thấy lớp học',
    AppKeys.studentNoClassSearchResultsMessage:
        'Kiểm tra lại mã lớp hoặc tên lớp rồi thử lại.',
    AppKeys.studentEnterClassCodeTitle: 'Nhập mã hoặc tên lớp',
    AppKeys.studentEnterClassCodeMessage:
        'Kết quả lớp học phù hợp sẽ hiển thị tại đây.',
    AppKeys.studentAlreadyJoinedClass: 'Bạn đã tham gia lớp học này.',
    AppKeys.studentNoInvitationsTitle: 'Chưa có lời mời',
    AppKeys.studentNoInvitationsMessage:
        'Lời mời lớp học mới sẽ xuất hiện tại đây.',
    AppKeys.noChapterTitle: 'Chưa có chương',
    AppKeys.noChapterMessage: 'Chưa có lộ trình ôn tập cho hồ sơ này.',
    AppKeys.startTest: 'Bắt đầu kiểm tra ({count})',
    AppKeys.time: 'Thời gian',
    AppKeys.generateTestFailed: 'Tạo test thất bại. Vui lòng thử lại sau.',
    AppKeys.noGrades: 'Chưa có lớp học nào để hiển thị.',
    AppKeys.completedResultTitle: 'Hoàn Thành',
  },
  'en': {
    AppKeys.appName: 'NUMI',
    AppKeys.loading: 'Loading...',
    AppKeys.close: 'Close',
    AppKeys.cancel: 'Cancel',
    AppKeys.save: 'Save',
    AppKeys.retry: 'Retry',
    AppKeys.retryUpper: 'RETRY',
    AppKeys.accept: 'Accept',
    AppKeys.reject: 'Reject',
    AppKeys.delete: 'Delete',
    AppKeys.update: 'Update',
    AppKeys.add: 'Add',
    AppKeys.back: 'Back',
    AppKeys.skipUpper: 'SKIP',
    AppKeys.continueUpper: 'CONTINUE',
    AppKeys.language: 'Language',
    AppKeys.languageTitle: 'Language',
    AppKeys.languageMenuSubtitle: 'Change display language',
    AppKeys.languageVietnamese: 'Tiếng Việt',
    AppKeys.languageEnglish: 'English',
    AppKeys.welcomeTitlePrefix: 'Learn math with\n',
    AppKeys.welcomeTitleN: 'NUMI',
    AppKeys.welcomeSubtitlePrefix: 'Join Numi',
    AppKeys.welcomeSubtitle: 'and become a math wizard!',
    AppKeys.start: 'START',
    AppKeys.continueLabel: 'Continue',
    AppKeys.avatarUpper: 'AVATAR',
    AppKeys.chooseAvatar: 'Choose avatar',
    AppKeys.signingUp: 'Signing up...',
    AppKeys.studentMissingProfileId: 'Student profile is missing profile_id.',
    AppKeys.studentRetry: 'Try again',
    AppKeys.studentNoClassSearchResults: 'No classrooms found',
    AppKeys.studentNoClassSearchResultsMessage:
        'Check the class code or class name and try again.',
    AppKeys.studentEnterClassCodeTitle: 'Enter a code or class name',
    AppKeys.studentEnterClassCodeMessage:
        'Matching classroom results will appear here.',
    AppKeys.studentAlreadyJoinedClass: 'You have already joined this class.',
    AppKeys.studentNoInvitationsTitle: 'No invitations yet',
    AppKeys.studentNoInvitationsMessage:
        'New class invitations will appear here.',
    AppKeys.noChapterTitle: 'No chapters',
    AppKeys.noChapterMessage:
        'No review journey is available for this profile.',
    AppKeys.startTest: 'Start test ({count})',
    AppKeys.time: 'Time',
    AppKeys.generateTestFailed: 'Failed to create test. Please try later.',
    AppKeys.noGrades: 'No grades to show.',
    AppKeys.completedResultTitle: 'Completed',
  },
};
