import '../app_keys.dart';

const commonStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.appName: 'NUMI',
    AppKeys.loading: 'Đang tải...',
    AppKeys.close: 'Đóng',
    AppKeys.cancel: 'Hủy',
    AppKeys.save: 'Lưu',
    AppKeys.retry: 'Thử lại',
    AppKeys.retryUpper: 'THỬ LẠI',
    AppKeys.accept: 'Chấp nhận',
    AppKeys.reject: 'Từ chối',
    AppKeys.delete: 'Xóa',
    AppKeys.update: 'Cập nhật',
    AppKeys.add: 'Thêm',
    AppKeys.back: 'Quay lại',
    AppKeys.skipUpper: 'BỎ QUA',
    AppKeys.continueUpper: 'TIẾP TỤC',
    AppKeys.attemptExitTitle: 'Thoát bài đang làm?',
    AppKeys.attemptExitMessage:
        'Các câu trả lời đã chọn sẽ bị mất. Bạn có chắc muốn thoát không?',
    AppKeys.exitUpper: 'THOÁT',
    AppKeys.language: 'Ngôn ngữ',
    AppKeys.languageTitle: 'Ngôn Ngữ',
    AppKeys.languageMenuSubtitle: 'Đổi ngôn ngữ hiển thị',
    AppKeys.languageVietnamese: 'Tiếng Việt',
    AppKeys.languageEnglish: 'English',
    AppKeys.continueLabel: 'Tiếp tục',
    AppKeys.time: 'Thời gian',
  },
  'en': {
    AppKeys.appName: 'NUMI',
    AppKeys.loading: 'Loading...',
    AppKeys.close: 'Close',
    AppKeys.cancel: 'Cancel',
    AppKeys.save: 'Save',
    AppKeys.retry: 'Retry',
    AppKeys.retryUpper: 'RETRY',
    AppKeys.accept: 'Accept',
    AppKeys.reject: 'Reject',
    AppKeys.delete: 'Delete',
    AppKeys.update: 'Update',
    AppKeys.add: 'Add',
    AppKeys.back: 'Back',
    AppKeys.skipUpper: 'SKIP',
    AppKeys.continueUpper: 'CONTINUE',
    AppKeys.attemptExitTitle: 'Leave this attempt?',
    AppKeys.attemptExitMessage:
        'Your selected answers will be lost. Are you sure you want to leave?',
    AppKeys.exitUpper: 'LEAVE',
    AppKeys.language: 'Language',
    AppKeys.languageTitle: 'Language',
    AppKeys.languageMenuSubtitle: 'Change display language',
    AppKeys.languageVietnamese: 'Tiếng Việt',
    AppKeys.languageEnglish: 'English',
    AppKeys.continueLabel: 'Continue',
    AppKeys.time: 'Time',
  },
};
