import '../app_keys.dart';

const commonStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.appName: 'NUMI',
    AppKeys.loading: 'Äang táº£i...',
    AppKeys.close: 'ÄÃ³ng',
    AppKeys.cancel: 'Há»§y',
    AppKeys.save: 'LÆ°u',
    AppKeys.retry: 'Thá»­ láº¡i',
    AppKeys.retryUpper: 'THá»¬ Láº I',
    AppKeys.accept: 'Cháº¥p nháº­n',
    AppKeys.reject: 'Tá»« chá»‘i',
    AppKeys.delete: 'XÃ³a',
    AppKeys.update: 'Cáº­p nháº­t',
    AppKeys.add: 'ThÃªm',
    AppKeys.back: 'Quay láº¡i',
    AppKeys.skipUpper: 'Bá»Ž QUA',
    AppKeys.continueUpper: 'TIáº¾P Tá»¤C',
    AppKeys.language: 'NgÃ´n ngá»¯',
    AppKeys.languageTitle: 'NgÃ´n Ngá»¯',
    AppKeys.languageMenuSubtitle: 'Äá»•i ngÃ´n ngá»¯ hiá»ƒn thá»‹',
    AppKeys.languageVietnamese: 'Tiáº¿ng Viá»‡t',
    AppKeys.languageEnglish: 'English',
    AppKeys.welcomeTitlePrefix: 'Há»c ToÃ¡n cÃ¹ng\n',
    AppKeys.welcomeTitleN: 'NUMI',
    AppKeys.welcomeSubtitlePrefix: 'HÃ£y cÃ¹ng Numi',
    AppKeys.welcomeSubtitle: 'trá»Ÿ thÃ nh "phÃ¹ thá»§y" tÃ­nh toÃ¡n nhÃ©!',
    AppKeys.start: 'Báº®T Äáº¦U',
    AppKeys.continueLabel: 'Tiáº¿p tá»¥c',
    AppKeys.avatarUpper: 'áº¢NH Äáº I DIá»†N',
    AppKeys.chooseAvatar: 'Chá»n áº£nh Ä‘áº¡i diá»‡n',
    AppKeys.signingUp: 'Äang Ä‘Äƒng kÃ½...',
    AppKeys.studentMissingProfileId: 'Há»“ sÆ¡ há»c sinh thiáº¿u profile_id.',
    AppKeys.studentRetry: 'Thá»­ láº¡i',
    AppKeys.studentNoClassSearchResults: 'KhÃ´ng tÃ¬m tháº¥y lá»›p há»c',
    AppKeys.studentNoClassSearchResultsMessage:
        'Kiá»ƒm tra láº¡i mÃ£ lá»›p hoáº·c tÃªn lá»›p rá»“i thá»­ láº¡i.',
    AppKeys.studentEnterClassCodeTitle: 'Nháº­p mÃ£ hoáº·c tÃªn lá»›p',
    AppKeys.studentEnterClassCodeMessage:
        'Káº¿t quáº£ lá»›p há»c phÃ¹ há»£p sáº½ hiá»ƒn thá»‹ táº¡i Ä‘Ã¢y.',
    AppKeys.studentAlreadyJoinedClass: 'Báº¡n Ä‘Ã£ tham gia lá»›p há»c nÃ y.',
    AppKeys.studentNoInvitationsTitle: 'ChÆ°a cÃ³ lá»i má»i',
    AppKeys.studentNoInvitationsMessage:
        'Lá»i má»i lá»›p há»c má»›i sáº½ xuáº¥t hiá»‡n táº¡i Ä‘Ã¢y.',
    AppKeys.noChapterTitle: 'ChÆ°a cÃ³ chÆ°Æ¡ng',
    AppKeys.noChapterMessage:
        'ChÆ°a cÃ³ lá»™ trÃ¬nh Ã´n táº­p cho há»“ sÆ¡ nÃ y.',
    AppKeys.startTest: 'Báº¯t Ä‘áº§u kiá»ƒm tra ({count})',
    AppKeys.time: 'Thá»i gian',
    AppKeys.generateTestFailed:
        'Táº¡o test tháº¥t báº¡i. Vui lÃ²ng thá»­ láº¡i sau.',
    AppKeys.noGrades: 'ChÆ°a cÃ³ lá»›p há»c nÃ o Ä‘á»ƒ hiá»ƒn thá»‹.',
    AppKeys.completedResultTitle: 'HoÃ n ThÃ nh',
  },
  'en': {
    AppKeys.appName: 'NUMI',
    AppKeys.loading: 'Loading...',
    AppKeys.close: 'Close',
    AppKeys.cancel: 'Cancel',
    AppKeys.save: 'Save',
    AppKeys.retry: 'Retry',
    AppKeys.retryUpper: 'RETRY',
    AppKeys.accept: 'Accept',
    AppKeys.reject: 'Reject',
    AppKeys.delete: 'Delete',
    AppKeys.update: 'Update',
    AppKeys.add: 'Add',
    AppKeys.back: 'Back',
    AppKeys.skipUpper: 'SKIP',
    AppKeys.continueUpper: 'CONTINUE',
    AppKeys.language: 'Language',
    AppKeys.languageTitle: 'Language',
    AppKeys.languageMenuSubtitle: 'Change display language',
    AppKeys.languageVietnamese: 'Tiáº¿ng Viá»‡t',
    AppKeys.languageEnglish: 'English',
    AppKeys.welcomeTitlePrefix: 'Learn math with\n',
    AppKeys.welcomeTitleN: 'NUMI',
    AppKeys.welcomeSubtitlePrefix: 'Join Numi',
    AppKeys.welcomeSubtitle: 'and become a math wizard!',
    AppKeys.start: 'START',
    AppKeys.continueLabel: 'Continue',
    AppKeys.avatarUpper: 'AVATAR',
    AppKeys.chooseAvatar: 'Choose avatar',
    AppKeys.signingUp: 'Signing up...',
    AppKeys.studentMissingProfileId: 'Student profile is missing profile_id.',
    AppKeys.studentRetry: 'Try again',
    AppKeys.studentNoClassSearchResults: 'No classrooms found',
    AppKeys.studentNoClassSearchResultsMessage:
        'Check the class code or class name and try again.',
    AppKeys.studentEnterClassCodeTitle: 'Enter a code or class name',
    AppKeys.studentEnterClassCodeMessage:
        'Matching classroom results will appear here.',
    AppKeys.studentAlreadyJoinedClass: 'You have already joined this class.',
    AppKeys.studentNoInvitationsTitle: 'No invitations yet',
    AppKeys.studentNoInvitationsMessage:
        'New class invitations will appear here.',
    AppKeys.noChapterTitle: 'No chapters',
    AppKeys.noChapterMessage:
        'No review journey is available for this profile.',
    AppKeys.startTest: 'Start test ({count})',
    AppKeys.time: 'Time',
    AppKeys.generateTestFailed: 'Failed to create test. Please try later.',
    AppKeys.noGrades: 'No grades to show.',
    AppKeys.completedResultTitle: 'Completed',
  },
};
