import '../app_keys.dart';

const gamesStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.gamesGradeTitle: 'Chọn lớp để bắt đầu',
    AppKeys.gamesGradeSubtitle:
        'NUMI sẽ điều chỉnh nội dung và độ khó theo lớp của bé.',
    AppKeys.gamesSelectGrade: 'Chọn lớp này',
    AppKeys.gamesChooseTitle: 'Chọn một hành trình',
    AppKeys.gamesChooseSubtitle:
        'Chọn game để mở bản đồ và bắt đầu hành trình thử thách.',
    AppKeys.gamesPrototype: 'BẢN MẪU',
    AppKeys.gamesLevelCount: '{count} màn',
    AppKeys.gamesLevelLabel: 'Màn {level}',
    AppKeys.gamesLevelComingSoon:
        'Màn {level} đã sẵn sàng cho game được chọn sau.',
    AppKeys.gamesJourneyOne: 'Nông trại Numi',
    AppKeys.gamesJourneyTwo: 'Hành trình Numi 02',
    AppKeys.gamesJourneyThree: 'Hành trình Numi 03',
    AppKeys.gamesFarmTitle: 'Nông trại Numi',
    AppKeys.gamesFarmStageOneTitle: 'Đếm và thu hoạch từ 1 đến 5',
    AppKeys.gamesFarmStageTwoTitle: 'Đếm và thu hoạch từ 1 đến 10',
    AppKeys.gamesFarmStageThreeTitle: 'So sánh hai giỏ nông sản',
    AppKeys.gamesFarmStageFourTitle: 'Gộp giỏ - phép cộng trong 10',
    AppKeys.gamesFarmStageFiveTitle: 'Bớt nông sản - phép trừ trong 10',
    AppKeys.gamesFarmOrderLabel: 'ĐƠN HÀNG CỦA NUMI',
    AppKeys.gamesFarmHarvestPrefix: 'Hãy hái',
    AppKeys.gamesFarmHarvestSuffix: 'củ cà rốt',
    AppKeys.gamesFarmCorrect: 'CHÍNH XÁC!',
    AppKeys.gamesFarmIncorrect: 'CHƯA ĐÚNG!',
    AppKeys.gamesFarmBasketReady: 'Giỏ cà rốt đã đủ rồi!',
    AppKeys.gamesFarmComparePrompt: 'Chọn dấu đúng giữa hai giỏ',
    AppKeys.gamesFarmAdditionPrompt: 'Hai giỏ có tất cả bao nhiêu?',
    AppKeys.gamesFarmSubtractionPrompt: 'Sau khi bớt đi còn bao nhiêu?',
    AppKeys.gamesFarmCarrot: 'Cà rốt',
    AppKeys.gamesFarmCheck: 'KIỂM TRA',
    AppKeys.gamesFarmNext: 'TIẾP TỤC',
    AppKeys.gamesFarmFinish: 'HOÀN THÀNH',
    AppKeys.gamesFarmCompleteTitle: 'Thu hoạch xong!',
    AppKeys.gamesFarmCompleteMessage:
        'Bé đã hoàn thành xuất sắc Màn {stage} của Nông trại Numi.',
    AppKeys.gamesFarmBackToMap: 'VỀ BẢN ĐỒ',
    AppKeys.gamesFarmTime: 'Thời gian',
    AppKeys.gamesFarmCorrectCount: 'Đúng',
    AppKeys.gamesFarmWrongCount: 'Sai',
    AppKeys.gamesExitTitle: 'Rời trò chơi?',
    AppKeys.gamesExitMessage: 'Tiến độ của lượt chơi này sẽ không được lưu.',
    AppKeys.gamesKeepPlaying: 'CHƠI TIẾP',
    AppKeys.gamesRescueTitle: 'Numi Monster Rescue',
    AppKeys.gamesRescueLevelOne: 'Giải cứu Numi Điện',
    AppKeys.gamesRescueUrgent: 'NHIỆM VỤ KHẨN CẤP',
    AppKeys.gamesRescueIntroMessage:
        '{name} đang bị nhốt sâu trong rừng. Hãy dẫn đội Numi đến giải cứu bạn ấy!',
    AppKeys.gamesRescueStart: 'BẮT ĐẦU GIẢI CỨU',
    AppKeys.gamesRescueCheckpoint: 'CHẶNG {current}/{total}',
    AppKeys.gamesRescueChoosePath: 'Chọn cổng cho cả đội!',
    AppKeys.gamesRescueGateHint:
        'Chạm vào một cổng và xem đội Numi lớn mạnh ngay lập tức.',
    AppKeys.gamesRescueTeamChallenge: 'THỬ THÁCH ĐỒNG ĐỘI',
    AppKeys.gamesRescueBridgeTitle: 'Chia đội để mở cầu',
    AppKeys.gamesRescueBridgeHint:
        'Cần đúng {count} Numi giữ cần gạt. Các bạn còn lại sẽ chạy qua cầu.',
    AppKeys.gamesRescueHoldLever: 'Giữ cần gạt',
    AppKeys.gamesRescueCrossBridge: 'Qua cầu',
    AppKeys.gamesRescueOpenBridge: 'MỞ CẦU!',
    AppKeys.gamesRescueNeedExactTeam: 'CHỌN ĐÚNG SỐ NUMI',
    AppKeys.gamesRescueFinalChallenge: 'TRẬN CHIẾN CUỐI',
    AppKeys.gamesRescueBossTitle: 'Phá khóa năng lượng!',
    AppKeys.gamesRescueBossHint:
        'Chạm từng lõi để cử đúng số Numi tấn công. Phá cả ba để mở lồng!',
    AppKeys.gamesRescueBossName: 'Robot Gác Cổng',
    AppKeys.gamesRescueNumiReady: '{count} Numi sẵn sàng',
    AppKeys.gamesRescueCompleteTitle: 'Giải cứu thành công!',
    AppKeys.gamesRescueCompleteMessage:
        '{name} đã gia nhập bộ sưu tập và đang chờ về Đảo Numi cùng bé.',
    AppKeys.gamesRescueSkillUnlocked: 'MỞ KHÓA: NHÂN ĐÔI SỨC MẠNH',
    AppKeys.gamesRescueBringHome: 'ĐƯA NUMI VỀ ĐẢO',
    AppKeys.gamesRescueBackToMap: 'VỀ BẢN ĐỒ',
  },
  'en': {
    AppKeys.gamesGradeTitle: 'Choose a grade to begin',
    AppKeys.gamesGradeSubtitle:
        'NUMI will match the content and difficulty to the child\'s grade.',
    AppKeys.gamesSelectGrade: 'Choose this grade',
    AppKeys.gamesChooseTitle: 'Choose an adventure',
    AppKeys.gamesChooseSubtitle:
        'Choose a game to open its map and begin the challenge.',
    AppKeys.gamesPrototype: 'PROTOTYPE',
    AppKeys.gamesLevelCount: '{count} stages',
    AppKeys.gamesLevelLabel: 'Stage {level}',
    AppKeys.gamesLevelComingSoon:
        'Stage {level} is ready for the game we choose next.',
    AppKeys.gamesJourneyOne: 'Numi Farm',
    AppKeys.gamesJourneyTwo: 'Numi Journey 02',
    AppKeys.gamesJourneyThree: 'Numi Journey 03',
    AppKeys.gamesFarmTitle: 'Numi Farm',
    AppKeys.gamesFarmStageOneTitle: 'Count and harvest from 1 to 5',
    AppKeys.gamesFarmStageTwoTitle: 'Count and harvest from 1 to 10',
    AppKeys.gamesFarmStageThreeTitle: 'Compare two produce baskets',
    AppKeys.gamesFarmStageFourTitle: 'Combine baskets - add within 10',
    AppKeys.gamesFarmStageFiveTitle: 'Remove produce - subtract within 10',
    AppKeys.gamesFarmOrderLabel: 'NUMI\'S ORDER',
    AppKeys.gamesFarmHarvestPrefix: 'Pick',
    AppKeys.gamesFarmHarvestSuffix: 'carrots',
    AppKeys.gamesFarmCorrect: 'THAT\'S RIGHT!',
    AppKeys.gamesFarmIncorrect: 'NOT QUITE!',
    AppKeys.gamesFarmBasketReady: 'The carrot basket is ready!',
    AppKeys.gamesFarmComparePrompt:
        'Choose the correct sign between the baskets',
    AppKeys.gamesFarmAdditionPrompt: 'How many items are in both baskets?',
    AppKeys.gamesFarmSubtractionPrompt:
        'How many items remain after taking some away?',
    AppKeys.gamesFarmCarrot: 'Carrot',
    AppKeys.gamesFarmCheck: 'CHECK',
    AppKeys.gamesFarmNext: 'CONTINUE',
    AppKeys.gamesFarmFinish: 'FINISH',
    AppKeys.gamesFarmCompleteTitle: 'Harvest complete!',
    AppKeys.gamesFarmCompleteMessage:
        'You completed Stage {stage} of Numi Farm.',
    AppKeys.gamesFarmBackToMap: 'BACK TO MAP',
    AppKeys.gamesFarmTime: 'Time',
    AppKeys.gamesFarmCorrectCount: 'Correct',
    AppKeys.gamesFarmWrongCount: 'Wrong',
    AppKeys.gamesExitTitle: 'Leave the game?',
    AppKeys.gamesExitMessage:
        'Progress from this play session will not be saved.',
    AppKeys.gamesKeepPlaying: 'KEEP PLAYING',
    AppKeys.gamesRescueTitle: 'Numi Monster Rescue',
    AppKeys.gamesRescueLevelOne: 'Rescue Numi Spark',
    AppKeys.gamesRescueUrgent: 'URGENT MISSION',
    AppKeys.gamesRescueIntroMessage:
        '{name} is trapped deep in the forest. Lead your Numi team to the rescue!',
    AppKeys.gamesRescueStart: 'START THE RESCUE',
    AppKeys.gamesRescueCheckpoint: 'CHECKPOINT {current}/{total}',
    AppKeys.gamesRescueChoosePath: 'Choose a gate for the team!',
    AppKeys.gamesRescueGateHint:
        'Tap a gate and watch your Numi team grow instantly.',
    AppKeys.gamesRescueTeamChallenge: 'TEAM CHALLENGE',
    AppKeys.gamesRescueBridgeTitle: 'Split the team to open the bridge',
    AppKeys.gamesRescueBridgeHint:
        'Exactly {count} Numi must hold the lever. Everyone else can cross.',
    AppKeys.gamesRescueHoldLever: 'Hold lever',
    AppKeys.gamesRescueCrossBridge: 'Cross bridge',
    AppKeys.gamesRescueOpenBridge: 'OPEN THE BRIDGE!',
    AppKeys.gamesRescueNeedExactTeam: 'CHOOSE THE EXACT TEAM',
    AppKeys.gamesRescueFinalChallenge: 'FINAL BATTLE',
    AppKeys.gamesRescueBossTitle: 'Break the energy locks!',
    AppKeys.gamesRescueBossHint:
        'Tap each core to send the exact Numi team. Break all three to open the cage!',
    AppKeys.gamesRescueBossName: 'Gatekeeper Bot',
    AppKeys.gamesRescueNumiReady: '{count} Numi ready',
    AppKeys.gamesRescueCompleteTitle: 'Rescue complete!',
    AppKeys.gamesRescueCompleteMessage:
        '{name} joined your collection and is ready to come home to Numi Island.',
    AppKeys.gamesRescueSkillUnlocked: 'UNLOCKED: DOUBLE POWER',
    AppKeys.gamesRescueBringHome: 'BRING NUMI HOME',
    AppKeys.gamesRescueBackToMap: 'BACK TO MAP',
  },
};
