import '../app_keys.dart';

const gamesStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.gamesGradeTitle: 'Chọn lớp để bắt đầu',
    AppKeys.gamesGradeSubtitle:
        'NUMI sẽ điều chỉnh nội dung và độ khó theo lớp của bé.',
    AppKeys.gamesSelectGrade: 'Chọn lớp này',
    AppKeys.gamesChooseTitle: 'Chọn một hành trình',
    AppKeys.gamesChooseSubtitle:
        'Chọn game để mở bản đồ và bắt đầu hành trình thử thách.',
    AppKeys.gamesPrototype: 'BẢN MẪU',
    AppKeys.gamesLevelCount: '{count} màn',
    AppKeys.gamesLevelLabel: 'Màn {level}',
    AppKeys.gamesLevelComingSoon:
        'Màn {level} đã sẵn sàng cho game được chọn sau.',
    AppKeys.gamesJourneyOne: 'Nông trại Numi',
    AppKeys.gamesJourneyTwo: 'Hành trình Numi 02',
    AppKeys.gamesJourneyThree: 'Hành trình Numi 03',
    AppKeys.gamesFarmTitle: 'Nông trại Numi',
    AppKeys.gamesFarmStageOneTitle: 'Đếm và thu hoạch từ 1 đến 5',
    AppKeys.gamesFarmStageTwoTitle: 'Đếm và thu hoạch từ 1 đến 10',
    AppKeys.gamesFarmStageThreeTitle: 'So sánh hai giỏ nông sản',
    AppKeys.gamesFarmStageFourTitle: 'Gộp giỏ - phép cộng trong 10',
    AppKeys.gamesFarmStageFiveTitle: 'Bớt nông sản - phép trừ trong 10',
    AppKeys.gamesFarmOrderLabel: 'ĐƠN HÀNG CỦA NUMI',
    AppKeys.gamesFarmHarvestPrefix: 'Hãy hái',
    AppKeys.gamesFarmHarvestSuffix: 'củ cà rốt',
    AppKeys.gamesFarmCorrect: 'CHÍNH XÁC!',
    AppKeys.gamesFarmIncorrect: 'CHƯA ĐÚNG!',
    AppKeys.gamesFarmBasketReady: 'Giỏ cà rốt đã đủ rồi!',
    AppKeys.gamesFarmComparePrompt: 'Chọn dấu đúng giữa hai giỏ',
    AppKeys.gamesFarmAdditionPrompt: 'Hai giỏ có tất cả bao nhiêu?',
    AppKeys.gamesFarmSubtractionPrompt: 'Sau khi bớt đi còn bao nhiêu?',
    AppKeys.gamesFarmCarrot: 'Cà rốt',
    AppKeys.gamesFarmCheck: 'KIỂM TRA',
    AppKeys.gamesFarmNext: 'TIẾP TỤC',
    AppKeys.gamesFarmFinish: 'HOÀN THÀNH',
    AppKeys.gamesFarmCompleteTitle: 'Thu hoạch xong!',
    AppKeys.gamesFarmCompleteMessage:
        'Bé đã hoàn thành xuất sắc Màn {stage} của Nông trại Numi.',
    AppKeys.gamesFarmBackToMap: 'VỀ BẢN ĐỒ',
    AppKeys.gamesFarmTime: 'Thời gian',
    AppKeys.gamesFarmCorrectCount: 'Đúng',
    AppKeys.gamesFarmWrongCount: 'Sai',
    AppKeys.gamesSquadronTitle: 'Phi đội Toán học',
    AppKeys.gamesSquadronLevelOne: 'Màn 1 · Tuần tra số học',
    AppKeys.gamesSquadronLevelTwo: 'Màn 2 · Vành đai cửu chương',
    AppKeys.gamesSquadronLevelThree: 'Màn 3 · BOSS Drone Nhân Chia',
    AppKeys.gamesSquadronLevelFour: 'Màn 4 · Truy tìm ẩn số',
    AppKeys.gamesSquadronLevelFive: 'Màn 5 · BOSS Pháo đài 1.000',
    AppKeys.gamesSquadronLevelSix: 'Màn 6 · Cổng không-thời gian',
    AppKeys.gamesSquadronLevelSeven: 'Màn 7 · BOSS Vua Thiên Thạch',
    AppKeys.gamesSquadronBossLevel: 'BOSS · MÀN {level}',
    AppKeys.gamesSquadronBossEnergy: 'NĂNG LƯỢNG BOSS',
    AppKeys.gamesSquadronMission: 'CHẠM MỤC TIÊU ĐÚNG',
    AppKeys.gamesSquadronComplete: 'Nhiệm vụ hoàn thành!',
    AppKeys.gamesSquadronBossDefeated: 'Đã hạ Boss!',
    AppKeys.gamesSquadronTryAgain: 'Phi thuyền cần sửa chữa!',
    AppKeys.gamesSquadronLevelComplete:
        'Bé đã hoàn thành Màn {level} của Phi đội Toán học.',
    AppKeys.gamesSquadronNeedAccuracy:
        'Cần phá ít nhất 10 trong 30 thiên thạch toán và giữ lại khiên để qua màn.',
    AppKeys.gamesSquadronExitTitle: 'Rời nhiệm vụ?',
    AppKeys.gamesSquadronExitMessage:
        'Tiến độ của lượt chơi này sẽ không được lưu.',
    AppKeys.gamesSquadronKeepPlaying: 'CHƠI TIẾP',
    AppKeys.gamesSquadronFlightHint:
        'Kéo tàu để né • Chọn đạn đáp án • Bắn thiên thạch',
    AppKeys.gamesSquadronChooseAmmoFirst:
        'Hãy chọn một viên đạn đáp án trước khi bắn!',
    AppKeys.gamesSquadronFire: 'BẮN',
    AppKeys.gamesSquadronSelectTarget:
        'Chạm vào thiên thạch hoặc bộ phận boss để khóa mục tiêu!',
    AppKeys.gamesSquadronCurrentAmmo: 'ĐẠN HIỆN TẠI',
    AppKeys.gamesSquadronTargetLocked: 'Đã khóa mục tiêu • Sẵn sàng bắn',
    AppKeys.gamesSquadronTapMeteor: 'Chạm vào một mục tiêu để ngắm',
    AppKeys.gamesSquadronNextAmmo: 'Đạn kế tiếp: {ammo}',
    AppKeys.gamesSquadronLaserWarning: 'CẢNH BÁO LASER • HÃY NÉ!',
    AppKeys.gamesSquadronAimShip: 'Di chuyển tàu vào đúng làn rồi bắn thẳng',
    AppKeys.gamesSquadronReloading: 'ĐANG NẠP',
  },
  'en': {
    AppKeys.gamesGradeTitle: 'Choose a grade to begin',
    AppKeys.gamesGradeSubtitle:
        'NUMI will match the content and difficulty to the child\'s grade.',
    AppKeys.gamesSelectGrade: 'Choose this grade',
    AppKeys.gamesChooseTitle: 'Choose an adventure',
    AppKeys.gamesChooseSubtitle:
        'Choose a game to open its map and begin the challenge.',
    AppKeys.gamesPrototype: 'PROTOTYPE',
    AppKeys.gamesLevelCount: '{count} stages',
    AppKeys.gamesLevelLabel: 'Stage {level}',
    AppKeys.gamesLevelComingSoon:
        'Stage {level} is ready for the game we choose next.',
    AppKeys.gamesJourneyOne: 'Numi Farm',
    AppKeys.gamesJourneyTwo: 'Numi Journey 02',
    AppKeys.gamesJourneyThree: 'Numi Journey 03',
    AppKeys.gamesFarmTitle: 'Numi Farm',
    AppKeys.gamesFarmStageOneTitle: 'Count and harvest from 1 to 5',
    AppKeys.gamesFarmStageTwoTitle: 'Count and harvest from 1 to 10',
    AppKeys.gamesFarmStageThreeTitle: 'Compare two produce baskets',
    AppKeys.gamesFarmStageFourTitle: 'Combine baskets - add within 10',
    AppKeys.gamesFarmStageFiveTitle: 'Remove produce - subtract within 10',
    AppKeys.gamesFarmOrderLabel: 'NUMI\'S ORDER',
    AppKeys.gamesFarmHarvestPrefix: 'Pick',
    AppKeys.gamesFarmHarvestSuffix: 'carrots',
    AppKeys.gamesFarmCorrect: 'THAT\'S RIGHT!',
    AppKeys.gamesFarmIncorrect: 'NOT QUITE!',
    AppKeys.gamesFarmBasketReady: 'The carrot basket is ready!',
    AppKeys.gamesFarmComparePrompt:
        'Choose the correct sign between the baskets',
    AppKeys.gamesFarmAdditionPrompt: 'How many items are in both baskets?',
    AppKeys.gamesFarmSubtractionPrompt:
        'How many items remain after taking some away?',
    AppKeys.gamesFarmCarrot: 'Carrot',
    AppKeys.gamesFarmCheck: 'CHECK',
    AppKeys.gamesFarmNext: 'CONTINUE',
    AppKeys.gamesFarmFinish: 'FINISH',
    AppKeys.gamesFarmCompleteTitle: 'Harvest complete!',
    AppKeys.gamesFarmCompleteMessage:
        'You completed Stage {stage} of Numi Farm.',
    AppKeys.gamesFarmBackToMap: 'BACK TO MAP',
    AppKeys.gamesFarmTime: 'Time',
    AppKeys.gamesFarmCorrectCount: 'Correct',
    AppKeys.gamesFarmWrongCount: 'Wrong',
    AppKeys.gamesSquadronTitle: 'Math Squadron',
    AppKeys.gamesSquadronLevelOne: 'Stage 1 · Number Patrol',
    AppKeys.gamesSquadronLevelTwo: 'Stage 2 · Times-table Belt',
    AppKeys.gamesSquadronLevelThree: 'Stage 3 · BOSS Multiply Drone',
    AppKeys.gamesSquadronLevelFour: 'Stage 4 · Find the Unknown',
    AppKeys.gamesSquadronLevelFive: 'Stage 5 · BOSS Fortress 1,000',
    AppKeys.gamesSquadronLevelSix: 'Stage 6 · Space-time Gate',
    AppKeys.gamesSquadronLevelSeven: 'Stage 7 · BOSS Meteor King',
    AppKeys.gamesSquadronBossLevel: 'BOSS · STAGE {level}',
    AppKeys.gamesSquadronBossEnergy: 'BOSS ENERGY',
    AppKeys.gamesSquadronMission: 'TAP THE CORRECT TARGET',
    AppKeys.gamesSquadronComplete: 'Mission complete!',
    AppKeys.gamesSquadronBossDefeated: 'Boss defeated!',
    AppKeys.gamesSquadronTryAgain: 'Ship needs repairs!',
    AppKeys.gamesSquadronLevelComplete:
        'You completed Stage {level} of Math Squadron.',
    AppKeys.gamesSquadronNeedAccuracy:
        'Destroy at least 10 of 30 math meteors and keep a shield to pass.',
    AppKeys.gamesSquadronExitTitle: 'Leave mission?',
    AppKeys.gamesSquadronExitMessage:
        'Progress from this play session will not be saved.',
    AppKeys.gamesSquadronKeepPlaying: 'KEEP PLAYING',
    AppKeys.gamesSquadronFlightHint:
        'Drag to dodge • Choose answer ammo • Fire',
    AppKeys.gamesSquadronChooseAmmoFirst:
        'Choose an answer charge before firing!',
    AppKeys.gamesSquadronFire: 'FIRE',
    AppKeys.gamesSquadronSelectTarget:
        'Tap a meteor or boss part to lock the target!',
    AppKeys.gamesSquadronCurrentAmmo: 'CURRENT AMMO',
    AppKeys.gamesSquadronTargetLocked: 'Target locked • Ready to fire',
    AppKeys.gamesSquadronTapMeteor: 'Tap a target to aim',
    AppKeys.gamesSquadronNextAmmo: 'Next ammo: {ammo}',
    AppKeys.gamesSquadronLaserWarning: 'LASER WARNING • DODGE!',
    AppKeys.gamesSquadronAimShip:
        'Move the ship into a lane and fire straight ahead',
    AppKeys.gamesSquadronReloading: 'RELOAD',
  },
};
