import '../../app_keys.dart';

const quizStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.incomplete: 'Chưa xong',
    AppKeys.mathAssessment: 'Bài kiểm tra Toán',
    AppKeys.mathPractice: 'Bài luyện tập Toán',
    AppKeys.mathReview: 'Bài ôn tập Toán',
    AppKeys.excellent: 'Tuyệt vời!',
    AppKeys.good: 'Tốt',
    AppKeys.niceTry: 'Cố gắng tốt',
    AppKeys.failed: 'Chưa đạt',
    AppKeys.quizDetailLoadFailed: 'Tải chi tiết bài kiểm tra thất bại.',
    AppKeys.quizDetailTitle: 'Chi Tiết',
    AppKeys.emptyQuizQuestions: 'Bài kiểm tra chưa có câu hỏi.',
    AppKeys.totalQuestions: 'Tổng câu',
    AppKeys.correct: 'Đúng',
    AppKeys.incorrect: 'Sai',
    AppKeys.questionNumber: 'Câu {number}',
    AppKeys.viewResult: 'Xem Kết Quả',
    AppKeys.previous: 'Trước',
    AppKeys.next: 'Tiếp',
    AppKeys.correctStatus: 'Chính Xác',
    AppKeys.incorrectStatus: 'Chưa Đúng',
    AppKeys.showAnswerUpper: 'ĐÁP ÁN',
    AppKeys.hideAnswerUpper: 'ẨN ĐÁP ÁN',
    AppKeys.noAnswer: 'Chưa có đáp án.',
    AppKeys.answer: 'Đáp án: {answer}',
    AppKeys.quizDetailErrorTitle: 'Không tải được chi tiết bài kiểm tra.',
    AppKeys.createQuestionFailed: 'Không thể tạo câu hỏi. Vui lòng thử lại.',
    AppKeys.missingQuizToSubmit: 'Không tìm thấy bài test để nộp.',
    AppKeys.submitQuizFailed: 'Nộp bài thất bại. Vui lòng thử lại.',
    AppKeys.unansweredSubmitTitle: 'Bạn có câu hỏi chưa trả lời',
    AppKeys.unansweredSubmitMessage: 'Bạn có chắc muốn nộp bài không?',
    AppKeys.stayUpper: 'Ở LẠI',
    AppKeys.submitUpper: 'NỘP BÀI',
    AppKeys.submittingForYou: 'đợi Numi nộp bài cho bạn nhé!',
    AppKeys.generatingAssessment: 'Để Numi tạo bài kiểm tra cho bạn nhé',
    AppKeys.aiChallenge: 'Thử thách AI',
    AppKeys.questionProgress: 'CÂU {current}/{total}',
    AppKeys.previousQuestionUpper: 'CÂU TRƯỚC',
    AppKeys.submittingUpper: 'ĐANG NỘP',
    AppKeys.excellentResultTitle: 'Xuất Sắc',
    AppKeys.goodResultTitle: 'Tốt',
    AppKeys.incompleteResultTitle: 'Chưa Hoàn Thành',
    AppKeys.excellentResultMessage: '',
    AppKeys.generatingNewQuiz: 'đợi Numi tạo bài mới cho bạn nhé!',
    AppKeys.assessmentResultTitle: 'Kết Quả',
    AppKeys.scoreUpper: 'ĐIỂM SỐ',
    AppKeys.numiAiReview: 'Numi AI nhận xét',
    AppKeys.defaultAiReview:
        'Bé làm rất tốt phần phép cộng, hãy tiếp tục phát huy nhé! Chúng ta chỉ cần thôi.',
    AppKeys.defaultAiReviewHighlight: 'phép cộng',
    AppKeys.assessmentUpper: 'Đánh Giá',
    AppKeys.practiceUpper: 'Luyện Tập',
    AppKeys.quizHasNoQuestions: 'Quiz không có câu hỏi.',
  },
  'en': {
    AppKeys.incomplete: 'Incomplete',
    AppKeys.mathAssessment: 'Math assessment',
    AppKeys.mathPractice: 'Math practice',
    AppKeys.mathReview: 'Math review',
    AppKeys.excellent: 'Excellent!',
    AppKeys.good: 'Good',
    AppKeys.niceTry: 'Nice try',
    AppKeys.failed: 'Failed',
    AppKeys.quizDetailLoadFailed: 'Failed to load test details.',
    AppKeys.quizDetailTitle: 'Detail',
    AppKeys.emptyQuizQuestions: 'This test has no questions.',
    AppKeys.totalQuestions: 'Questions',
    AppKeys.correct: 'Correct',
    AppKeys.incorrect: 'Wrong',
    AppKeys.questionNumber: 'Question {number}',
    AppKeys.viewResult: 'View Result',
    AppKeys.previous: 'Previous',
    AppKeys.next: 'Next',
    AppKeys.correctStatus: 'Correct',
    AppKeys.incorrectStatus: 'Incorrect',
    AppKeys.showAnswerUpper: 'ANSWER',
    AppKeys.hideAnswerUpper: 'HIDE ANSWER',
    AppKeys.noAnswer: 'No answer available.',
    AppKeys.answer: 'Answer: {answer}',
    AppKeys.quizDetailErrorTitle: 'Could not load test details.',
    AppKeys.createQuestionFailed:
        'Could not create questions. Please try again.',
    AppKeys.missingQuizToSubmit: 'Could not find a test to submit.',
    AppKeys.submitQuizFailed: 'Failed to submit. Please try again.',
    AppKeys.unansweredSubmitTitle: 'Some questions are unanswered',
    AppKeys.unansweredSubmitMessage: 'Are you sure you want to submit now?',
    AppKeys.stayUpper: 'STAY',
    AppKeys.submitUpper: 'SUBMIT',
    AppKeys.submittingForYou: 'Numi is submitting your test...',
    AppKeys.generatingAssessment: 'Let Numi create your test',
    AppKeys.aiChallenge: 'AI Challenge',
    AppKeys.questionProgress: 'QUESTION {current}/{total}',
    AppKeys.previousQuestionUpper: 'PREVIOUS',
    AppKeys.submittingUpper: 'SUBMITTING',
    AppKeys.excellentResultTitle: 'Excellent',
    AppKeys.goodResultTitle: 'Good',
    AppKeys.incompleteResultTitle: 'Not Completed',
    AppKeys.excellentResultMessage: '',
    AppKeys.generatingNewQuiz: 'Numi is creating a new test...',
    AppKeys.assessmentResultTitle: 'Result',
    AppKeys.scoreUpper: 'SCORE',
    AppKeys.numiAiReview: 'Numi AI review',
    AppKeys.defaultAiReview:
        'Your child did very well with addition. Keep going, and practice subtraction with regrouping a little more.',
    AppKeys.defaultAiReviewHighlight: 'addition',
    AppKeys.assessmentUpper: 'Review',
    AppKeys.practiceUpper: 'Practice',
    AppKeys.quizHasNoQuestions: 'Quiz has no questions.',
  },
};
