import '../../app_keys.dart';

const quizStrings = <String, Map<String, String>>{
  'vi': {
    AppKeys.incomplete: 'ChÆ°a xong',
    AppKeys.mathAssessment: 'BÃ i kiá»ƒm tra ToÃ¡n',
    AppKeys.mathPractice: 'BÃ i luyá»‡n táº­p ToÃ¡n',
    AppKeys.mathReview: 'BÃ i Ã´n táº­p ToÃ¡n',
    AppKeys.excellent: 'Tuyá»‡t vá»i!',
    AppKeys.good: 'Tá»‘t',
    AppKeys.niceTry: 'Cá»‘ gáº¯ng tá»‘t',
    AppKeys.failed: 'ChÆ°a Ä‘áº¡t',
    AppKeys.quizDetailLoadFailed:
        'Táº£i chi tiáº¿t bÃ i kiá»ƒm tra tháº¥t báº¡i.',
    AppKeys.quizDetailTitle: 'Chi Tiáº¿t',
    AppKeys.emptyQuizQuestions: 'BÃ i kiá»ƒm tra chÆ°a cÃ³ cÃ¢u há»i.',
    AppKeys.totalQuestions: 'Tá»•ng cÃ¢u',
    AppKeys.correct: 'ÄÃºng',
    AppKeys.incorrect: 'Sai',
    AppKeys.questionNumber: 'CÃ¢u {number}',
    AppKeys.viewResult: 'Xem Káº¿t Quáº£',
    AppKeys.previous: 'TrÆ°á»›c',
    AppKeys.next: 'Tiáº¿p',
    AppKeys.correctStatus: 'ChÃ­nh XÃ¡c',
    AppKeys.incorrectStatus: 'ChÆ°a ÄÃºng',
    AppKeys.showAnswerUpper: 'ÄÃP ÃN',
    AppKeys.hideAnswerUpper: 'áº¨N ÄÃP ÃN',
    AppKeys.noAnswer: 'ChÆ°a cÃ³ Ä‘Ã¡p Ã¡n.',
    AppKeys.answer: 'ÄÃ¡p Ã¡n: {answer}',
    AppKeys.quizDetailErrorTitle:
        'KhÃ´ng táº£i Ä‘Æ°á»£c chi tiáº¿t bÃ i kiá»ƒm tra.',
    AppKeys.createQuestionFailed:
        'KhÃ´ng thá»ƒ táº¡o cÃ¢u há»i. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.missingQuizToSubmit: 'KhÃ´ng tÃ¬m tháº¥y bÃ i test Ä‘á»ƒ ná»™p.',
    AppKeys.submitQuizFailed: 'Ná»™p bÃ i tháº¥t báº¡i. Vui lÃ²ng thá»­ láº¡i.',
    AppKeys.unansweredSubmitTitle: 'Báº¡n cÃ³ cÃ¢u há»i chÆ°a tráº£ lá»i',
    AppKeys.unansweredSubmitMessage:
        'Báº¡n cÃ³ cháº¯c muá»‘n ná»™p bÃ i khÃ´ng?',
    AppKeys.stayUpper: 'á»ž Láº I',
    AppKeys.submitUpper: 'Ná»˜P BÃ€I',
    AppKeys.submittingForYou: 'Ä‘á»£i Numi ná»™p bÃ i cho báº¡n nhÃ©!',
    AppKeys.generatingAssessment:
        'Äá»ƒ Numi táº¡o bÃ i kiá»ƒm tra cho báº¡n nhÃ©',
    AppKeys.aiChallenge: 'Thá»­ thÃ¡ch AI',
    AppKeys.questionProgress: 'CÃ‚U {current}/{total}',
    AppKeys.previousQuestionUpper: 'CÃ‚U TRÆ¯á»šC',
    AppKeys.submittingUpper: 'ÄANG Ná»˜P',
    AppKeys.excellentResultTitle: 'Xuáº¥t Sáº¯c',
    AppKeys.goodResultTitle: 'Tá»‘t',
    AppKeys.incompleteResultTitle: 'ChÆ°a HoÃ n ThÃ nh',
    AppKeys.excellentResultMessage: '',
    AppKeys.generatingNewQuiz: 'Ä‘á»£i Numi táº¡o bÃ i má»›i cho báº¡n nhÃ©!',
    AppKeys.assessmentResultTitle: 'Káº¿t Quáº£',
    AppKeys.scoreUpper: 'ÄIá»‚M Sá»',
    AppKeys.numiAiReview: 'Numi AI nháº­n xÃ©t',
    AppKeys.defaultAiReview:
        'BÃ© lÃ m ráº¥t tá»‘t pháº§n phÃ©p cá»™ng, hÃ£y tiáº¿p tá»¥c phÃ¡t huy nhÃ©! ChÃºng ta chá»‰ cáº§n thÃ´i.',
    AppKeys.defaultAiReviewHighlight: 'phÃ©p cá»™ng',
    AppKeys.assessmentUpper: 'ÄÃ¡nh GiÃ¡',
    AppKeys.practiceUpper: 'Luyá»‡n Táº­p',
    AppKeys.quizHasNoQuestions: 'Quiz khÃ´ng cÃ³ cÃ¢u há»i.',
  },
  'en': {
    AppKeys.incomplete: 'Incomplete',
    AppKeys.mathAssessment: 'Math assessment',
    AppKeys.mathPractice: 'Math practice',
    AppKeys.mathReview: 'Math review',
    AppKeys.excellent: 'Excellent!',
    AppKeys.good: 'Good',
    AppKeys.niceTry: 'Nice try',
    AppKeys.failed: 'Failed',
    AppKeys.quizDetailLoadFailed: 'Failed to load test details.',
    AppKeys.quizDetailTitle: 'Detail',
    AppKeys.emptyQuizQuestions: 'This test has no questions.',
    AppKeys.totalQuestions: 'Questions',
    AppKeys.correct: 'Correct',
    AppKeys.incorrect: 'Wrong',
    AppKeys.questionNumber: 'Question {number}',
    AppKeys.viewResult: 'View Result',
    AppKeys.previous: 'Previous',
    AppKeys.next: 'Next',
    AppKeys.correctStatus: 'Correct',
    AppKeys.incorrectStatus: 'Incorrect',
    AppKeys.showAnswerUpper: 'ANSWER',
    AppKeys.hideAnswerUpper: 'HIDE ANSWER',
    AppKeys.noAnswer: 'No answer available.',
    AppKeys.answer: 'Answer: {answer}',
    AppKeys.quizDetailErrorTitle: 'Could not load test details.',
    AppKeys.createQuestionFailed:
        'Could not create questions. Please try again.',
    AppKeys.missingQuizToSubmit: 'Could not find a test to submit.',
    AppKeys.submitQuizFailed: 'Failed to submit. Please try again.',
    AppKeys.unansweredSubmitTitle: 'Some questions are unanswered',
    AppKeys.unansweredSubmitMessage: 'Are you sure you want to submit now?',
    AppKeys.stayUpper: 'STAY',
    AppKeys.submitUpper: 'SUBMIT',
    AppKeys.submittingForYou: 'Numi is submitting your test...',
    AppKeys.generatingAssessment: 'Let Numi create your test',
    AppKeys.aiChallenge: 'AI Challenge',
    AppKeys.questionProgress: 'QUESTION {current}/{total}',
    AppKeys.previousQuestionUpper: 'PREVIOUS',
    AppKeys.submittingUpper: 'SUBMITTING',
    AppKeys.excellentResultTitle: 'Excellent',
    AppKeys.goodResultTitle: 'Good',
    AppKeys.incompleteResultTitle: 'Not Completed',
    AppKeys.excellentResultMessage: '',
    AppKeys.generatingNewQuiz: 'Numi is creating a new test...',
    AppKeys.assessmentResultTitle: 'Result',
    AppKeys.scoreUpper: 'SCORE',
    AppKeys.numiAiReview: 'Numi AI review',
    AppKeys.defaultAiReview:
        'Your child did very well with addition. Keep going, and practice subtraction with regrouping a little more.',
    AppKeys.defaultAiReviewHighlight: 'addition',
    AppKeys.assessmentUpper: 'Review',
    AppKeys.practiceUpper: 'Practice',
    AppKeys.quizHasNoQuestions: 'Quiz has no questions.',
  },
};
