import 'app_keys.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      
      AppKeys.appName: 'EzMonex',

      
      AppKeys.navHome: 'Home',
      AppKeys.navSettings: 'Settings',
      AppKeys.navProfile: 'Profile',
      AppKeys.navActivity: 'Activity',
      AppKeys.navWallet: 'Wallet',
      AppKeys.navSendMoney: 'Send',
      AppKeys.navReceiveMoney: 'Receive Money',

      
      AppKeys.kycVerification: 'KYC Verification',
      AppKeys.kycNoData: "You haven't submitted any KYC data yet.",
      AppKeys.kycResidentialAddress: 'Residential Address Verification',
      AppKeys.kycResidentialSubtitle: 'Proof of residential address.',
      AppKeys.kycIdCard: 'ID Card Verification',
      AppKeys.kycIdCardSubtitle: 'Passport photograph and Valid ID card.',
      AppKeys.kycSourceFunds: 'Source of Funds Verification',
      AppKeys.kycSourceFundsSubtitle: 'Proof of funds',
      AppKeys.kycStatusProcessing: 'Processing',
      AppKeys.kycStatusIncomplete: 'Incomplete',
      AppKeys.back: 'Back',

      
      AppKeys.myAccount: 'My Account',
      AppKeys.userNotFound: 'User not found',
      AppKeys.chooseAvatar: 'Choose Avatar',
      AppKeys.fullName: 'Full Name',
      AppKeys.emailAddress: 'Email Address',
      AppKeys.phoneNumber: 'Phone Number',
      AppKeys.address: 'Address',
      AppKeys.loginWithBiometric: 'Login with Biometric',
      AppKeys.changePassword: 'Change Password',
      AppKeys.deleteAccount: 'Delete Account',

      
      AppKeys.addressSearch: 'Address Search',
      AppKeys.addressLabel: 'Address',
      AppKeys.addressHint: 'e.g., 20 Cooper Square',
      AppKeys.addressNotFound: '⚠️ Could not find the address.',
      AppKeys.save: 'Save',
      AppKeys.add: 'Add',
      AppKeys.update: 'Update',
      
      AppKeys.deleteAccountTitle: 'Delete Account',
      AppKeys.areYouSure: 'Are you absolutely sure?',
      AppKeys.deleteWarning:
          'This action is irreversible. All of your data, including your profile, settings, and history, will be permanently deleted.',
      AppKeys.deleteCannotUndo: 'This action cannot be undone.',
      AppKeys.yesDeleteAccount: 'Yes, Delete My Account',
      AppKeys.cancelTitle: 'Cancel',
      AppKeys.failedToDeleteAccount: 'Failed to delete account',
      
      AppKeys.changeAddress: 'Change Address',
      AppKeys.addressInfo:
          'Tap on any field to search for and select your new address. The fields will be filled in automatically.',
      AppKeys.streetAddress: 'Street Address',
      AppKeys.streetAddressHint: 'e.g., 20 Cooper Square',
      AppKeys.cityLabel: 'City',
      AppKeys.cityHint: 'e.g., Calabasas',
      AppKeys.stateLabel: 'State',
      AppKeys.stateHint: 'e.g., CA',
      AppKeys.zipCodeLabel: 'ZIP Code',
      AppKeys.zipCodeHint: 'e.g., 90210',

      
      AppKeys.changeEmail: 'Change Email',
      AppKeys.emailInfo:
          "Enter your new email address. We'll send a verification code to complete the change.",
      AppKeys.newEmailLabel: 'New Email',
      AppKeys.newEmailHint: 'Enter your new email',
      AppKeys.emailEmptyError: 'Email cannot be empty.',
      AppKeys.emailInvalidError: 'Please enter a valid email address.',

      
      AppKeys.changeName: 'Change Name',
      AppKeys.personalInformation: 'Personal Information',
      AppKeys.personalInfoSubtitle: 'Update your legal name as it appears on your ID',
      AppKeys.nameDetails: 'Name Details',
      AppKeys.firstNameLabel: 'First Name *',
      AppKeys.firstNameHint: 'e.g., JOHN',
      AppKeys.middleNameLabel: 'Middle Name (Optional)',
      AppKeys.middleNameHint: 'e.g., ALEXANDER',
      AppKeys.lastNameLabel: 'Last Name *',
      AppKeys.lastNameHint: 'e.g., DOE',
      AppKeys.nameMatchId:
          'Make sure your name matches exactly as it appears on your government-issued ID.',

      
      AppKeys.changePhoneNumber: 'Change Phone Number',
      AppKeys.phoneInfo:
          "Enter your new phone number. We'll send a verification code to complete the change.",

      
      AppKeys.error: 'ERROR',
      AppKeys.successUpdated: 'updated successfully',
      AppKeys.initializing: 'Initializing...',
      AppKeys.errorLoadingUser: 'Error loading user',
      AppKeys.checkYourInternet: 'Check your internet connection and try again.',
      AppKeys.processing: 'Processing',
      AppKeys.incomplete: 'Incomplete',
      AppKeys.errorLoadingUserColon: 'Error loading user:',

      
      AppKeys.languageTitle: 'Change Language',
      AppKeys.languageEnglish: 'English',
      AppKeys.languageVietnamese: 'Vietnamese',
      AppKeys.currentLanguage: 'Current Language',

      
      AppKeys.accountAndSecurity: 'Account & Security',
      AppKeys.receiver: 'Receiver',
      AppKeys.payment: 'Payment',
      AppKeys.adminDashboard: 'Admin Dashboard',
      AppKeys.demoDevOnly: 'Demo (Dev only)',
      AppKeys.language: 'Language',
      AppKeys.logout: 'Logout',
      AppKeys.confirmLogout: 'Confirm Logout',
      AppKeys.areYouSureLogout: 'Are you sure you want to logout?',
      AppKeys.yesLogout: 'Yes, Logout',

      
      AppKeys.somethingWentWrong: 'Something went wrong. Please try again later',
      AppKeys.pleaseRetryLater: 'Please try again later',
      AppKeys.couldNotFindMatches: "We couldn't find any matches.",

      
      AppKeys.passwordSecurityInfo: 'For your security, please use a strong password.',
      AppKeys.currentPasswordRequired: 'Current password is required!',
      AppKeys.currentPasswordHint: 'Current password',
      AppKeys.currentPassword: 'Current Password',
      AppKeys.newPassword: 'New Password',
      AppKeys.newPasswordHint: 'New Password',
      AppKeys.passwordRequired: 'Password is required!',
      AppKeys.passwordNotMeetRequirements: 'Password does not meet requirements!',
      AppKeys.confirmPassword: 'Confirm Password',
      AppKeys.confirmPasswordHint: 'Confirm Password',
      AppKeys.passwordConfirmRequired: 'Password confirm is required!',
      AppKeys.passwordNotMatching: 'The password confirmation is not matching.',
      AppKeys.passwordUpdatedSuccessfully: 'Password updated successfully!',
      AppKeys.passwordMustInclude: 'Password must include:',
      AppKeys.passwordCriteria1: 'At least 8 characters',
      AppKeys.passwordCriteria2: 'At least one uppercase letter',
      AppKeys.passwordCriteria3: 'At least one lowercase letter',
      AppKeys.passwordCriteria4: 'At least one number',
      AppKeys.passwordCriteria5: 'At least one special character: !@#\$%&*.-_',

      
      AppKeys.manageReceivers: 'Manage Receivers',
      AppKeys.search: 'Search',
      AppKeys.noResultsFor: 'No results for',
      AppKeys.tryCheckingSpelling: 'Try checking the spelling or add a new recipient.',
      AppKeys.noRecipients: 'No Recipients',
      AppKeys.addNewRecipientToStart: 'Add a new recipient to get started.',
      AppKeys.addNewRecipient: 'Add New Recipient',

      
      AppKeys.managePaymentMethodLabel: 'Manage Payments',
      AppKeys.noPaymentMethods: 'No Payment Methods',
      AppKeys.addPaymentMethodToStart: 'Add a payment method to get started.',
      AppKeys.addPaymentMethod: 'Add New Payment',
      AppKeys.failedToLoadPaymentMethods: 'Failed to load payment methods.',
      AppKeys.defaultPaymentMethod: 'Default',
      AppKeys.pending: 'Pending',
      AppKeys.verify: 'Verify',
      AppKeys.disable: 'Disable',
      AppKeys.enable: 'Enable',
      AppKeys.setAsDefault: 'Set as Default',
      AppKeys.paymentMethodUpdated: 'Payment method updated successfully',
      AppKeys.failedToUpdatePaymentMethod: 'Failed to update payment method',
      AppKeys.makeThisPrimary: 'Make this primary',
      AppKeys.deactivatePayment: 'Deactivate payment',
      AppKeys.activatePayment: 'Activate payment',
      AppKeys.completeVerification: 'Complete verification',

      
      AppKeys.login: 'Log In',
      AppKeys.signUp: 'Sign Up',
      AppKeys.contactUs: 'Contact Us',
      AppKeys.demo: 'Demo',
      AppKeys.checkAvailability: 'Check Availability',
      AppKeys.transactionFee: 'Fee Estimator',

      
      AppKeys.hiThere: 'Hi there! 👋',
      AppKeys.welcomeBack: 'Welcome back, Sign in to your account',
      AppKeys.username: 'Username',
      AppKeys.enterEmailOrPhone: 'Enter email or phone number',
      AppKeys.password: 'Password',
      AppKeys.enterYourPassword: 'Enter your password',
      AppKeys.rememberMe: 'Remember me',
      AppKeys.forgotPassword: 'Forgot Password?',
      AppKeys.dontHaveAccount: "Don't have an account?",
      AppKeys.loginFailed: 'Login Failed',
      AppKeys.incorrectCredentials: 'Incorrect username or password. Please try again.',
      AppKeys.tooManyAttempts: 'Too many attempts',
      AppKeys.accountLocked: 'Your account has been locked...',
      AppKeys.biometricFailed: 'Biometric Failed',
      AppKeys.couldNotAuthenticate: 'Could not authenticate.',
      AppKeys.serverProblem: 'Has problem with Server',
      AppKeys.checkInternetOrWait: 'Check your internet or wait for the server',
      AppKeys.updateBiometric: 'Update Biometric',
      AppKeys.updateBiometricMessage:
          'Your login details are different from the ones saved for biometrics. Do you want to use these new details for future biometric logins?',
      AppKeys.yesUpdate: 'Yes, Update',
      AppKeys.noThanks: 'No, Thanks',
      AppKeys.ok: 'OK',

      
      AppKeys.exchangeRate: 'Exchange Rate',
      AppKeys.swapCurrencies: 'Swap Currencies',
      AppKeys.sendMoneyDescription: 'Send money in USD and receive in USD or local currency',
      AppKeys.earnRewardMoney: 'Earn \$5 for each friend you refer!',
      AppKeys.referFriendsDescription:
          'Join 5 Million Happy Customers! Recommend Remitbee to Your friends and family.',
      AppKeys.earn: 'Earn',
      AppKeys.forEachFriendRefer: 'for each friend you refer!',

      
      AppKeys.securityVerification: 'Security Verification',
      AppKeys.additionalSecurityRequired:
          'Additional security verification is required. Complete the process by entering the One-Time-Password (OTP) verification code.',
      AppKeys.receiveOtpOptions: 'Receive OTP Options:',
      AppKeys.chooseOtpReceive: 'Choose where to receive your OTP verification code',
      AppKeys.next: 'Next',
      AppKeys.failedToVerify: 'Failed to verify!',

      
      AppKeys.activityTitle: 'Activity',
      AppKeys.searchTransactions: 'Search transactions',
      AppKeys.sortByAmount: 'Sort by amount',
      AppKeys.noTransactionsFound: 'No transactions match your search.',
      AppKeys.noTransactionsInPeriod: 'No activity in this period.',
      AppKeys.adjustDateRange: 'Try adjusting the date range.',
      AppKeys.transactionsWillAppearHere: 'Transactions you make will appear here.',
      AppKeys.tryAdjustingDateRange: 'Try adjusting the date range or create a new transfer.',
      AppKeys.createNewTransfer: 'Create New Transfer',
      AppKeys.refresh: 'Refresh',
      AppKeys.failedToLoadData: 'Failed to load data.',
      AppKeys.dateUnavailable: 'Date Unavailable',
      AppKeys.unknownRecipient: 'Unknown Recipient',
      AppKeys.clear: 'Clear',

      
      AppKeys.statusInit: 'Initialized',
      AppKeys.statusPendingKyc: 'Pending KYC',
      AppKeys.statusPendingCancel: 'Pending Cancel',
      AppKeys.statusCancelled: 'Cancelled',
      AppKeys.statusDeclined: 'Declined',
      AppKeys.statusProcessed: 'Processed',
      AppKeys.statusCompleted: 'Completed',
      AppKeys.statusNewEntry: 'New Entry',
      AppKeys.statusHold: 'On Hold',
      AppKeys.statusApproved: 'Approved',
      AppKeys.statusPaid: 'Paid',
      AppKeys.statusRefund: 'Refunded',
      AppKeys.statusPending: 'Pending',
      AppKeys.statusVoid: 'Void',
      AppKeys.statusBlock: 'Blocked',
      AppKeys.statusRequestToCancel: 'Cancel Requested',
      AppKeys.statusProcessCancelSuccess: 'Cancelled',
      AppKeys.statusSelfProcessCancelSuccess: 'Self Cancelled',
      AppKeys.statusUnknown: 'Unknown',
      AppKeys.statusCancelRefund: 'Cancel & Refund',
      AppKeys.statusApprovedXinfo: 'Approved (XInfo)',
      AppKeys.statusPaidXinfo: 'Paid (XInfo)',
      AppKeys.statusCancelAfterPaid: 'Cancelled After Paid',
      AppKeys.statusHoldBySender: 'Hold by Sender',
      AppKeys.statusGDue: 'GDue',

      
      AppKeys.transferSummary: 'Transfer Summary',
      AppKeys.financialDetails: 'Financial Details',
      AppKeys.recipientDetails: 'Recipient Details',
      AppKeys.sendAmount: 'Send Amount',
      AppKeys.recipientAmount: 'Recipient Amount',
      AppKeys.exchangeRateUsed: 'Exchange Rate Used',
      AppKeys.transferFee: 'Transfer Fee',
      AppKeys.totalAmount: 'Total Amount',
      AppKeys.transactionToken: 'Transaction Token',
      AppKeys.deliveryMethod: 'Delivery Method',
      AppKeys.status: 'Status',
      AppKeys.recipientName: 'Recipient Name',
      AppKeys.message: 'Message',
      AppKeys.noMessage: 'No message',
      AppKeys.editRecipient: 'Edit Recipient',
      AppKeys.editAmount: 'Edit Amount',
      AppKeys.editDeliveryMethod: 'Edit Delivery Method',
      AppKeys.cancelTransaction: 'Cancel',
      AppKeys.refundTransaction: 'Refund',
      AppKeys.contactSupport: 'Contact Support',
      AppKeys.completeKyc: 'Complete KYC',
      AppKeys.kycRequired: 'KYC Required',
      AppKeys.kycRequiredMessage:
          'Complete your KYC verification to proceed with this transaction.',
      AppKeys.copiedToClipboard: 'Copied to clipboard',
      AppKeys.cancelTransactionConfirm: 'Cancel Transaction',
      AppKeys.cancelTransactionMessage:
          'Are you sure you want to cancel this transaction? This action cannot be undone.',
      AppKeys.yesCancelTransaction: 'Yes, Cancel',
      AppKeys.transactionCancelled: 'Transaction cancelled successfully',
      AppKeys.failedToCancelTransaction: 'Failed to cancel transaction',
      AppKeys.adminActions: 'Admin Actions',
      AppKeys.transferSummaryDiscount: 'Discount',

      AppKeys.changeSendAmount: 'Change Send Amount',
      AppKeys.amount: 'Amount',
      AppKeys.send: 'Send',
      AppKeys.receive: 'Receive',
      AppKeys.pleaseSelectReceiveCurrency: 'Please select a receive currency.',
      AppKeys.noChangesDetected: 'No changes detected',
      AppKeys.noChangesDetectedMessage:
          'No changes detected. Please modify the amount or currency.',
      AppKeys.invalidAmountError: 'Invalid amount',
      AppKeys.updateSendAmount: 'Update Send Amount',
      AppKeys.currentAmount: 'Current Amount',
      AppKeys.newAmount: 'New Amount',
      AppKeys.enterNewAmount: 'Enter new amount',
      AppKeys.minimumAmount: 'Minimum amount',
      AppKeys.maximumAmount: 'Maximum amount',
      AppKeys.updateAmount: 'Update Amount',
      AppKeys.amountUpdated: 'Amount updated successfully',
      AppKeys.failedToUpdateAmount: 'Failed to update amount',
      AppKeys.invalidAmount: 'Invalid amount',
      AppKeys.amountTooLow: 'Amount too low',
      AppKeys.amountTooHigh: 'Amount too high',

      AppKeys.updateTransactionConfirm: 'Update Transaction Confirmation',
      AppKeys.confirmUpdate: 'Confirm Update',
      AppKeys.slideToConfirm: 'Slide to Confirm',
      AppKeys.transactionUpdateSuccessful: 'Transaction updated successfully',
      AppKeys.transactionUpdateFailed: 'Failed to update transaction',
      AppKeys.selectPaymentMethod: 'Select Payment Method',

      AppKeys.paymentMethodRequired: 'Payment method is required',
      AppKeys.invalidTransactionData: 'Invalid transaction data',
      AppKeys.calculatingFees: 'Calculating fees...',
      AppKeys.loadingPaymentMethods: 'Loading payment methods...',
      AppKeys.noDueAmount: 'No amount due',
      AppKeys.refundAmount: 'Refund Amount',

      
      AppKeys.sendMoneyTo: 'Send Money To',
      AppKeys.sendMoneyAmount: 'Amount',
      AppKeys.deliveryOptions: 'Delivery Options',
      AppKeys.deliveryCurrencyVndLowestFee: 'Delivery currency in VND for lowest fee.',
      AppKeys.chooseBankDepositInstant: 'Choose bank deposit for near instant delivery*',
      AppKeys.selectCountry: 'Select country',
      AppKeys.selectCurrency: 'Select Invalid account number',
      AppKeys.exchangeRateLabel: 'Exchange Rate',
      AppKeys.calculatingExchangeRate: 'Calculating exchange rate...',
      AppKeys.amountReachedLimit: 'Amount has reached the limit',
      AppKeys.invalidAmountEntered: 'Invalid amount entered',
      AppKeys.deliveryMethodRequired: 'Delivery option is required!',
      AppKeys.accountNumberLabel: 'Account Number',
      AppKeys.addNewAccountNumber: 'Add New Account Number',
      AppKeys.selectAccountNumber: 'Select Account Number',
      AppKeys.unknownRoute: 'Unknown Route',
      AppKeys.phoneNumberLabel: 'Phone number',
      AppKeys.enterPhoneNumber: 'Enter phone number',
      AppKeys.phoneNumberRequired: 'Phone number is required',
      AppKeys.invalidPhoneNumber: 'Invalid phone number',
      AppKeys.promoCodeLabel: 'Promo Code',
      AppKeys.applyPromoCode: 'Apply promo code',
      AppKeys.removePromoCode: 'Remove promo code',
      AppKeys.transferDetails: 'Transfer Details',
      AppKeys.feeBreakdown: 'Fee Breakdown',
      AppKeys.transactionFeeLabel: 'Transaction Fee',
      AppKeys.discountApplied: 'Discount Applied',

      AppKeys.senderProfile: 'Sender Profile',
      AppKeys.verifyProfileInformation: 'Verify your profile information',
      AppKeys.senderInformation: 'Sender Information',
      AppKeys.sender: 'Sender',
      AppKeys.senderProfileSaved: 'Sender profile saved successfully!',
      AppKeys.unableToSaveSenderProfile: '⚠️ Unable to Save Sender Profile',
      AppKeys.haventChangedAnything: "You haven't changed anything.",
      AppKeys.editPhoneEmailInSettings: '* Edit phone/email in Account settings',
      AppKeys.modify: 'Modify',
      AppKeys.notProvided: 'Not provided',

      
      AppKeys.recipientProfile: 'Recipient Profile',
      AppKeys.chooseRecipient: 'Choose Recipient',
      AppKeys.noRecipientSelected: 'No recipient selected',
      AppKeys.selectRecipientMessage:
          'Please select an existing recipient or add a new one to continue.',
      AppKeys.refreshing: 'Refreshing...',
      AppKeys.loadingRecipientInfo: 'Loading recipient information...',
      AppKeys.recipientInfoUpdated: 'Recipient information updated',
      AppKeys.district: 'District',
      AppKeys.provinceState: 'Province/City',
      AppKeys.country: 'Country',
      AppKeys.tryDifferentNameOrAdd: "Try a different name or add a new recipient.",
      AppKeys.noRecipientsFound: "No Recipients Found",
      AppKeys.noSavedRecipientsMessage: "You have no saved recipients yet. Please add one.",

      
      AppKeys.addRecipient: 'Add Recipient',
      AppKeys.updateRecipient: 'Update Recipient',
      AppKeys.recipientInformation: 'Recipient Information',
      AppKeys.contactInformation: 'Contact Information',
      AppKeys.addressInformation: 'Address Information',
      AppKeys.bankAccountInformation: 'Bank Account Information',
      AppKeys.city: 'City',
      AppKeys.state: 'State',
      AppKeys.selectState: 'Select State',
      AppKeys.selectDistrict: 'Select District',
      AppKeys.selectBankAccount: 'Select Bank Account',
      AppKeys.addBankAccount: 'Add Bank Account',
      AppKeys.firstNameRequired: 'First name is required',
      AppKeys.lastNameRequired: 'Last name is required',
      AppKeys.streetAddressRequired: 'Street address is required',
      AppKeys.receiverSaved: 'Recipient saved successfully',
      AppKeys.receiverUpdated: 'Recipient updated successfully',
      AppKeys.failedToSaveReceiver: 'Failed to save recipient',
      AppKeys.failedToUpdateReceiver: 'Failed to update recipient',
      AppKeys.checkingService: 'Checking service availability...',
      AppKeys.serviceNotAvailable: 'Service not available for this recipient',
      AppKeys.loadingBankAccounts: 'Loading bank accounts...',
      AppKeys.loadingDistricts: 'Loading districts...',
      AppKeys.optional: 'Optional',
      AppKeys.changeRecipient: 'Change Recipient',
      AppKeys.importantNameShouldMatchId: '*Important - Name should match official id',
      AppKeys.nameChangeNotAllowedForBankTransfer: 'Name change not allowed for Bank Transfer.',
      AppKeys.emailOptional: 'Email (Optional)',
      AppKeys.contact: 'Contact',
      AppKeys.searchRecipient: 'Search Recipient',
      AppKeys.recipient: 'Recipient',
      
      AppKeys.phoneCannotEmpty: 'Phone can not empty.',
      AppKeys.phoneEnter10Digits: 'Please enter enough 10 digits.',
      AppKeys.phoneInvalidNumber:
          'The phone number you provided appears to be invalid. Please check the number and try again.',

      AppKeys.addPaymentMethodTitle: 'Add Payment Method',
      AppKeys.updatePaymentMethodTitle: 'Update Payment Method',
      AppKeys.cardDetail: 'Card Details',
      AppKeys.cardNumber: 'Card Number',
      AppKeys.nameOnCard: 'Name on Card',
      AppKeys.expirationDate: 'Exp Date',
      AppKeys.cvv: 'CVC',
      AppKeys.billingAddress: 'Billing Address',
      AppKeys.setAsDefaultPayment: 'Set as default payment method',

      
      AppKeys.messageAndDataRatesMayApply:
          'I consent to receive SMS alerts from EZMonex for phone verification purposes.',
      AppKeys.consentToReceiveSms:
          '* Message & data rates may apply. You can reply STOP to unsubscribe at any time.',
      AppKeys.alreadyHaveAccount: 'Already have an account?',
      AppKeys.phoneVerification: 'Phone Verification',

      
      AppKeys.receiveAmount: 'Receive Amount',
      AppKeys.fee: 'Fee',
      AppKeys.total: 'Total',
      AppKeys.paid: 'Paid',
      AppKeys.newDueAmount: 'New Due Amount',
      AppKeys.haveAnPromoCode: 'Have a Promo Code?',
      AppKeys.promoDiscount: 'Promo Discount',
      AppKeys.securityCode: 'Security Code',
      AppKeys.messageToRecipient: 'Message To Recipient',
      AppKeys.required: 'Required',
      AppKeys.digits: 'Digits',
      AppKeys.chooseBank: 'Choose Bank',
      AppKeys.bankPickup: 'Bank Pickup',
      AppKeys.bankAccount: 'Bank Account',
      AppKeys.addNew: 'Add New',
      AppKeys.pay: 'Pay',
      AppKeys.chooseBankPickup: 'Choose Bank Pickup',
      AppKeys.footerCfpbLine1: 'This is CFPB line 1 abcderftgyh edrftgtth rfrrfff',
      AppKeys.footerCfpbLine2: 'This is CFPB line 2 sfsdfsfsfsdfs sfsdfsfsdfsdf slides',
      AppKeys.footerFxGainNotice: 'EZMONEX may have FX gain from this transaction.',
      AppKeys.footerDragToSendAgree: 'By Drag To Send, you agree to ',
      AppKeys.footerEzmonexAgreementPolicy: 'EZMONEX Agreement Policy',

      AppKeys.addBankAccountTitle: 'Add Bank Account',

      AppKeys.updateBankAccountTitle: 'Update Bank Account',
      AppKeys.bankAccountDetails: 'Bank Account Details',
      AppKeys.bankName: 'Bank Name',
      AppKeys.selectBank: 'Select Bank',
      AppKeys.bankRequired: 'Bank selection is required',
      AppKeys.accountNumber: 'Account Number',
      AppKeys.enterAccountNumber: 'Enter account number',
      AppKeys.accountNumberRequired: 'Account number is required',
      AppKeys.invalidAccountNumber: 'Invalid account number',
      AppKeys.accountHolderName: 'Account Holder Name',
      AppKeys.enterAccountHolderName: 'Enter account holder name',
      AppKeys.accountHolderNameRequired: 'Account holder name is required',
      AppKeys.currency: 'Currency',
      AppKeys.currencyRequired: 'Currency selection is required',
      AppKeys.bankAccountSaved: 'Bank account saved successfully',
      AppKeys.bankAccountUpdated: 'Bank account updated successfully',
      AppKeys.failedToSaveBankAccount: 'Failed to save bank account',
      AppKeys.failedToUpdateBankAccount: 'Failed to update bank account',
      AppKeys.loadingBanks: 'Loading banks...',
      AppKeys.nobanksAvailable: 'No banks available',
      AppKeys.searchBanks: 'Search banks',
      AppKeys.addBank: 'Add Bank',
      AppKeys.limit: 'Limit',

      
      AppKeys.confirmTitle: 'Confirm',
      AppKeys.areYouSureYouWantTo: 'Are you sure you want to',
      AppKeys.thisActionCannotBeUndone: 'This action cannot be undone.',
      AppKeys.yes: 'Yes',
      AppKeys.no: 'No',
      AppKeys.successTitle: 'Success',
      AppKeys.errorTitle: 'Error',
      AppKeys.warningTitle: 'Warning',
      AppKeys.infoTitle: 'Information',
      AppKeys.notice: 'Notice',
      AppKeys.confirmation: 'Confirmation',
      AppKeys.alert: 'Alert',
      AppKeys.done: 'Done',
      AppKeys.retry: 'Retry',
      AppKeys.continueAction: 'Continue',
      AppKeys.goBack: 'Go Back',
      AppKeys.verifyYouAreHuman: 'Verify You\'re Human',
      AppKeys.slideToVerify: 'Slide to verify',

      AppKeys.bankAlreadyExist: 'Bank Already Exists',
      AppKeys.cardAlreadyExist: 'Card Already Exists',
      AppKeys.refundAccount: 'TRefund Account',
      AppKeys.thisBankIsAlreadyInYourAccount: 'This bank account is already in your account',
      AppKeys.thisCardIsAlready: 'This card is already in your account',
      AppKeys.refundAreOnlyMadeTo: 'Refunds are only made to the account used for payment',
      AppKeys.thankYou: 'Thank You',
      AppKeys.thankYouForYourMessage:
          'Thank you for your message. We have received it and will respond as soon as possible.',
      AppKeys.enableBiometric: 'Enable Biometric',
      AppKeys.enableBiometricContent:
          'Enable Biometric to use Face ID/Fingerprint for faster logins next time?',
      AppKeys.enableBiometricConfirmLabel: 'Enable',
      AppKeys.enableBiometricCancelLabel: 'Not Now',
      AppKeys.changePhone: 'Change Phone',
      AppKeys.requestCancelTransaction: 'Request Cancel Transaction',
    },
    'vi': {
      
      AppKeys.appName: 'EzMonex',

      
      AppKeys.navHome: 'Trang chủ',
      AppKeys.navSettings: 'Cài đặt',
      AppKeys.navProfile: 'Hồ sơ',
      AppKeys.navActivity: 'Hoạt động',
      AppKeys.navWallet: 'Ví',
      AppKeys.navSendMoney: 'Gửi tiền',
      AppKeys.navReceiveMoney: 'Nhận tiền',

      
      AppKeys.kycVerification: 'Xác minh KYC',
      AppKeys.kycNoData: 'Bạn chưa gửi bất kỳ dữ liệu KYC nào.',
      AppKeys.kycResidentialAddress: 'Xác minh địa chỉ cư trú',
      AppKeys.kycResidentialSubtitle: 'Bằng chứng địa chỉ cư trú.',
      AppKeys.kycIdCard: 'Xác minh thẻ căn cước',
      AppKeys.kycIdCardSubtitle: 'Ảnh hộ chiếu và thẻ căn cước hợp lệ.',
      AppKeys.kycSourceFunds: 'Xác minh nguồn vốn',
      AppKeys.kycSourceFundsSubtitle: 'Bằng chứng nguồn vốn',
      AppKeys.kycStatusProcessing: 'Đang xử lý',
      AppKeys.kycStatusIncomplete: 'Chưa hoàn thành',
      AppKeys.back: 'Quay lại',

      
      AppKeys.myAccount: 'Tài khoản của tôi',
      AppKeys.userNotFound: 'Không tìm thấy người dùng',
      AppKeys.chooseAvatar: 'Chọn ảnh đại diện',
      AppKeys.fullName: 'Họ và tên',
      AppKeys.emailAddress: 'Địa chỉ email',
      AppKeys.phoneNumber: 'Số điện thoại',
      AppKeys.address: 'Địa chỉ',
      AppKeys.loginWithBiometric: 'Đăng nhập bằng sinh trắc học',
      AppKeys.changePassword: 'Đổi mật khẩu',
      AppKeys.deleteAccount: 'Xóa tài khoản',

      
      AppKeys.addressSearch: 'Tìm kiếm địa chỉ',
      AppKeys.addressLabel: 'Địa chỉ',
      AppKeys.addressHint: 'VD: 20 Cooper Square',
      AppKeys.addressNotFound: '⚠️ Không thể tìm thấy địa chỉ.',
      AppKeys.save: 'Lưu',

      
      AppKeys.deleteAccountTitle: 'Xóa tài khoản',
      AppKeys.areYouSure: 'Bạn có chắc chắn không?',
      AppKeys.deleteWarning:
          'Hành động này không thể hoàn tác. Tất cả dữ liệu của bạn, bao gồm hồ sơ, cài đặt và lịch sử, sẽ bị xóa vĩnh viễn.',
      AppKeys.deleteCannotUndo: 'Hành động này không thể hoàn tác.',
      AppKeys.yesDeleteAccount: 'Có, xóa tài khoản của tôi',
      AppKeys.cancelTitle: 'Hủy',
      AppKeys.failedToDeleteAccount: 'Không thể xóa tài khoản',

      
      AppKeys.changeAddress: 'Thay đổi địa chỉ',
      AppKeys.addressInfo:
          'Nhấn vào bất kỳ trường nào để tìm kiếm và chọn địa chỉ mới. Các trường sẽ được điền tự động.',
      AppKeys.streetAddress: 'Địa chỉ đường phố',
      AppKeys.streetAddressHint: 'VD: 20 Cooper Square',
      AppKeys.cityLabel: 'Thành phố',
      AppKeys.cityHint: 'VD: Hồ Chí Minh',
      AppKeys.stateLabel: 'Tỉnh/Thành',
      AppKeys.stateHint: 'VD: TP.HCM',
      AppKeys.zipCodeLabel: 'Mã bưu điện',
      AppKeys.zipCodeHint: 'VD: 70000',

      
      AppKeys.changeEmail: 'Thay đổi email',
      AppKeys.emailInfo:
          'Nhập địa chỉ email mới. Chúng tôi sẽ gửi mã xác minh để hoàn tất thay đổi.',
      AppKeys.newEmailLabel: 'Email mới',
      AppKeys.newEmailHint: 'Nhập email mới',
      AppKeys.emailEmptyError: 'Email không được để trống.',
      AppKeys.emailInvalidError: 'Vui lòng nhập địa chỉ email hợp lệ.',

      
      AppKeys.changeName: 'Thay đổi tên',
      AppKeys.personalInformation: 'Thông tin cá nhân',
      AppKeys.personalInfoSubtitle: 'Cập nhật tên pháp lý như trên giấy tờ tùy thân',
      AppKeys.nameDetails: 'Chi tiết tên',
      AppKeys.firstNameLabel: 'Họ *',
      AppKeys.firstNameHint: 'VD: NGUYỄN',
      AppKeys.middleNameLabel: 'Tên đệm (Tùy chọn)',
      AppKeys.middleNameHint: 'VD: VĂN',
      AppKeys.lastNameLabel: 'Tên *',
      AppKeys.lastNameHint: 'VD: AN',
      AppKeys.nameMatchId:
          'Đảm bảo tên của bạn khớp chính xác như trên giấy tờ tùy thân do chính phủ cấp.',

      
      AppKeys.changePhoneNumber: 'Thay đổi số điện thoại',
      AppKeys.phoneInfo:
          'Nhập số điện thoại mới. Chúng tôi sẽ gửi mã xác minh để hoàn tất thay đổi.',

      
      AppKeys.error: 'LỖI',
      AppKeys.successUpdated: 'đã cập nhật thành công',
      AppKeys.initializing: 'Đang khởi tạo...',
      AppKeys.errorLoadingUser: 'Lỗi tải người dùng',
      AppKeys.checkYourInternet: 'Kiểm tra kết nối internet và thử lại.',
      AppKeys.processing: 'Đang xử lý',
      AppKeys.incomplete: 'Chưa hoàn thành',
      AppKeys.errorLoadingUserColon: 'Lỗi tải người dùng:',

      
      AppKeys.languageTitle: 'Thay đổi ngôn ngữ',
      AppKeys.languageEnglish: 'Tiếng Anh',
      AppKeys.languageVietnamese: 'Tiếng Việt',
      AppKeys.currentLanguage: 'Ngôn ngữ hiện tại',

      
      AppKeys.accountAndSecurity: 'Tài khoản & Bảo mật',
      AppKeys.receiver: 'Người nhận',
      AppKeys.payment: 'Thanh toán',
      AppKeys.adminDashboard: 'Bảng điều khiển quản trị',
      AppKeys.demoDevOnly: 'Demo (Chỉ dành cho Dev)',
      AppKeys.language: 'Ngôn ngữ',
      AppKeys.logout: 'Đăng xuất',
      AppKeys.confirmLogout: 'Xác nhận đăng xuất',
      AppKeys.areYouSureLogout: 'Bạn có chắc chắn muốn đăng xuất không?',
      AppKeys.yesLogout: 'Có, đăng xuất',

      
      AppKeys.somethingWentWrong: 'Đã xảy ra lỗi. Vui lòng thử lại sau',
      AppKeys.pleaseRetryLater: 'Vui lòng thử lại sau',
      AppKeys.couldNotFindMatches: 'Chúng tôi không tìm thấy kết quả phù hợp.',

      
      AppKeys.passwordSecurityInfo: 'Để bảo mật, vui lòng sử dụng mật khẩu mạnh.',
      AppKeys.currentPasswordRequired: 'Mật khẩu hiện tại là bắt buộc!',
      AppKeys.currentPassword: 'Mật khẩu hiện tại',
      AppKeys.currentPasswordHint: 'Mật khẩu hiện tại',
      AppKeys.newPassword: 'Mật khẩu mới',
      AppKeys.newPasswordHint: 'Mật khẩu mới',
      AppKeys.passwordRequired: 'Mật khẩu là bắt buộc!',
      AppKeys.passwordNotMeetRequirements: 'Mật khẩu không đáp ứng yêu cầu!',
      AppKeys.confirmPassword: 'Xác nhận mật khẩu',
      AppKeys.confirmPasswordHint: 'Xác nhận mật khẩu',
      AppKeys.passwordConfirmRequired: 'Xác nhận mật khẩu là bắt buộc!',
      AppKeys.passwordNotMatching: 'Xác nhận mật khẩu không khớp.',
      AppKeys.passwordUpdatedSuccessfully: 'Cập nhật mật khẩu thành công!',
      AppKeys.passwordMustInclude: 'Mật khẩu phải bao gồm:',
      AppKeys.passwordCriteria1: 'Ít nhất 8 ký tự',
      AppKeys.passwordCriteria2: 'Ít nhất một chữ cái viết hoa',
      AppKeys.passwordCriteria3: 'Ít nhất một chữ cái viết thường',
      AppKeys.passwordCriteria4: 'Ít nhất một số',
      AppKeys.passwordCriteria5: 'Ít nhất một ký tự đặc biệt: !@#\$%&*.-_',

      
      AppKeys.manageReceivers: 'Quản lý người nhận',
      AppKeys.search: 'Tìm kiếm',
      AppKeys.noResultsFor: 'Không có kết quả cho',
      AppKeys.tryCheckingSpelling: 'Thử kiểm tra chính tả hoặc thêm người nhận mới.',
      AppKeys.noRecipients: 'Không có người nhận',
      AppKeys.addNewRecipientToStart: 'Thêm người nhận mới để bắt đầu.',
      AppKeys.addNewRecipient: 'Thêm người nhận mới',

      
      AppKeys.managePaymentMethodLabel: 'Quản lý thanh toán',
      AppKeys.noPaymentMethods: 'Không có phương thức thanh toán',
      AppKeys.addPaymentMethodToStart: 'Thêm phương thức thanh toán để bắt đầu.',
      AppKeys.addPaymentMethod: 'Thêm phương thức thanh toán',
      AppKeys.failedToLoadPaymentMethods: 'Không thể tải phương thức thanh toán.',
      AppKeys.defaultPaymentMethod: 'Mặc định',
      AppKeys.pending: 'Đang chờ',
      AppKeys.verify: 'Xác minh',
      AppKeys.disable: 'Vô hiệu hóa',
      AppKeys.enable: 'Kích hoạt',
      AppKeys.setAsDefault: 'Đặt làm mặc định',
      AppKeys.paymentMethodUpdated: 'Cập nhật phương thức thanh toán thành công',
      AppKeys.failedToUpdatePaymentMethod: 'Không thể cập nhật phương thức thanh toán',
      AppKeys.makeThisPrimary: 'Đặt làm chính',
      AppKeys.deactivatePayment: 'Tắt thanh toán',
      AppKeys.activatePayment: 'Bật thanh toán',
      AppKeys.completeVerification: 'Hoàn tất xác minh',

      
      AppKeys.login: 'Đăng nhập',
      AppKeys.signUp: 'Đăng ký',
      AppKeys.contactUs: 'Liên hệ',
      AppKeys.demo: 'Demo',
      AppKeys.checkAvailability: 'Kiểm tra khả dụng',
      AppKeys.transactionFee: 'Phí giao dịch',

      
      AppKeys.hiThere: 'Xin chào! 👋',
      AppKeys.welcomeBack: 'Chào mừng trở lại, đăng nhập vào tài khoản của bạn',
      AppKeys.username: 'Tên đăng nhập',
      AppKeys.enterEmailOrPhone: 'Nhập email hoặc số điện thoại',
      AppKeys.password: 'Mật khẩu',
      AppKeys.enterYourPassword: 'Nhập mật khẩu của bạn',
      AppKeys.rememberMe: 'Ghi nhớ đăng nhập',
      AppKeys.forgotPassword: 'Quên mật khẩu?',
      AppKeys.dontHaveAccount: 'Chưa có tài khoản?',
      AppKeys.loginFailed: 'Đăng nhập thất bại',
      AppKeys.incorrectCredentials: 'Tên đăng nhập hoặc mật khẩu không đúng. Vui lòng thử lại.',
      AppKeys.tooManyAttempts: 'Quá nhiều lần thử',
      AppKeys.accountLocked: 'Tài khoản của bạn đã bị khóa...',
      AppKeys.biometricFailed: 'Xác thực sinh trắc học thất bại',
      AppKeys.couldNotAuthenticate: 'Không thể xác thực.',
      AppKeys.serverProblem: 'Có vấn đề với máy chủ',
      AppKeys.checkInternetOrWait: 'Kiểm tra kết nối internet hoặc chờ máy chủ',
      AppKeys.updateBiometric: 'Cập nhật sinh trắc học',
      AppKeys.updateBiometricMessage:
          'Thông tin đăng nhập của bạn khác với thông tin đã lưu cho sinh trắc học. Bạn có muốn sử dụng thông tin mới này cho đăng nhập sinh trắc học trong tương lai không?',
      AppKeys.yesUpdate: 'Có, cập nhật',
      AppKeys.noThanks: 'Không, cảm ơn',
      AppKeys.ok: 'OK',

      
      AppKeys.exchangeRate: 'Tỷ giá',
      AppKeys.swapCurrencies: 'Hoán đổi tiền tệ',
      AppKeys.sendMoneyDescription: 'Gửi tiền bằng USD và nhận bằng USD hoặc tiền tệ địa phương',
      AppKeys.earnRewardMoney: 'Kiếm \$5 cho mỗi bạn bè bạn giới thiệu!',
      AppKeys.referFriendsDescription:
          'Tham gia cùng 5 triệu khách hàng hạnh phúc! Giới thiệu Remitbee cho bạn bè và gia đình.',
      AppKeys.earn: 'Kiếm',
      AppKeys.forEachFriendRefer: 'cho mỗi bạn bè bạn giới thiệu!',

      
      AppKeys.securityVerification: 'Xác minh bảo mật',
      AppKeys.additionalSecurityRequired:
          'Yêu cầu xác minh bảo mật bổ sung. Hoàn tất quy trình bằng cách nhập mã xác minh One-Time-Password (OTP).',
      AppKeys.receiveOtpOptions: 'Tùy chọn nhận OTP:',
      AppKeys.chooseOtpReceive: 'Chọn nơi nhận mã xác minh OTP của bạn',
      AppKeys.next: 'Tiếp theo',
      AppKeys.failedToVerify: 'Xác minh thất bại!',

      
      AppKeys.activityTitle: 'Hoạt động',
      AppKeys.searchTransactions: 'Tìm kiếm giao dịch',
      AppKeys.sortByAmount: 'Sắp xếp theo số tiền',
      AppKeys.noTransactionsFound: 'Không có giao dịch nào phù hợp với tìm kiếm của bạn.',
      AppKeys.noTransactionsInPeriod: 'Không có hoạt động trong khoảng thời gian này.',
      AppKeys.adjustDateRange: 'Thử điều chỉnh khoảng thời gian.',
      AppKeys.transactionsWillAppearHere: 'Các giao dịch bạn thực hiện sẽ xuất hiện ở đây.',
      AppKeys.tryAdjustingDateRange: 'Thử điều chỉnh khoảng thời gian hoặc tạo giao dịch mới.',
      AppKeys.createNewTransfer: 'Tạo giao dịch mới',
      AppKeys.refresh: 'Làm mới',
      AppKeys.failedToLoadData: 'Không thể tải dữ liệu.',
      AppKeys.dateUnavailable: 'Không có ngày',
      AppKeys.unknownRecipient: 'Người nhận không xác định',
      AppKeys.clear: 'Xóa',

      
      AppKeys.statusInit: 'Khởi tạo',
      AppKeys.statusPendingKyc: 'Chờ KYC',
      AppKeys.statusPendingCancel: 'Chờ hủy',
      AppKeys.statusCancelled: 'Đã hủy',
      AppKeys.statusDeclined: 'Bị từ chối',
      AppKeys.statusProcessed: 'Đã xử lý',
      AppKeys.statusCompleted: 'Hoàn thành',
      AppKeys.statusNewEntry: 'Mới tạo',
      AppKeys.statusHold: 'Tạm giữ',
      AppKeys.statusApproved: 'Đã duyệt',
      AppKeys.statusPaid: 'Đã thanh toán',
      AppKeys.statusRefund: 'Đã hoàn tiền',
      AppKeys.statusPending: 'Đang chờ',
      AppKeys.statusVoid: 'Hủy bỏ',
      AppKeys.statusBlock: 'Bị chặn',
      AppKeys.statusRequestToCancel: 'Yêu cầu hủy',
      AppKeys.statusProcessCancelSuccess: 'Đã hủy',
      AppKeys.statusSelfProcessCancelSuccess: 'Tự hủy',
      AppKeys.statusUnknown: 'Không xác định',
      AppKeys.statusCancelRefund: 'Hủy & Hoàn tiền',
      AppKeys.statusApprovedXinfo: 'Đã duyệt (XInfo)',
      AppKeys.statusPaidXinfo: 'Đã thanh toán (XInfo)',
      AppKeys.statusCancelAfterPaid: 'Đã hủy sau khi thanh toán',
      AppKeys.statusHoldBySender: 'Tạm giữ bởi người gửi',
      AppKeys.statusGDue: 'GDue',

      
      AppKeys.transferSummary: 'Tóm tắt giao dịch',
      AppKeys.financialDetails: 'Chi tiết tài chính',
      AppKeys.recipientDetails: 'Thông tin người nhận',
      AppKeys.sendAmount: 'Số tiền gửi',
      AppKeys.recipientAmount: 'Số tiền nhận',
      AppKeys.exchangeRateUsed: 'Tỷ giá sử dụng',
      AppKeys.transferFee: 'Phí chuyển tiền',
      AppKeys.totalAmount: 'Tổng số tiền',
      AppKeys.transactionToken: 'Mã giao dịch',
      AppKeys.deliveryMethod: 'Phương thức giao hàng',
      AppKeys.status: 'Trạng thái',
      AppKeys.recipientName: 'Tên người nhận',
      AppKeys.message: 'Tin nhắn',
      AppKeys.noMessage: 'Không có tin nhắn',
      AppKeys.editRecipient: 'Sửa người nhận',
      AppKeys.editAmount: 'Sửa số tiền',
      AppKeys.editDeliveryMethod: 'Sửa phương thức giao hàng',
      AppKeys.cancelTransaction: 'Hủy giao dịch',
      AppKeys.refundTransaction: 'Hoàn tiền',
      AppKeys.contactSupport: 'Liên hệ hỗ trợ',
      AppKeys.completeKyc: 'Hoàn thành KYC',
      AppKeys.kycRequired: 'Yêu cầu KYC',
      AppKeys.kycRequiredMessage: 'Hoàn thành xác minh KYC để tiến hành giao dịch này.',
      AppKeys.copiedToClipboard: 'Đã sao chép vào clipboard',
      AppKeys.cancelTransactionConfirm: 'Hủy giao dịch',
      AppKeys.cancelTransactionMessage:
          'Bạn có chắc chắn muốn hủy giao dịch này? Hành động này không thể hoàn tác.',
      AppKeys.yesCancelTransaction: 'Có, hủy',
      AppKeys.transactionCancelled: 'Hủy giao dịch thành công',
      AppKeys.failedToCancelTransaction: 'Không thể hủy giao dịch',
      AppKeys.adminActions: 'Hành động quản trị',
      AppKeys.transferSummaryDiscount: 'Giảm giá',

      AppKeys.changeSendAmount: 'Thay đổi số tiền gửi',
      AppKeys.amount: 'Số tiền',
      AppKeys.send: 'Gửi',
      AppKeys.receive: 'Nhận',
      AppKeys.pleaseSelectReceiveCurrency: 'Vui lòng chọn loại tiền nhận.',
      AppKeys.noChangesDetected: 'Không có thay đổi',
      AppKeys.noChangesDetectedMessage:
          'Không có thay đổi nào được phát hiện. Vui lòng thay đổi số tiền hoặc loại tiền.',
      AppKeys.invalidAmountError: 'Số tiền không hợp lệ',
      AppKeys.updateSendAmount: 'Cập nhật số tiền gửi',
      AppKeys.currentAmount: 'Số tiền hiện tại',
      AppKeys.newAmount: 'Số tiền mới',
      AppKeys.enterNewAmount: 'Nhập số tiền mới',
      AppKeys.minimumAmount: 'Số tiền tối thiểu',
      AppKeys.maximumAmount: 'Số tiền tối đa',
      AppKeys.updateAmount: 'Cập nhật số tiền',
      AppKeys.amountUpdated: 'Cập nhật số tiền thành công',
      AppKeys.failedToUpdateAmount: 'Không thể cập nhật số tiền',
      AppKeys.invalidAmount: 'Số tiền không hợp lệ',
      AppKeys.amountTooLow: 'Số tiền quá thấp',
      AppKeys.amountTooHigh: 'Số tiền quá cao',

      AppKeys.updateTransactionConfirm: 'Xác nhận cập nhật giao dịch',
      AppKeys.confirmUpdate: 'Xác nhận cập nhật',
      AppKeys.slideToConfirm: 'Trượt để xác nhận',
      AppKeys.transactionUpdateSuccessful: 'Cập nhật giao dịch thành công',
      AppKeys.transactionUpdateFailed: 'Không thể cập nhật giao dịch',
      AppKeys.selectPaymentMethod: 'Chọn phương thức thanh toán',
      AppKeys.paymentMethodRequired: 'Yêu cầu phương thức thanh toán',
      AppKeys.invalidTransactionData: 'Dữ liệu giao dịch không hợp lệ',
      AppKeys.calculatingFees: 'Đang tính phí...',
      AppKeys.loadingPaymentMethods: 'Đang tải phương thức thanh toán...',
      AppKeys.noDueAmount: 'Không có số tiền cần thanh toán',
      AppKeys.refundAmount: 'Số tiền hoàn lại',

      
      AppKeys.sendMoneyTo: 'Gửi tiền đến',
      AppKeys.sendMoneyAmount: 'Số tiền',
      AppKeys.deliveryOptions: 'Tùy chọn giao hàng',
      AppKeys.deliveryCurrencyVndLowestFee: 'Giao tiền bằng VND để có phí thấp nhất.',
      AppKeys.chooseBankDepositInstant: 'Chọn gửi ngân hàng để giao hàng gần như ngay lập tức*',
      AppKeys.selectCountry: 'Chọn quốc gia',
      AppKeys.selectCurrency: 'Chọn loại tiền',
      AppKeys.exchangeRateLabel: 'Tỷ giá hối đoái',
      AppKeys.calculatingExchangeRate: 'Đang tính tỷ giá...',
      AppKeys.amountReachedLimit: 'Số tiền đã đạt giới hạn',
      AppKeys.invalidAmountEntered: 'Số tiền không hợp lệ',
      AppKeys.deliveryMethodRequired: 'Tùy chọn giao hàng là bắt buộc!',
      AppKeys.accountNumberLabel: 'Số tài khoản',
      AppKeys.addNewAccountNumber: 'Thêm số tài khoản mới',
      AppKeys.selectAccountNumber: 'Chọn số tài khoản',
      AppKeys.unknownRoute: 'Tuyến đường không xác định',
      AppKeys.phoneNumberLabel: 'Số điện thoại',
      AppKeys.enterPhoneNumber: 'Nhập số điện thoại',
      AppKeys.phoneNumberRequired: 'Số điện thoại là bắt buộc',
      AppKeys.invalidPhoneNumber: 'Số điện thoại không hợp lệ',
      AppKeys.promoCodeLabel: 'Mã khuyến mãi',
      AppKeys.applyPromoCode: 'Áp dụng mã khuyến mãi',
      AppKeys.removePromoCode: 'Xóa mã khuyến mãi',
      AppKeys.transferDetails: 'Chi tiết chuyển tiền',
      AppKeys.feeBreakdown: 'Chi tiết phí',
      AppKeys.transactionFeeLabel: 'Phí giao dịch',
      AppKeys.discountApplied: 'Đã áp dụng giảm giá',

      
      AppKeys.senderProfile: 'Hồ sơ người gửi',
      AppKeys.verifyProfileInformation: 'Xác minh thông tin hồ sơ của bạn',
      AppKeys.senderInformation: 'Thông tin người gửi',
      AppKeys.sender: 'Người gửi',
      AppKeys.senderProfileSaved: 'Lưu hồ sơ người gửi thành công!',
      AppKeys.unableToSaveSenderProfile: '⚠️ Không thể lưu hồ sơ người gửi',
      AppKeys.haventChangedAnything: 'Bạn chưa thay đổi gì cả.',
      AppKeys.editPhoneEmailInSettings: '* Chỉnh sửa số điện thoại/email trong Cài đặt tài khoản',
      AppKeys.modify: 'Chỉnh sửa',
      AppKeys.notProvided: 'Chưa cung cấp',

      
      AppKeys.recipientProfile: 'Hồ Sơ Người Nhận',
      AppKeys.chooseRecipient: 'Chọn Người Nhận',
      AppKeys.noRecipientSelected: 'Chưa chọn người nhận',
      AppKeys.selectRecipientMessage: 'Vui lòng chọn người nhận hiện có hoặc thêm mới để tiếp tục.',
      AppKeys.refreshing: 'Đang làm mới...',
      AppKeys.loadingRecipientInfo: 'Đang tải thông tin người nhận...',
      AppKeys.recipientInfoUpdated: 'Đã cập nhật thông tin người nhận',
      AppKeys.district: 'Quận/Huyện',
      AppKeys.provinceState: 'Tỉnh/Thành',
      AppKeys.country: 'Quốc gia',
      AppKeys.tryDifferentNameOrAdd: "Thử tên khác hoặc thêm người nhận mới.",
      AppKeys.noRecipientsFound: "Không tìm thấy người nhận",
      AppKeys.noSavedRecipientsMessage:
          "Bạn chưa có người nhận nào được lưu. Vui lòng thêm một người.",

      
      AppKeys.addRecipient: 'Thêm Người Nhận',
      AppKeys.updateRecipient: 'Cập Nhật Người Nhận',
      AppKeys.recipientInformation: 'Thông Tin Người Nhận',
      AppKeys.contactInformation: 'Thông Tin Liên Hệ',
      AppKeys.addressInformation: 'Thông Tin Địa Chỉ',
      AppKeys.bankAccountInformation: 'Thông Tin Tài Khoản Ngân Hàng',
      AppKeys.city: 'Thành Phố',
      AppKeys.state: 'Tỉnh/Thành',
      AppKeys.selectState: 'Chọn Tỉnh/Thành',
      AppKeys.selectDistrict: 'Chọn Quận/Huyện',
      AppKeys.selectBankAccount: 'Chọn Tài Khoản Ngân Hàng',
      AppKeys.addBankAccount: 'Thêm Tài Khoản Ngân Hàng',
      AppKeys.firstNameRequired: 'Họ là bắt buộc',
      AppKeys.lastNameRequired: 'Tên là bắt buộc',
      AppKeys.streetAddressRequired: 'Địa chỉ đường phố là bắt buộc',
      AppKeys.receiverSaved: 'Lưu người nhận thành công',
      AppKeys.receiverUpdated: 'Cập nhật người nhận thành công',
      AppKeys.failedToSaveReceiver: 'Không thể lưu người nhận',
      AppKeys.failedToUpdateReceiver: 'Không thể cập nhật người nhận',
      AppKeys.checkingService: 'Đang kiểm tra tình trạng dịch vụ...',
      AppKeys.serviceNotAvailable: 'Dịch vụ không khả dụng cho người nhận này',
      AppKeys.loadingBankAccounts: 'Đang tải tài khoản ngân hàng...',
      AppKeys.loadingDistricts: 'Đang tải quận/huyện...',
      AppKeys.optional: 'Tùy chọn',
      AppKeys.changeRecipient: 'Thay đổi người nhận',
      AppKeys.importantNameShouldMatchId:
          '*Quan trọng: Tên của người nhận nên khớp với giấy tờ tùy thân.',
      AppKeys.nameChangeNotAllowedForBankTransfer:
          'Tên người nhận không thể thay đổi đối với chuyển khoản ngân hàng.',
      AppKeys.contact: 'Liên hệ',
      AppKeys.searchRecipient: 'Tìm kiếm người nhận',
      AppKeys.recipient: 'Người nhận',
      
      AppKeys.phoneCannotEmpty: 'Số điện thoại không được để trống',
      AppKeys.phoneEnter10Digits: 'Vui lòng nhập số điện thoại gồm 10 chữ số',
      AppKeys.phoneInvalidNumber:
          'Số điện thoại bạn cung cấp có vẻ không hợp lệ. Vui lòng kiểm tra lại số và thử lại.',
      AppKeys.emailOptional: 'Email (Tùy chọn)',

      
      AppKeys.addPaymentMethodTitle: 'Thêm Phương Thức Thanh Toán',
      AppKeys.updatePaymentMethodTitle: 'Cập Nhật Phương Thức Thanh Toán',
      AppKeys.cardDetail: 'Chi Tiết',
      AppKeys.cardNumber: 'Số Thẻ',
      AppKeys.nameOnCard: 'Tên Trên Thẻ',
      AppKeys.expirationDate: 'Ngày Hết Hạn',
      AppKeys.cvv: 'CVV',
      AppKeys.billingAddress: 'Địa Chỉ Thanh Toán',
      AppKeys.setAsDefaultPayment: 'Đặt Là Phương Thức Mặc Định',
      AppKeys.add: 'Thêm',
      AppKeys.update: 'Cập Nhật',

      
      AppKeys.messageAndDataRatesMayApply:
          'Tôi đồng ý nhận cảnh báo SMS từ EZMonex cho mục đích xác minh điện thoại.',
      AppKeys.consentToReceiveSms:
          '* Có thể áp dụng phí tin nhắn và dữ liệu. Bạn có thể trả lời STOP để hủy đăng ký bất cứ lúc nào.',
      AppKeys.alreadyHaveAccount: 'Đã có tài khoản?',
      AppKeys.phoneVerification: 'Xác minh điện thoại',

      
      AppKeys.receiveAmount: 'Số tiền nhận',
      AppKeys.fee: 'Phí',
      AppKeys.total: 'Tổng',
      AppKeys.paid: 'Đã thanh toán',
      AppKeys.newDueAmount: 'Số tiền mới phải trả',
      AppKeys.haveAnPromoCode: 'Có mã khuyến mãi?',
      AppKeys.promoDiscount: 'Giảm giá',
      AppKeys.securityCode: 'Mã bảo mật',
      AppKeys.messageToRecipient: 'Tin nhắn cho người nhận',
      AppKeys.required: 'Bắt buộc',
      AppKeys.digits: 'Chữ số',
      AppKeys.chooseBank: 'Chọn Ngân Hàng',
      AppKeys.bankPickup: 'Nhận Tại Ngân Hàng',
      AppKeys.bankAccount: 'Tài Khoản',
      AppKeys.addNew: 'Thêm Mới',
      AppKeys.pay: 'Thanh Toán',
      AppKeys.chooseBankPickup: ' Chọn Ngân Hàng Nhận',
      AppKeys.footerCfpbLine1: 'Đây là dòng CFPB 1 abcderftgyh edrftgtth rfrrfff',
      AppKeys.footerCfpbLine2: 'Đây là dòng CFPB 2 sfsdfsfsfsdfs sfsdfsfsdfsdf slides',
      AppKeys.footerFxGainNotice: 'EZMONEX có thể có lợi nhuận FX từ giao dịch này.',
      AppKeys.footerDragToSendAgree: 'Bằng cách Kéo Để Gửi, bạn đồng ý với ',
      AppKeys.footerEzmonexAgreementPolicy: 'Chính Sách Thỏa Thuận EZMONEX',

      AppKeys.addBankAccountTitle: 'Thêm Tài Khoản Ngân Hàng',
      AppKeys.updateBankAccountTitle: 'Cập Nhật Tài Khoản Ngân Hàng',
      AppKeys.bankAccountDetails: 'Chi Tiết Tài Khoản Ngân Hàng',
      AppKeys.bankName: 'Tên Ngân Hàng',
      AppKeys.selectBank: 'Chọn Ngân Hàng',
      AppKeys.bankRequired: 'Bắt buộc chọn ngân hàng',
      AppKeys.accountNumber: 'Số Tài Khoản',
      AppKeys.enterAccountNumber: 'Nhập số tài khoản',
      AppKeys.accountNumberRequired: 'Số tài khoản là bắt buộc',
      AppKeys.invalidAccountNumber: 'Số tài khoản không hợp lệ',
      AppKeys.accountHolderName: 'Tên Chủ Tài Khoản',
      AppKeys.enterAccountHolderName: 'Nhập tên chủ tài khoản',
      AppKeys.accountHolderNameRequired: 'Tên chủ tài khoản là bắt buộc',
      AppKeys.currency: 'Loại Tiền',
      AppKeys.currencyRequired: 'Bắt buộc chọn loại tiền',
      AppKeys.bankAccountSaved: 'Lưu tài khoản ngân hàng thành công',
      AppKeys.bankAccountUpdated: 'Cập nhật tài khoản ngân hàng thành công',
      AppKeys.failedToSaveBankAccount: 'Không thể lưu tài khoản ngân hàng',
      AppKeys.failedToUpdateBankAccount: 'Không thể cập nhật tài khoản ngân hàng',
      AppKeys.loadingBanks: 'Đang tải ngân hàng...',
      AppKeys.nobanksAvailable: 'Không có ngân hàng nào',
      AppKeys.searchBanks: 'Tìm kiếm ngân hàng',
      AppKeys.addBank: 'Thêm',
      AppKeys.limit: 'Giới hạn',
      AppKeys.verifyYouAreHuman: 'Xác Minh Bạn Không Phải Robot',
      AppKeys.slideToVerify: 'Trượt để xác minh',

      AppKeys.bankAlreadyExist: 'Ngân hàng đã tồn tại',
      AppKeys.cardAlreadyExist: 'Thẻ đã tồn tại',
      AppKeys.refundAccount: 'Tài khoản hoàn tiền',
      AppKeys.thisBankIsAlreadyInYourAccount: 'Ngân hàng này đã có trong tài khoản của bạn',
      AppKeys.thisCardIsAlready: 'Thẻ này đã có trong tài khoản của bạn',
      AppKeys.refundAreOnlyMadeTo: 'Tiền hoàn lại chỉ chuyển về tài khoản thanh toán',
      AppKeys.thankYou: 'Cảm ơn',
      AppKeys.thankYouForYourMessage:
          'Cảm ơn bạn đã gửi tin nhắn. Chúng tôi đã nhận được và sẽ phản hồi trong thời gian sớm nhất.',
      AppKeys.enableBiometric: 'Kích Hoạt Sinh Trắc Học',
      AppKeys.enableBiometricContent:
          'Kích hoạt Sinh Trắc Học để sử dụng Face ID/Vân Tay cho đăng nhập nhanh hơn lần sau?',
      AppKeys.enableBiometricConfirmLabel: 'Kích Hoạt',
      AppKeys.enableBiometricCancelLabel: 'Không Phải Lúc Này',
      AppKeys.confirmTitle: 'Xác Nhận',
      AppKeys.changePhone: 'Thay Đổi Số Điện Thoại',
      AppKeys.requestCancelTransaction: 'Yêu Cầu Hủy Giao Dịch',
    },
  };

  static Map<String, String> getAll(String languageCode) {
    return _localizedValues[languageCode] ?? _localizedValues['en'] ?? {};
  }
}
