import 'app_keys.dart';
import 'app_language.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      AppKeys.appName: 'NUMI',
      AppKeys.loading: 'Đang tải...',
      AppKeys.close: 'Đóng',
      AppKeys.cancel: 'Hủy',
      AppKeys.save: 'Lưu',
      AppKeys.retry: 'Thử lại',
      AppKeys.retryUpper: 'THỬ LẠI',
      AppKeys.accept: 'Chấp nhận',
      AppKeys.reject: 'Từ chối',
      AppKeys.delete: 'Xóa',
      AppKeys.update: 'Cập nhật',
      AppKeys.add: 'Thêm',
      AppKeys.back: 'Quay lại',
      AppKeys.skipUpper: 'BỎ QUA',
      AppKeys.continueUpper: 'TIẾP TỤC',
      AppKeys.language: 'Ngôn ngữ',
      AppKeys.languageTitle: 'Ngôn Ngữ',
      AppKeys.languageMenuSubtitle: 'Đổi ngôn ngữ hiển thị',
      AppKeys.languageVietnamese: 'Tiếng Việt',
      AppKeys.languageEnglish: 'English',
      AppKeys.welcomeTitlePrefix: 'Học Toán cùng\n',
      AppKeys.welcomeTitleN: 'NUMI',
      AppKeys.welcomeSubtitlePrefix: 'Hãy cùng Numi',
      AppKeys.welcomeSubtitle: 'trở thành "phù thủy" tính toán nhé!',
      AppKeys.start: 'BẮT ĐẦU',
      AppKeys.phoneLoginTitle: 'Số điện thoại',
      AppKeys.phoneLoginBrandName: 'NUMINUMI',
      AppKeys.phoneLoginSubtitle:
          'Nhập số điện thoại để\nđăng ký hoặc đăng nhập !',
      AppKeys.phoneNumberUpper: 'SỐ ĐIỆN THOẠI',
      AppKeys.phoneHint: 'Nhập số điện thoại',
      AppKeys.chooseCountry: 'Chọn quốc gia',
      AppKeys.continueLabel: 'Tiếp tục',
      AppKeys.creatingAccount: 'Đang tạo tài khoản...',
      AppKeys.checking: 'Đang kiểm tra...',
      AppKeys.phoneRequired: 'Vui lòng nhập số điện thoại.',
      AppKeys.invalidPhone: 'Số điện thoại chưa hợp lệ.',
      AppKeys.phoneTooShort: 'Số điện thoại chưa đủ ký tự.',
      AppKeys.restoringSession: 'Đang kiểm tra phiên đăng nhập...',
      AppKeys.newAccountPrompt: 'Đây là tài khoản MỚI. Tiếp tục đăng ký?',
      AppKeys.signup: 'Đăng ký',
      AppKeys.login: 'Đăng nhập',
      AppKeys.loginWithPin: 'Đăng nhập với PIN',
      AppKeys.otpWithin30Seconds: 'Bạn sẽ nhận được mã trong vòng 30 giây',
      AppKeys.otpTitle: 'MÃ XÁC NHẬN',
      AppKeys.otpSentMessage: 'Mã OTP vừa gửi: {code}',
      AppKeys.otpConfirming: 'Đang xác thực...',
      AppKeys.otpConfirm: 'Gửi OTP',
      AppKeys.resendOtp: 'Gửi lại mã',
      AppKeys.resendOtpAfter: 'Gửi lại mã sau {seconds} giây',
      AppKeys.signupNameHint: 'Nhập tên người dùng',
      AppKeys.signupEmailHint: 'example@numinumi.com',
      AppKeys.signupNameLabel: 'Tên người dùng',
      AppKeys.signupEmailLabel: 'Email',
      AppKeys.signupRoleLabel: 'Bạn là',
      AppKeys.signupRoleStudent: 'Học Sinh',
      AppKeys.signupRoleParent: 'Phụ huynh',
      AppKeys.signupRoleTeacher: 'Giáo viên',
      AppKeys.signupEmailDescription:
          'Nhập email để theo dõi kết quả kiểm tra và hành\ntrình học tập của bé',
      AppKeys.avatarUpper: 'ẢNH ĐẠI DIỆN',
      AppKeys.chooseAvatar: 'Chọn ảnh đại diện',
      AppKeys.signingUp: 'Đang đăng ký...',
      AppKeys.navHome: 'HOME',
      AppKeys.navReview: 'ÔN TẬP',
      AppKeys.navHistory: 'LỊCH SỬ',
      AppKeys.navReport: 'BÁO CÁO',
      AppKeys.navSettings: 'CÀI ĐẶT',
      AppKeys.student: 'HỌC SINH',
      AppKeys.assessment: 'KIỂM TRA',
      AppKeys.assessmentDescription:
          'Cùng AI kiểm tra khả năng toán học\nvượt trội riêng bạn.',
      AppKeys.startNow: 'Bắt đầu ngay',
      AppKeys.practice: 'Luyện tập',
      AppKeys.yourAchievement: 'Thành tích của bạn',
      AppKeys.studentHomework: 'Bài tập',
      AppKeys.studentClassroom: 'Lớp học',
      AppKeys.studentNoHomeworkTitle: 'Chưa có bài tập',
      AppKeys.studentNoHomeworkMessage:
          'Bài tập được giao sẽ hiển thị tại đây.',
      AppKeys.studentNoClassroomsTitle: 'Chưa tham gia lớp học',
      AppKeys.studentNoClassroomsMessage:
          'Tham gia lớp để nhận bài tập và theo dõi tiến độ.',
      AppKeys.studentJoinNewClassroom: 'Tham gia lớp mới',
      AppKeys.studentJoinClassroomSoon: 'Tính năng tham gia lớp sẽ sớm có mặt.',
      AppKeys.studentClassroomLoadFailed: 'Tải danh sách lớp học thất bại.',
      AppKeys.studentMissingProfileId: 'Hồ sơ học sinh thiếu profile_id.',
      AppKeys.studentFindClassTitle: 'Tìm Lớp Học',
      AppKeys.studentClassCodeHint: 'Nhập mã lớp',
      AppKeys.studentSearchClass: 'Tìm kiếm lớp học',
      AppKeys.studentSearchResults: 'Kết quả tìm kiếm',
      AppKeys.studentDefaultSchoolFilter: 'Trường Lưu Tấn Phát',
      AppKeys.studentGradeFilter: 'Lớp {grade}',
      AppKeys.studentClassSearchFailed: 'Tìm kiếm lớp học thất bại.',
      AppKeys.studentClassSearchLoading: 'Đang tìm lớp phù hợp...',
      AppKeys.studentClassSearchRetry: 'Thử lại bằng mã hoặc tên lớp khác.',
      AppKeys.studentNoClassSearchResults: 'Không tìm thấy lớp học',
      AppKeys.studentNoClassSearchResultsMessage:
          'Kiểm tra lại mã lớp hoặc tên lớp rồi thử lại.',
      AppKeys.studentEnterClassCodeTitle: 'Nhập mã hoặc tên lớp',
      AppKeys.studentEnterClassCodeMessage:
          'Kết quả lớp học phù hợp sẽ hiển thị tại đây.',
      AppKeys.studentClassMissingCode: 'Lớp học này chưa có mã tham gia.',
      AppKeys.studentJoinClassSuccess: 'Đã gửi yêu cầu tham gia lớp.',
      AppKeys.studentJoinClassFailed: 'Không thể gửi yêu cầu tham gia lớp.',
      AppKeys.studentAlreadyJoinedClass: 'Bạn đã tham gia lớp học này.',
      AppKeys.studentClassJoinRequestPending:
          'Lớp học này đã có lời mời hoặc yêu cầu đang chờ.',
      AppKeys.studentClassCodeLabel: 'CODE: {code}',
      AppKeys.studentClassRelationshipMember: 'ĐÃ THAM GIA',
      AppKeys.studentClassRelationshipPendingInvitation: 'ĐÃ ĐƯỢC MỜI',
      AppKeys.studentClassRelationshipPendingRequest: 'ĐANG CHỜ',
      AppKeys.studentClassRelationshipNone: 'CHƯA THAM GIA',
      AppKeys.studentClassInvitations: 'Lời mời lớp học',
      AppKeys.studentViewAllInvitations: 'Xem tất cả ({count})',
      AppKeys.studentViewAllClassrooms: 'Xem tất cả ({count})',
      AppKeys.studentNoInvitationsTitle: 'Chưa có lời mời',
      AppKeys.studentNoInvitationsMessage:
          'Lời mời lớp học mới sẽ xuất hiện tại đây.',
      AppKeys.parentNoStudentTitle: 'Chưa có hồ sơ con',
      AppKeys.parentNoStudentMessage:
          'Bạn cần tạo hồ sơ cho con trước khi tham gia lớp học.',
      AppKeys.parentCreateStudentNow: 'Tạo hồ sơ ngay',
      AppKeys.parentCreateStudentLater: 'Để sau',
      AppKeys.parentSwitchStudentTitle: 'Chuyển sang hồ sơ học sinh',
      AppKeys.parentSwitchStudentMessage:
          'Tính năng lớp học chỉ dùng được với hồ sơ học sinh. Vui lòng chuyển sang hồ sơ học sinh để tiếp tục.',
      AppKeys.parentSwitchStudentAction: 'Chọn hồ sơ học sinh',
      AppKeys.studentInviteSubtitle: '{name} mời bạn',
      AppKeys.studentInviteSubtitleFallback: 'Giáo viên mời bạn',
      AppKeys.studentInvitationLoadFailed: 'Không thể tải lời mời lớp học.',
      AppKeys.studentInvitationAcceptSuccess: 'Đã tham gia lớp học.',
      AppKeys.studentInvitationRejectSuccess: 'Đã từ chối lời mời.',
      AppKeys.studentJoinClassroomUpper: 'THAM GIA LỚP HỌC',
      AppKeys.studentClassDetailTitle: 'Lớp Học',
      AppKeys.studentClassTeacherRole: 'GIÁO VIÊN',
      AppKeys.studentClassLearningCategories: 'Phân loại học tập',
      AppKeys.studentClassAssignments: 'Bài tập về nhà',
      AppKeys.studentClassAssignmentsSubtitle: '3 nhiệm vụ mới',
      AppKeys.studentClassAssignmentsCountFormat: '{count} bài tập',
      AppKeys.studentClassQuizzes: 'Bài kiểm tra',
      AppKeys.studentClassQuizzesSubtitle: 'Thử thách mới',
      AppKeys.studentClassMaterials: 'Tài liệu',
      AppKeys.studentClassMaterialsSubtitle: '12 thư mục',
      AppKeys.studentClassGrades: 'Bảng điểm',
      AppKeys.studentClassGradesSubtitle: 'Điểm TB: 8.5',
      AppKeys.studentClassUpcomingDeadlines: 'Sắp tới hạn',
      AppKeys.studentClassAll: 'Tất cả',
      AppKeys.studentClassReview15Minutes: 'Ôn tập 15 phút',
      AppKeys.studentClassDeadlineSample: 'Hạn nộp: 21:00 31/05/2026',
      AppKeys.studentClassComingSoon: 'Tính năng sẽ sớm có mặt.',
      AppKeys.studentHomeworkSearchHint: 'Tìm kiếm bài tập',
      AppKeys.studentHomeworkNotSubmitted: 'Chưa nộp',
      AppKeys.studentHomeworkSubmitted: 'Đã nộp',
      AppKeys.studentHomeworkOverdue: 'Quá hạn',
      AppKeys.studentHomeworkAssignedAt: '14:00 29/05/2026',
      AppKeys.studentHomeworkReviewTitle: 'Bài Tập Ôn Luyện',
      AppKeys.studentHomeworkQuestionCount: '30 câu hỏi',
      AppKeys.studentHomeworkDueDate: 'Hạn nộp: 31/05/2026',
      AppKeys.studentHomeworkDueFormat: 'Hạn nộp: {date}',
      AppKeys.studentHomeworkLoadFailed:
          'Không thể tải bài tập. Vui lòng thử lại.',
      AppKeys.studentHomeworkNoQuestions: 'Bài tập chưa có câu hỏi.',
      AppKeys.studentHomeworkQuestionMissingAnswers:
          'Bài tập có câu hỏi chưa có đáp án.',
      AppKeys.studentHomeworkSubmitSuccess: 'Đã nộp bài tập.',
      AppKeys.studentHomeworkSubmitFailed:
          'Nộp bài tập thất bại. Vui lòng thử lại.',
      AppKeys.studentHomeworkMissingExercise: 'Không tìm thấy bài tập để nộp.',
      AppKeys.studentHomeworkAlreadySubmitted: 'Bạn đã nộp bài tập này rồi.',
      AppKeys.assessmentAction: 'Đánh Giá',
      AppKeys.viewAll: 'Xem tất cả',
      AppKeys.viewAllUpper: 'XEM TẤT CẢ',
      AppKeys.progressAchievementTitle: 'Tiến độ vượt bậc',
      AppKeys.todayCompletedExercises: 'Đã hoàn thành 12 bài tập hôm nay',
      AppKeys.reviewTitle: 'Lộ trình học tập',
      AppKeys.exercises: 'Bài tập',
      AppKeys.days: 'Ngày',
      AppKeys.noAccountForProfile: 'Chưa có thông tin tài khoản để tải hồ sơ.',
      AppKeys.noAccountForHistory:
          'Chưa có thông tin tài khoản để tải lịch sử.',
      AppKeys.profileLoadFailed: 'Tải hồ sơ thất bại.',
      AppKeys.chapterMissingProfileInfo:
          'Hồ sơ thiếu lớp, chương trình hoặc học kỳ.',
      AppKeys.chapterLoadFailed: 'Tải danh sách chương thất bại.',
      AppKeys.profileLoadErrorTitle: 'Không tải được hồ sơ',
      AppKeys.noProfileTitle: 'Chưa có hồ sơ',
      AppKeys.noProfileMessage: 'Bạn có thể thêm hồ sơ học tập cho bé.',
      AppKeys.addProfile: 'Thêm hồ sơ',
      AppKeys.chapterLoadErrorTitle: 'Không tải được chương',
      AppKeys.noChapterTitle: 'Chưa có chương',
      AppKeys.noChapterMessage: 'Chưa có lộ trình ôn tập cho hồ sơ này.',
      AppKeys.test: 'Kiểm tra',
      AppKeys.startTest: 'Bắt đầu kiểm tra ({count})',
      AppKeys.clearSelection: 'Bỏ chọn',
      AppKeys.startChapterTestMessage: 'Bắt đầu kiểm tra chương {chapter}.',
      AppKeys.startSelectedTestMessage: 'Bắt đầu kiểm tra {count} chương.',
      AppKeys.chapter: 'Chương',
      AppKeys.lessons: 'bài học',
      AppKeys.chapterNumber: 'Chương {number}',
      AppKeys.lockedLessonMessage: 'Bài {number}: {title} sẽ mở sau.',
      AppKeys.historyTitle: 'Lịch Sử',
      AppKeys.searchHint: 'Tìm kiếm ...',
      AppKeys.assessmentTab: 'Kiểm tra',
      AppKeys.practiceTab: 'Luyện tập',
      AppKeys.historyLoadFailed: 'Tải lịch sử thất bại.',
      AppKeys.historyLoadErrorTitle: 'Chưa tải được lịch sử',
      AppKeys.noHistoryTitle: 'Chưa có bài phù hợp',
      AppKeys.noHistoryMessage: 'Đổi từ khóa để xem các bài khác.',
      AppKeys.missingQuizId: 'Bài kiểm tra này thiếu quiz_id.',
      AppKeys.incomplete: 'Chưa xong',
      AppKeys.mathAssessment: 'Bài kiểm tra Toán',
      AppKeys.mathPractice: 'Bài luyện tập Toán',
      AppKeys.mathReview: 'Bài ôn tập Toán',
      AppKeys.excellent: 'Tuyệt vời!',
      AppKeys.good: 'Tốt',
      AppKeys.niceTry: 'Cố gắng tốt',
      AppKeys.failed: 'Chưa đạt',
      AppKeys.quizDetailLoadFailed: 'Tải chi tiết bài kiểm tra thất bại.',
      AppKeys.quizDetailTitle: 'Chi Tiết Bài Kiểm Tra',
      AppKeys.emptyQuizQuestions: 'Bài kiểm tra chưa có câu hỏi.',
      AppKeys.totalQuestions: 'Tổng câu',
      AppKeys.correct: 'Đúng',
      AppKeys.incorrect: 'Sai',
      AppKeys.time: 'Thời gian',
      AppKeys.questionNumber: 'Câu {number}',
      AppKeys.showAnswerUpper: 'ĐÁP ÁN',
      AppKeys.hideAnswerUpper: 'ẨN ĐÁP ÁN',
      AppKeys.noAnswer: 'Chưa có đáp án.',
      AppKeys.answer: 'Đáp án: {answer}',
      AppKeys.quizDetailErrorTitle: 'Không tải được chi tiết bài kiểm tra.',
      AppKeys.settingsTitle: 'Cài Đặt',
      AppKeys.accountTitle: 'Tài Khoản',
      AppKeys.profileTitle: 'Hồ Sơ',
      AppKeys.addProfileTitle: 'Thêm Hồ Sơ',
      AppKeys.updateProfileTitle: 'Cập Nhật Hồ Sơ',
      AppKeys.school: 'Trường Học',
      AppKeys.accountMenuTitle: 'Tài Khoản',
      AppKeys.accountMenuSubtitle: 'Quản lý thông tin tài khoản',
      AppKeys.profileMenuTitle: 'Hồ Sơ',
      AppKeys.profileMenuSubtitle: 'Xem và chỉnh sửa hồ sơ',
      AppKeys.logout: 'Logout',
      AppKeys.logoutSubtitle: 'Đăng xuất khỏi tài khoản',
      AppKeys.passcodeMenuTitle: 'Mã PIN',
      AppKeys.passcodeMenuSubtitleSet: 'Tạo mã PIN để khóa ứng dụng',
      AppKeys.passcodeMenuSubtitleManage: 'Đổi hoặc xóa mã PIN',
      AppKeys.createPasscodeTitle: 'Tạo Mã PIN',
      AppKeys.confirmPasscodeTitle: 'Nhập Lại Mã PIN',
      AppKeys.unlockPasscodeTitle: 'Nhập Mã PIN',
      AppKeys.verifyPasscodeTitle: 'Xác Minh Mã PIN',
      AppKeys.createPasscodeSubtitle: 'Tạo mã PIN để\nđăng nhập nhanh chóng',
      AppKeys.confirmPasscodeSubtitle: 'Nhập lại mã PIN để\nxác nhận',
      AppKeys.unlockPasscodeSubtitle: 'Nhập mã PIN để\nđăng nhập nhanh chóng',
      AppKeys.verifyPasscodeSubtitle: 'Nhập mã PIN để\nxác nhận',
      AppKeys.changePasscodeTitle: 'Đổi Mã PIN',
      AppKeys.enterCurrentPasscodeTitle: 'Nhập Mã PIN Hiện Tại',
      AppKeys.passcodeContinue: 'Tiếp Tục',
      AppKeys.passcodeUnlock: 'Mở Khóa',
      AppKeys.passcodeSkip: 'Bỏ Qua',
      AppKeys.passcodeRemove: 'Xóa Mã PIN',
      AppKeys.passcodeSetUp: 'Tạo Mã PIN',
      AppKeys.passcodeChange: 'Đổi Mã PIN',
      AppKeys.passcodeMismatch: 'Mã PIN không khớp. Vui lòng thử lại.',
      AppKeys.passcodeIncorrect: 'Mã PIN không đúng. Vui lòng thử lại.',
      AppKeys.passcodeSaveFailed: 'Không thể lưu mã PIN. Vui lòng thử lại.',
      AppKeys.passcodeSessionExpired:
          'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
      AppKeys.passcodeRemoveFailed: 'Không thể xóa mã PIN. Vui lòng thử lại.',
      AppKeys.passcodeSet: 'Đã tạo mã PIN.',
      AppKeys.passcodeChanged: 'Đã đổi mã PIN.',
      AppKeys.passcodeRemoved: 'Đã xóa mã PIN.',
      AppKeys.missingAccount: 'Thiếu thông tin tài khoản.',
      AppKeys.accountNameRequired: 'Vui lòng nhập tên tài khoản.',
      AppKeys.accountUpdated: 'Đã cập nhật tài khoản.',
      AppKeys.accountUpdateFailed: 'Không thể cập nhật tài khoản.',
      AppKeys.imagePickFailed: 'Không thể chọn ảnh lúc này.',
      AppKeys.profileOptionsMissingAccount:
          'Chưa có thông tin tài khoản để tải lựa chọn.',
      AppKeys.profileOptionsLoadFailed: 'Tải lựa chọn hồ sơ thất bại.',
      AppKeys.schoolOptionsLoadFailed: 'Tải danh sách trường thất bại.',
      AppKeys.reloadOptions: 'Tải lại lựa chọn',
      AppKeys.missingProfileName: 'Vui lòng nhập họ tên.',
      AppKeys.missingProfileSelections: 'Vui lòng chọn đủ thông tin.',
      AppKeys.missingProfileId: 'Hồ sơ này thiếu profile_id.',
      AppKeys.profileCreateFailed: 'Không thể tạo hồ sơ. Vui lòng thử lại.',
      AppKeys.profileUpdateFailed:
          'Không thể cập nhật hồ sơ. Vui lòng thử lại.',
      AppKeys.deleteProfileTitle: 'Xóa hồ sơ?',
      AppKeys.deleteProfileMessage:
          'Bạn có chắc muốn delete profile này không?',
      AppKeys.profileDeleted: 'Đã xóa hồ sơ.',
      AppKeys.profileDeleteFailed: 'Không thể xóa hồ sơ. Vui lòng thử lại.',
      AppKeys.username: 'Tên Người Dùng',
      AppKeys.fullName: 'Họ Tên',
      AppKeys.studentNameHint: 'Nhập họ tên học sinh',
      AppKeys.parentProfileNameHint: 'Nhập họ tên phụ huynh',
      AppKeys.phoneNumber: 'Số Điện Thoại',
      AppKeys.email: 'Email',
      AppKeys.parentProfilePhoneHint: 'Nhập số điện thoại phụ huynh',
      AppKeys.parentProfileEmailHint: 'Nhập email phụ huynh',
      AppKeys.grade: 'Lớp',
      AppKeys.program: 'Chương Trình',
      AppKeys.learningProgram: 'Chương Trình Học',
      AppKeys.semester: 'Học kỳ',
      AppKeys.chooseSchool: 'Chọn trường học',
      AppKeys.chooseGrade: 'Chọn lớp',
      AppKeys.chooseProgram: 'Chọn chương trình',
      AppKeys.chooseSemester: 'Chọn học kỳ',
      AppKeys.noSchools: 'Chưa có trường học nào để hiển thị.',
      AppKeys.active: 'ACTIVE',
      AppKeys.switchingProfile: 'Đang chuyển hồ sơ...',
      AppKeys.switchingLanguage: 'Đang đổi ngôn ngữ...',
      AppKeys.parentInfoTitle: 'Thông tin phụ huynh',
      AppKeys.parentChildrenCount: 'Con của tôi ({count})',
      AppKeys.profileRole: 'Vai trò',
      AppKeys.roleStudent: 'Học sinh',
      AppKeys.roleParent: 'Phụ huynh',
      AppKeys.roleTeacher: 'Giáo viên',
      AppKeys.belovedChild: 'Bé yêu',
      AppKeys.notSelected: 'Chưa chọn',
      AppKeys.teacherFallback: 'Giáo viên',
      AppKeys.teacherMissingProfileId: 'Hồ sơ giáo viên thiếu profile_id.',
      AppKeys.teacherClassOpenFailed: 'Không mở được lớp học này.',
      AppKeys.teacherWelcomeBack: 'CHÀO MỪNG TRỞ LẠI',
      AppKeys.teacherHeroTitle: 'Sẵn sàng cho ngày mới',
      AppKeys.teacherHeroSubtitle: 'chuẩn bị học nhiều hơn',
      AppKeys.teacherYourClasses: 'Lớp học của bạn',
      AppKeys.teacherCreateNewClass: 'Tạo Lớp Học Mới',
      AppKeys.teacherCompleteProfile: 'Hoàn Thành Hồ Sơ',
      AppKeys.teacherClassFallback: 'Lớp học',
      AppKeys.teacherStudentCount: '{count} Học sinh',
      AppKeys.teacherEnterClass: 'Vào Lớp',
      AppKeys.teacherReportTitle: 'Báo Cáo',
      AppKeys.teacherReportComingSoon: 'Báo cáo lớp học sẽ sớm có mặt',
      AppKeys.teacherReportPlaceholder:
          'Numi đang chuẩn bị số liệu học tập cho giáo viên.',
      AppKeys.teacherCreateClassTitle: 'Tạo Lớp',
      AppKeys.teacherCreateOptionsFailed: 'Tải lựa chọn tạo lớp thất bại.',
      AppKeys.teacherClassMissingInfo: 'Vui lòng nhập đủ thông tin lớp học.',
      AppKeys.teacherClassImageLabel: 'Ảnh đại diện lớp học',
      AppKeys.teacherGradeLevel: 'Khối lớp',
      AppKeys.teacherClassName: 'Tên lớp học',
      AppKeys.teacherClassNameHint: 'Ví dụ: 1A2, 2A3,...',
      AppKeys.teacherClassDescription: 'Mô tả lớp học (không bắt buộc)',
      AppKeys.teacherClassDescriptionHint: 'Giới thiệu mục tiêu của lớp...',
      AppKeys.teacherCreating: 'Đang tạo...',
      AppKeys.teacherCreate: 'Tạo',
      AppKeys.teacherNoOptions: 'Chưa có lựa chọn',
      AppKeys.teacherClassDetailTitle: 'Lớp Học',
      AppKeys.teacherProgramFallback: 'Chương trình',
      AppKeys.teacherDescriptionFallback: 'Thông tin lớp',
      AppKeys.teacherClassInfoFallback: 'Lớp học',
      AppKeys.teacherClassHideLess: 'ẩn bớt',
      AppKeys.teacherCopiedClassLink: 'Đã sao chép liên kết lớp học.',
      AppKeys.teacherCopiedClassCode: 'Đã sao chép mã lớp.',
      AppKeys.profileIdCopied: 'Đã sao chép ID hồ sơ.',
      AppKeys.profileCodeLabel: 'Mã',
      AppKeys.profileCodeCopied: 'Đã sao chép mã hồ sơ.',
      AppKeys.teacherMemberManagement: 'Quản lý thành viên',
      AppKeys.teacherMemberSummary:
          '{members} thành viên\n{requests} yêu cầu mới',
      AppKeys.teacherMemberSummaryNoRequests: '{members} thành viên',
      AppKeys.teacherMembersTitle: 'Thành Viên',
      AppKeys.teacherJoinRequests: 'Yêu cầu tham gia ({count})',
      AppKeys.teacherNoJoinRequests: 'Chưa có yêu cầu tham gia.',
      AppKeys.teacherPendingApproval: 'Đang đợi phê duyệt',
      AppKeys.teacherJoinedStudentsTitle: 'Học sinh đã tham gia ({count})',
      AppKeys.teacherSearchStudentTitle: 'Thêm học sinh',
      AppKeys.teacherSearchStudentHint: 'Nhập tên hoặc mã học sinh',
      AppKeys.teacherNoStudentResults: 'Không tìm thấy học sinh phù hợp.',
      AppKeys.teacherSearchStudentFailed: 'Tìm kiếm học sinh thất bại.',
      AppKeys.teacherSelectedStudents: 'Đã chọn {count} học sinh',
      AppKeys.teacherSendInviteRequest: 'Gửi lời mời',
      AppKeys.teacherInviteRequestQueued:
          'Đã gửi lời mời cho {count} học sinh.',
      AppKeys.teacherTwoMinutesAgo: '2 phút trước',
      AppKeys.teacherFiveMinutesAgo: '5 phút trước',
      AppKeys.teacherClassFunctions: 'Chức Năng Lớp Học',
      AppKeys.teacherAssignments: 'Bài Tập',
      AppKeys.teacherAssessments: 'Đánh Giá',
      AppKeys.teacherCreatedAssignments: 'Bài tập đã tạo',
      AppKeys.teacherCreatedAssessments: 'Đánh giá đã tạo',
      AppKeys.teacherAssignmentSearchHint: 'Tìm kiếm ...',
      AppKeys.teacherAssignmentNewest: 'Mới nhất',
      AppKeys.teacherAssignmentListLoadFailed:
          'Tải danh sách bài tập thất bại.',
      AppKeys.teacherAssessmentListLoadFailed:
          'Tải danh sách đánh giá thất bại.',
      AppKeys.teacherAssignmentDetailLoadFailed:
          'Tải chi tiết bài tập thất bại.',
      AppKeys.teacherAssessmentDetailLoadFailed:
          'Tải chi tiết đánh giá thất bại.',
      AppKeys.teacherAssignmentCreateFailed:
          'Không thể tạo bài tập. Vui lòng thử lại.',
      AppKeys.teacherAssessmentCreateFailed:
          'Không thể tạo đánh giá. Vui lòng thử lại.',
      AppKeys.teacherAssignmentPickerSoon:
          'Lựa chọn này sẽ sớm có. Bạn vẫn có thể tạo bài tập.',
      AppKeys.teacherNoAssignments: 'Chưa có bài tập nào.',
      AppKeys.teacherNoAssessments: 'Chưa có đánh giá nào.',
      AppKeys.teacherAssignmentGeometryTitle: 'Bài tập về nhà: Hình học cơ bản',
      AppKeys.teacherAssignmentId: 'ID: {id}',
      AppKeys.teacherCreateAssignmentSoon: 'Tính năng tạo bài tập sẽ sớm có.',
      AppKeys.teacherAssignmentClassName: 'Toán 1A2',
      AppKeys.teacherAssignmentReviewTitle: 'Bài Tập Ôn Luyện',
      AppKeys.teacherAssignmentChapterRange: 'Chương 3, Bài 5-6',
      AppKeys.teacherAssignmentDueLabel: 'HẠN NỘP',
      AppKeys.teacherAssignmentDueValue: '21:00 31/05/2026',
      AppKeys.teacherAssignmentQuestionCountLabel: 'SỐ CÂU HỎI',
      AppKeys.teacherAssignmentQuestionCountValue: '10 câu',
      AppKeys.teacherAssignmentQuestionCountFormat: '{count} câu',
      AppKeys.teacherAssignmentQuestionContent: 'Nội dung câu hỏi',
      AppKeys.teacherAssignmentQuestionNumber: 'Câu {number}',
      AppKeys.teacherAssignmentEquationPrompt:
          'Giải phương trình x² - 5x + 6 = 0.',
      AppKeys.teacherCreateAssignmentTitle: 'Tạo Bài Tập',
      AppKeys.teacherCreateAssessmentTitle: 'Tạo Đánh Giá',
      AppKeys.teacherAssignmentClassOption: 'Lớp 2A1',
      AppKeys.teacherAssignmentSelectClass: 'Chọn lớp học',
      AppKeys.teacherAssignmentClassSummaryName: 'Toán A1',
      AppKeys.teacherAssignmentClassStudentCount: '32 Học Sinh',
      AppKeys.teacherAssignmentClassStudentCountFormat: '{count} Học Sinh',
      AppKeys.teacherAssignmentClassGrade: 'Lớp 1',
      AppKeys.teacherAssignmentClassProgram: 'Cánh Diều',
      AppKeys.teacherAssignmentClassDescription: 'Lớp Cá Biệt',
      AppKeys.teacherAssignmentVolumeOne: 'Tập 1',
      AppKeys.teacherAssignmentVolumeTwo: 'Tập 2',
      AppKeys.teacherAssignmentTitleHint: 'Tiêu Đề',
      AppKeys.teacherAssessmentTitleHint: 'Tiêu Đề Đánh Giá',
      AppKeys.teacherAssignmentProgramLabel: 'Chương Trình',
      AppKeys.teacherAssignmentProgramValue: 'Cánh Diều 1',
      AppKeys.teacherAssignmentProgramRequired: 'Vui lòng chọn chương trình.',
      AppKeys.teacherAssignmentPublishLabel: 'Hiển thị',
      AppKeys.teacherAssignmentVisibilityPublic: 'PUBLIC',
      AppKeys.teacherAssignmentVisibilityPrivate: 'PRIVATE',
      AppKeys.teacherAssignmentDeadline: 'Hạn Nộp',
      AppKeys.teacherAssignmentStartDateHint: 'Ngày giờ bắt đầu',
      AppKeys.teacherAssignmentEndDateHint: 'Ngày giờ kết thúc',
      AppKeys.teacherAssignmentStartDateRequired: 'Vui lòng chọn ngày bắt đầu.',
      AppKeys.teacherAssignmentEndDateRequired: 'Vui lòng chọn ngày kết thúc.',
      AppKeys.teacherAssignmentFutureDateRequired:
          'Ngày đã chọn phải ở tương lai.',
      AppKeys.teacherAssignmentEndAfterStart:
          'Ngày kết thúc phải sau ngày bắt đầu.',
      AppKeys.teacherAssignmentChapterLabel: 'Chương Học',
      AppKeys.teacherAssignmentLessonLabel: 'Bài Học',
      AppKeys.teacherAssignmentDescriptionLabel: 'Mô tả',
      AppKeys.teacherAssignmentDescriptionHint: 'Mô tả thêm',
      AppKeys.teacherAssessmentDescriptionHint: 'Mô tả đánh giá',
      AppKeys.teacherAssignmentCreated: 'Đã tạo bài tập.',
      AppKeys.teacherAssessmentCreated: 'Đã tạo đánh giá.',
      AppKeys.teacherJoinedStudents: 'Học sinh đã tham gia ({count})',
      AppKeys.teacherNoJoinedStudents: 'Chưa có học sinh tham gia.',
      AppKeys.teacherStudentFallback: 'Học sinh',
      AppKeys.teacherJustJoined: 'Vừa tham gia',
      AppKeys.profileTeacherNameHint: 'Nhập tên giáo viên',
      AppKeys.profileIdTypeLabel: 'Loại giấy tờ',
      AppKeys.profileIdTypeHint: 'Chọn loại giấy tờ',
      AppKeys.profileIdTypeNone: 'Không chọn',
      AppKeys.profileIdValueLabel: 'ID',
      AppKeys.profileTeacherIdHint:
          'Nhập mã cán bộ giáo viên hoặc số định danh',
      AppKeys.profileStudentIdHint: 'Nhập mã học bạ',
      AppKeys.idTypeMoetLabel: 'Mã học bạ',
      AppKeys.idTypeTeacherMoetLabel: 'Mã cán bộ giáo viên',
      AppKeys.idTypePublicIdLabel: 'Số định danh cá nhân',
      AppKeys.noAccountForGrades:
          'Chưa có thông tin tài khoản để tải danh sách lớp.',
      AppKeys.gradeLoadFailed: 'Tải danh sách lớp thất bại.',
      AppKeys.gradeQuestionTitle: 'Bé đang học lớp mấy\nnhỉ?',
      AppKeys.generateTestFailed: 'Tạo test thất bại. Vui lòng thử lại sau.',
      AppKeys.noGrades: 'Chưa có lớp học nào để hiển thị.',
      AppKeys.createQuestionFailed: 'Không thể tạo câu hỏi. Vui lòng thử lại.',
      AppKeys.missingQuizToSubmit: 'Không tìm thấy bài test để nộp.',
      AppKeys.submitQuizFailed: 'Nộp bài thất bại. Vui lòng thử lại.',
      AppKeys.unansweredSubmitTitle: 'Bạn có câu hỏi chưa trả lời',
      AppKeys.unansweredSubmitMessage: 'Bạn có chắc muốn nộp bài không?',
      AppKeys.stayUpper: 'Ở LẠI',
      AppKeys.submitUpper: 'NỘP BÀI',
      AppKeys.submittingForYou: 'đợi Numi nộp bài cho bạn nhé!',
      AppKeys.generatingAssessment: 'Để Numi tạo bài kiểm tra cho bạn nhé',
      AppKeys.aiChallenge: 'Thử thách AI',
      AppKeys.questionProgress: 'CÂU {current}/{total}',
      AppKeys.previousQuestionUpper: 'CÂU TRƯỚC',
      AppKeys.submittingUpper: 'ĐANG NỘP',
      AppKeys.testAgainCreateMissingQuiz: 'Không tìm thấy bài test trước đó.',
      AppKeys.testAgainCreateFailed: 'Không thể tạo bài mới. Vui lòng thử lại.',
      AppKeys.testAgainDialogTitle: 'Tạo bài mới thất bại',
      AppKeys.excellentResultTitle: 'Xuất Sắc',
      AppKeys.excellentResultMessage: '',
      AppKeys.generatingNewQuiz: 'đợi Numi tạo bài mới cho bạn nhé!',
      AppKeys.assessmentResultTitle: 'Kết Quả',
      AppKeys.scoreUpper: 'ĐIỂM SỐ',
      AppKeys.numiAiReview: 'Numi AI nhận xét',
      AppKeys.defaultAiReview:
          'Bé làm rất tốt phần phép cộng, hãy tiếp tục phát huy nhé! Chúng ta chỉ cần thôi.',
      AppKeys.defaultAiReviewHighlight: 'phép cộng',
      AppKeys.assessmentUpper: 'Đánh Giá',
      AppKeys.practiceUpper: 'Luyện Tập',
      AppKeys.authPhoneCheckFailed: 'Không thể kiểm tra số điện thoại.',
      AppKeys.signupOtpFailed: 'Không thể gửi OTP đăng ký. Vui lòng thử lại.',
      AppKeys.loginOtpFailed: 'Không thể gửi OTP. Vui lòng thử lại.',
      AppKeys.invalidOtp: 'Mã OTP không đúng. Vui lòng thử lại.',
      AppKeys.missingOtpUser: 'Response OTP thiếu thông tin user.',
      AppKeys.verifyOtpFailed: 'Không thể xác thực OTP. Vui lòng thử lại.',
      AppKeys.childNameRequired: 'Vui lòng nhập tên của bé.',
      AppKeys.signupFailed: 'Không thể đăng ký. Vui lòng thử lại.',
      AppKeys.quizHasNoQuestions: 'Quiz không có câu hỏi.',
      AppKeys.missingUserOrProfileForHistory:
          'Thiếu user hoặc profile để tải lịch sử.',
      AppKeys.missingQuizIdShort: 'Thiếu quiz ID.',
      AppKeys.apiBaseUrlMissing: 'Chưa cấu hình API_BASE_URL.',
      AppKeys.invalidServerResponse: 'Response từ server không hợp lệ.',
      AppKeys.apiConnectTimeout: 'Kết nối API quá thời gian chờ.',
      AppKeys.apiReceiveTimeout: 'API phản hồi quá thời gian chờ.',
      AppKeys.apiConnectFailed: 'Không kết nối được API: {message}',
      AppKeys.apiBadCertificate: 'Chứng chỉ API không hợp lệ.',
      AppKeys.apiRequestCanceled: 'Request đã bị hủy.',
      AppKeys.apiConnectionFailed: 'Không kết nối được API.',
    },
    'en': {
      AppKeys.appName: 'NUMI',
      AppKeys.loading: 'Loading...',
      AppKeys.close: 'Close',
      AppKeys.cancel: 'Cancel',
      AppKeys.save: 'Save',
      AppKeys.retry: 'Retry',
      AppKeys.retryUpper: 'RETRY',
      AppKeys.accept: 'Accept',
      AppKeys.reject: 'Reject',
      AppKeys.delete: 'Delete',
      AppKeys.update: 'Update',
      AppKeys.add: 'Add',
      AppKeys.back: 'Back',
      AppKeys.skipUpper: 'SKIP',
      AppKeys.continueUpper: 'CONTINUE',
      AppKeys.language: 'Language',
      AppKeys.languageTitle: 'Language',
      AppKeys.languageMenuSubtitle: 'Change display language',
      AppKeys.languageVietnamese: 'Tiếng Việt',
      AppKeys.languageEnglish: 'English',
      AppKeys.welcomeTitlePrefix: 'Learn math with\n',
      AppKeys.welcomeTitleN: 'NUMI',
      AppKeys.welcomeSubtitlePrefix: 'Join Numi',
      AppKeys.welcomeSubtitle: 'and become a math wizard!',
      AppKeys.start: 'START',
      AppKeys.phoneLoginTitle: 'Phone number',
      AppKeys.phoneLoginBrandName: 'NUMINUMI',
      AppKeys.phoneLoginSubtitle:
          'Enter your phone number to\nsign up or log in!',
      AppKeys.phoneNumberUpper: 'PHONE NUMBER',
      AppKeys.phoneHint: 'Enter phone number',
      AppKeys.chooseCountry: 'Choose country',
      AppKeys.continueLabel: 'Continue',
      AppKeys.creatingAccount: 'Creating account...',
      AppKeys.checking: 'Checking...',
      AppKeys.phoneRequired: 'Please enter a phone number.',
      AppKeys.invalidPhone: 'The phone number is invalid.',
      AppKeys.phoneTooShort: 'The phone number is too short.',
      AppKeys.restoringSession: 'Checking login session...',
      AppKeys.newAccountPrompt: 'This is a NEW account. Continue to sign up?',
      AppKeys.signup: 'Sign up',
      AppKeys.login: 'Log in',
      AppKeys.loginWithPin: 'Log in with PIN',
      AppKeys.otpWithin30Seconds: 'You will receive a code within 30 seconds',
      AppKeys.otpTitle: 'VERIFICATION CODE',
      AppKeys.otpSentMessage: 'OTP code sent: {code}',
      AppKeys.otpConfirming: 'Verifying...',
      AppKeys.otpConfirm: 'Confirm',
      AppKeys.resendOtp: 'Resend code',
      AppKeys.resendOtpAfter: 'Resend code in {seconds}s',
      AppKeys.signupNameHint: 'Enter full name',
      AppKeys.signupEmailHint: 'example@numinumi.com',
      AppKeys.signupNameLabel: 'Full name',
      AppKeys.signupEmailLabel: 'Email',
      AppKeys.signupRoleLabel: 'You are',
      AppKeys.signupRoleStudent: 'Student',
      AppKeys.signupRoleParent: 'Parent',
      AppKeys.signupRoleTeacher: 'Teacher',
      AppKeys.signupEmailDescription:
          "Enter an email to follow your child's assessment results\nand learning journey",
      AppKeys.avatarUpper: 'AVATAR',
      AppKeys.chooseAvatar: 'Choose avatar',
      AppKeys.signingUp: 'Signing up...',
      AppKeys.navHome: 'HOME',
      AppKeys.navReview: 'REVIEW',
      AppKeys.navHistory: 'HISTORY',
      AppKeys.navReport: 'REPORT',
      AppKeys.navSettings: 'SETTINGS',
      AppKeys.student: 'STUDENT',
      AppKeys.assessment: 'ASSESSMENT',
      AppKeys.assessmentDescription:
          'Use AI to check your unique\nmath strengths.',
      AppKeys.startNow: 'Start now',
      AppKeys.practice: 'Practice',
      AppKeys.yourAchievement: 'Your achievements',
      AppKeys.studentHomework: 'Homework',
      AppKeys.studentClassroom: 'Classroom',
      AppKeys.studentNoHomeworkTitle: 'No homework yet',
      AppKeys.studentNoHomeworkMessage: 'Assigned homework will appear here.',
      AppKeys.studentNoClassroomsTitle: 'No joined classrooms',
      AppKeys.studentNoClassroomsMessage:
          'Join a classroom to receive homework and track progress.',
      AppKeys.studentJoinNewClassroom: 'Join new classroom',
      AppKeys.studentJoinClassroomSoon: 'Classroom joining is coming soon.',
      AppKeys.studentClassroomLoadFailed: 'Failed to load classrooms.',
      AppKeys.studentMissingProfileId: 'Student profile is missing profile_id.',
      AppKeys.studentFindClassTitle: 'Find Classroom',
      AppKeys.studentClassCodeHint: 'Enter class code',
      AppKeys.studentSearchClass: 'Search classrooms',
      AppKeys.studentSearchResults: 'Search results',
      AppKeys.studentDefaultSchoolFilter: 'Luu Tan Phat School',
      AppKeys.studentGradeFilter: 'Grade {grade}',
      AppKeys.studentClassSearchFailed: 'Failed to search classrooms.',
      AppKeys.studentClassSearchLoading: 'Searching for matching classes...',
      AppKeys.studentClassSearchRetry: 'Try another code or class name.',
      AppKeys.studentNoClassSearchResults: 'No classrooms found',
      AppKeys.studentNoClassSearchResultsMessage:
          'Check the class code or class name and try again.',
      AppKeys.studentEnterClassCodeTitle: 'Enter a code or class name',
      AppKeys.studentEnterClassCodeMessage:
          'Matching classroom results will appear here.',
      AppKeys.studentClassMissingCode: 'This classroom has no join code yet.',
      AppKeys.studentJoinClassSuccess: 'Class join request sent.',
      AppKeys.studentJoinClassFailed: 'Could not send class join request.',
      AppKeys.studentAlreadyJoinedClass: 'You have already joined this class.',
      AppKeys.studentClassJoinRequestPending:
          'This classroom already has a pending invitation or request.',
      AppKeys.studentClassCodeLabel: 'CODE: {code}',
      AppKeys.studentClassRelationshipMember: 'JOINED',
      AppKeys.studentClassRelationshipPendingInvitation: 'INVITED',
      AppKeys.studentClassRelationshipPendingRequest: 'PENDING',
      AppKeys.studentClassRelationshipNone: 'NOT JOINED',
      AppKeys.studentClassInvitations: 'Class invitations',
      AppKeys.studentViewAllInvitations: 'View all ({count})',
      AppKeys.studentViewAllClassrooms: 'View all ({count})',
      AppKeys.studentNoInvitationsTitle: 'No invitations yet',
      AppKeys.studentNoInvitationsMessage:
          'New class invitations will appear here.',
      AppKeys.parentNoStudentTitle: 'No child profile yet',
      AppKeys.parentNoStudentMessage:
          'Create a child profile before joining a classroom.',
      AppKeys.parentCreateStudentNow: 'Create profile now',
      AppKeys.parentCreateStudentLater: 'Later',
      AppKeys.parentSwitchStudentTitle: 'Switch to a student profile',
      AppKeys.parentSwitchStudentMessage:
          'Classroom features are only available for student profiles. Please switch to a student profile to continue.',
      AppKeys.parentSwitchStudentAction: 'Choose student profile',
      AppKeys.studentInviteSubtitle: '{name} invited you',
      AppKeys.studentInviteSubtitleFallback: 'Your teacher invited you',
      AppKeys.studentInvitationLoadFailed: 'Could not load class invitations.',
      AppKeys.studentInvitationAcceptSuccess: 'Joined classroom.',
      AppKeys.studentInvitationRejectSuccess: 'Invitation rejected.',
      AppKeys.studentJoinClassroomUpper: 'JOIN CLASSROOM',
      AppKeys.studentClassDetailTitle: 'Class',
      AppKeys.studentClassTeacherRole: 'TEACHER',
      AppKeys.studentClassLearningCategories: 'Learning categories',
      AppKeys.studentClassAssignments: 'Homework',
      AppKeys.studentClassAssignmentsSubtitle: '3 new tasks',
      AppKeys.studentClassAssignmentsCountFormat: '{count} assignments',
      AppKeys.studentClassQuizzes: 'Quizzes',
      AppKeys.studentClassQuizzesSubtitle: 'New challenge',
      AppKeys.studentClassMaterials: 'Materials',
      AppKeys.studentClassMaterialsSubtitle: '12 folders',
      AppKeys.studentClassGrades: 'Grades',
      AppKeys.studentClassGradesSubtitle: 'Average score: 8.5',
      AppKeys.studentClassUpcomingDeadlines: 'Upcoming deadlines',
      AppKeys.studentClassAll: 'All',
      AppKeys.studentClassReview15Minutes: '15-minute review',
      AppKeys.studentClassDeadlineSample: 'Due: 21:00 05/31/2026',
      AppKeys.studentClassComingSoon: 'This feature is coming soon.',
      AppKeys.studentHomeworkSearchHint: 'Search homework',
      AppKeys.studentHomeworkNotSubmitted: 'Not submitted',
      AppKeys.studentHomeworkSubmitted: 'Submitted',
      AppKeys.studentHomeworkOverdue: 'Overdue',
      AppKeys.studentHomeworkAssignedAt: '14:00 05/29/2026',
      AppKeys.studentHomeworkReviewTitle: 'Review Homework',
      AppKeys.studentHomeworkQuestionCount: '30 questions',
      AppKeys.studentHomeworkDueDate: 'Due: 05/31/2026',
      AppKeys.studentHomeworkDueFormat: 'Due: {date}',
      AppKeys.studentHomeworkLoadFailed:
          'Could not load homework. Please try again.',
      AppKeys.studentHomeworkNoQuestions: 'This homework has no questions yet.',
      AppKeys.studentHomeworkQuestionMissingAnswers:
          'This homework has a question with no answers.',
      AppKeys.studentHomeworkSubmitSuccess: 'Homework submitted.',
      AppKeys.studentHomeworkSubmitFailed:
          'Failed to submit homework. Please try again.',
      AppKeys.studentHomeworkMissingExercise:
          'Could not find homework to submit.',
      AppKeys.studentHomeworkAlreadySubmitted:
          'You have already submitted this homework.',
      AppKeys.assessmentAction: 'Assessment',
      AppKeys.viewAll: 'View all',
      AppKeys.viewAllUpper: 'VIEW ALL',
      AppKeys.progressAchievementTitle: 'Great progress',
      AppKeys.todayCompletedExercises: 'Completed 12 exercises today',
      AppKeys.reviewTitle: 'Learning journey',
      AppKeys.exercises: 'Exercises',
      AppKeys.days: 'Days',
      AppKeys.noAccountForProfile: 'No account information to load profiles.',
      AppKeys.noAccountForHistory: 'No account information to load history.',
      AppKeys.profileLoadFailed: 'Failed to load profiles.',
      AppKeys.chapterMissingProfileInfo:
          'Profile is missing grade, program, or semester.',
      AppKeys.chapterLoadFailed: 'Failed to load chapters.',
      AppKeys.profileLoadErrorTitle: 'Could not load profiles',
      AppKeys.noProfileTitle: 'No profile yet',
      AppKeys.noProfileMessage:
          'You can add a learning profile for your child.',
      AppKeys.addProfile: 'Add profile',
      AppKeys.chapterLoadErrorTitle: 'Could not load chapters',
      AppKeys.noChapterTitle: 'No chapters',
      AppKeys.noChapterMessage:
          'No review journey is available for this profile.',
      AppKeys.test: 'Test',
      AppKeys.startTest: 'Start test ({count})',
      AppKeys.clearSelection: 'Clear',
      AppKeys.startChapterTestMessage: 'Starting test for chapter {chapter}.',
      AppKeys.startSelectedTestMessage: 'Starting test for {count} chapters.',
      AppKeys.chapter: 'Chapter',
      AppKeys.lessons: 'lessons',
      AppKeys.chapterNumber: 'Chapter {number}',
      AppKeys.lockedLessonMessage: 'Lesson {number}: {title} opens later.',
      AppKeys.historyTitle: 'History',
      AppKeys.searchHint: 'Search ...',
      AppKeys.assessmentTab: 'Assessment',
      AppKeys.practiceTab: 'Practice',
      AppKeys.historyLoadFailed: 'Failed to load history.',
      AppKeys.historyLoadErrorTitle: 'Could not load history',
      AppKeys.noHistoryTitle: 'No matching items',
      AppKeys.noHistoryMessage: 'Change the keyword to view other items.',
      AppKeys.missingQuizId: 'This test is missing quiz_id.',
      AppKeys.incomplete: 'Incomplete',
      AppKeys.mathAssessment: 'Math assessment',
      AppKeys.mathPractice: 'Math practice',
      AppKeys.mathReview: 'Math review',
      AppKeys.excellent: 'Excellent!',
      AppKeys.good: 'Good',
      AppKeys.niceTry: 'Nice try',
      AppKeys.failed: 'Failed',
      AppKeys.quizDetailLoadFailed: 'Failed to load test details.',
      AppKeys.quizDetailTitle: 'Test Details',
      AppKeys.emptyQuizQuestions: 'This test has no questions.',
      AppKeys.totalQuestions: 'Questions',
      AppKeys.correct: 'Correct',
      AppKeys.incorrect: 'Wrong',
      AppKeys.time: 'Time',
      AppKeys.questionNumber: 'Question {number}',
      AppKeys.showAnswerUpper: 'ANSWER',
      AppKeys.hideAnswerUpper: 'HIDE ANSWER',
      AppKeys.noAnswer: 'No answer available.',
      AppKeys.answer: 'Answer: {answer}',
      AppKeys.quizDetailErrorTitle: 'Could not load test details.',
      AppKeys.settingsTitle: 'Settings',
      AppKeys.accountTitle: 'Account',
      AppKeys.profileTitle: 'Profile',
      AppKeys.addProfileTitle: 'Add Profile',
      AppKeys.updateProfileTitle: 'Update Profile',
      AppKeys.school: 'School',
      AppKeys.accountMenuTitle: 'Account',
      AppKeys.accountMenuSubtitle: 'Manage account information',
      AppKeys.profileMenuTitle: 'Profile',
      AppKeys.profileMenuSubtitle: 'View and edit profiles',
      AppKeys.logout: 'Logout',
      AppKeys.logoutSubtitle: 'Sign out of your account',
      AppKeys.passcodeMenuTitle: 'Passcode',
      AppKeys.passcodeMenuSubtitleSet: 'Create a PIN to lock the app',
      AppKeys.passcodeMenuSubtitleManage: 'Change or remove your PIN',
      AppKeys.createPasscodeTitle: 'Create PIN',
      AppKeys.confirmPasscodeTitle: 'Confirm PIN',
      AppKeys.unlockPasscodeTitle: 'Enter PIN',
      AppKeys.verifyPasscodeTitle: 'Verify PIN',
      AppKeys.createPasscodeSubtitle: 'Create a PIN for\nquick login',
      AppKeys.confirmPasscodeSubtitle: 'Enter your PIN again\nto confirm',
      AppKeys.unlockPasscodeSubtitle: 'Enter your PIN for\nquick login',
      AppKeys.verifyPasscodeSubtitle: 'Enter your PIN\nto confirm',
      AppKeys.changePasscodeTitle: 'Change PIN',
      AppKeys.enterCurrentPasscodeTitle: 'Enter Current PIN',
      AppKeys.passcodeContinue: 'Continue',
      AppKeys.passcodeUnlock: 'Unlock',
      AppKeys.passcodeSkip: 'Skip',
      AppKeys.passcodeRemove: 'Remove PIN',
      AppKeys.passcodeSetUp: 'Set Up PIN',
      AppKeys.passcodeChange: 'Change PIN',
      AppKeys.passcodeMismatch: 'PINs do not match. Please try again.',
      AppKeys.passcodeIncorrect: 'Incorrect PIN. Please try again.',
      AppKeys.passcodeSaveFailed: 'Could not save PIN. Please try again.',
      AppKeys.passcodeSessionExpired:
          'Your login session expired. Please log in again.',
      AppKeys.passcodeRemoveFailed: 'Could not remove PIN. Please try again.',
      AppKeys.passcodeSet: 'PIN created.',
      AppKeys.passcodeChanged: 'PIN changed.',
      AppKeys.passcodeRemoved: 'PIN removed.',
      AppKeys.missingAccount: 'Missing account information.',
      AppKeys.accountNameRequired: 'Please enter an account name.',
      AppKeys.accountUpdated: 'Account updated.',
      AppKeys.accountUpdateFailed: 'Could not update account.',
      AppKeys.imagePickFailed: 'Could not choose an image now.',
      AppKeys.profileOptionsMissingAccount:
          'No account information to load options.',
      AppKeys.profileOptionsLoadFailed: 'Failed to load profile options.',
      AppKeys.schoolOptionsLoadFailed: 'Failed to load schools.',
      AppKeys.reloadOptions: 'Reload options',
      AppKeys.missingProfileName: 'Please enter a full name.',
      AppKeys.missingProfileSelections:
          'Please select all required information.',
      AppKeys.missingProfileId: 'This profile is missing profile_id.',
      AppKeys.profileCreateFailed:
          'Could not create profile. Please try again.',
      AppKeys.profileUpdateFailed:
          'Could not update profile. Please try again.',
      AppKeys.deleteProfileTitle: 'Delete profile?',
      AppKeys.deleteProfileMessage:
          'Are you sure you want to delete this profile?',
      AppKeys.profileDeleted: 'Profile deleted.',
      AppKeys.profileDeleteFailed:
          'Could not delete profile. Please try again.',
      AppKeys.username: 'Username',
      AppKeys.fullName: 'Full Name',
      AppKeys.studentNameHint: "Enter student's full name",
      AppKeys.parentProfileNameHint: "Enter parent's full name",
      AppKeys.phoneNumber: 'Phone Number',
      AppKeys.email: 'Email',
      AppKeys.parentProfilePhoneHint: "Enter parent's phone number",
      AppKeys.parentProfileEmailHint: "Enter parent's email",
      AppKeys.grade: 'Grade',
      AppKeys.program: 'Program',
      AppKeys.learningProgram: 'Learning Program',
      AppKeys.semester: 'Semester',
      AppKeys.chooseSchool: 'Choose school',
      AppKeys.chooseGrade: 'Choose grade',
      AppKeys.chooseProgram: 'Choose program',
      AppKeys.chooseSemester: 'Choose semester',
      AppKeys.noSchools: 'No schools to show.',
      AppKeys.active: 'ACTIVE',
      AppKeys.switchingProfile: 'Switching profile...',
      AppKeys.switchingLanguage: 'Changing language...',
      AppKeys.parentInfoTitle: 'Parent information',
      AppKeys.parentChildrenCount: 'My children ({count})',
      AppKeys.profileRole: 'Role',
      AppKeys.roleStudent: 'Student',
      AppKeys.roleParent: 'Parent',
      AppKeys.roleTeacher: 'Teacher',
      AppKeys.belovedChild: 'Little learner',
      AppKeys.notSelected: 'Not selected',
      AppKeys.teacherFallback: 'Teacher',
      AppKeys.teacherMissingProfileId: 'Teacher profile is missing profile_id.',
      AppKeys.teacherClassOpenFailed: 'Could not open this class.',
      AppKeys.teacherWelcomeBack: 'WELCOME BACK',
      AppKeys.teacherHeroTitle: 'Ready for a new day',
      AppKeys.teacherHeroSubtitle: 'prepared to learn more',
      AppKeys.teacherYourClasses: 'Your classes',
      AppKeys.teacherCreateNewClass: 'Create New Class',
      AppKeys.teacherCompleteProfile: 'Complete Profile',
      AppKeys.teacherClassFallback: 'Class',
      AppKeys.teacherStudentCount: '{count} students',
      AppKeys.teacherEnterClass: 'Enter Class',
      AppKeys.teacherReportTitle: 'Report',
      AppKeys.teacherReportComingSoon: 'Class reports are coming soon',
      AppKeys.teacherReportPlaceholder:
          'Numi is preparing learning insights for teachers.',
      AppKeys.teacherCreateClassTitle: 'Create Class',
      AppKeys.teacherCreateOptionsFailed: 'Failed to load class options.',
      AppKeys.teacherClassMissingInfo: 'Please enter all class information.',
      AppKeys.teacherClassImageLabel: 'Class image',
      AppKeys.teacherGradeLevel: 'Grade level',
      AppKeys.teacherClassName: 'Class name',
      AppKeys.teacherClassNameHint: 'Example: 1A2, 2A3,...',
      AppKeys.teacherClassDescription: 'Class description (optional)',
      AppKeys.teacherClassDescriptionHint: 'Introduce the class goals...',
      AppKeys.teacherCreating: 'Creating...',
      AppKeys.teacherCreate: 'Create',
      AppKeys.teacherNoOptions: 'No options available',
      AppKeys.teacherClassDetailTitle: 'Class',
      AppKeys.teacherProgramFallback: 'Program',
      AppKeys.teacherDescriptionFallback: 'Class information',
      AppKeys.teacherClassInfoFallback: 'Class',
      AppKeys.teacherClassHideLess: 'Hide details',
      AppKeys.teacherCopiedClassLink: 'Class link copied.',
      AppKeys.teacherCopiedClassCode: 'Class code copied.',
      AppKeys.profileIdCopied: 'Profile ID copied.',
      AppKeys.profileCodeLabel: 'Code',
      AppKeys.profileCodeCopied: 'Profile code copied.',
      AppKeys.teacherMemberManagement: 'Manage members',
      AppKeys.teacherMemberSummary:
          '{members} members\n{requests} new requests',
      AppKeys.teacherMemberSummaryNoRequests: '{members} members',
      AppKeys.teacherMembersTitle: 'Members',
      AppKeys.teacherJoinRequests: 'Join requests ({count})',
      AppKeys.teacherNoJoinRequests: 'No join requests yet.',
      AppKeys.teacherPendingApproval: 'Pending approval',
      AppKeys.teacherJoinedStudentsTitle: 'Joined students ({count})',
      AppKeys.teacherSearchStudentTitle: 'Add students',
      AppKeys.teacherSearchStudentHint: 'Enter student name or ID',
      AppKeys.teacherNoStudentResults: 'No matching students found.',
      AppKeys.teacherSearchStudentFailed: 'Student search failed.',
      AppKeys.teacherSelectedStudents: '{count} students selected',
      AppKeys.teacherSendInviteRequest: 'Send invite',
      AppKeys.teacherInviteRequestQueued: 'Invite sent to {count} students.',
      AppKeys.teacherTwoMinutesAgo: '2 minutes ago',
      AppKeys.teacherFiveMinutesAgo: '5 minutes ago',
      AppKeys.teacherClassFunctions: 'Class Functions',
      AppKeys.teacherAssignments: 'Assignments',
      AppKeys.teacherAssessments: 'Assessment',
      AppKeys.teacherCreatedAssignments: 'Created assignments',
      AppKeys.teacherCreatedAssessments: 'Created assessments',
      AppKeys.teacherAssignmentSearchHint: 'Search ...',
      AppKeys.teacherAssignmentNewest: 'Newest',
      AppKeys.teacherAssignmentListLoadFailed: 'Failed to load assignments.',
      AppKeys.teacherAssessmentListLoadFailed: 'Failed to load assessments.',
      AppKeys.teacherAssignmentDetailLoadFailed:
          'Failed to load assignment details.',
      AppKeys.teacherAssessmentDetailLoadFailed:
          'Failed to load assessment details.',
      AppKeys.teacherAssignmentCreateFailed:
          'Could not create assignment. Please try again.',
      AppKeys.teacherAssessmentCreateFailed:
          'Could not create assessment. Please try again.',
      AppKeys.teacherAssignmentPickerSoon:
          'This selector is coming soon. You can still create the assignment.',
      AppKeys.teacherNoAssignments: 'No assignments yet.',
      AppKeys.teacherNoAssessments: 'No assessments yet.',
      AppKeys.teacherAssignmentGeometryTitle: 'Homework: Basic geometry',
      AppKeys.teacherAssignmentId: 'ID: {id}',
      AppKeys.teacherCreateAssignmentSoon:
          'Assignment creation is coming soon.',
      AppKeys.teacherAssignmentClassName: 'Math 1A2',
      AppKeys.teacherAssignmentReviewTitle: 'Review Homework',
      AppKeys.teacherAssignmentChapterRange: 'Chapter 3, Lessons 5-6',
      AppKeys.teacherAssignmentDueLabel: 'DUE DATE',
      AppKeys.teacherAssignmentDueValue: '21:00 05/31/2026',
      AppKeys.teacherAssignmentQuestionCountLabel: 'QUESTIONS',
      AppKeys.teacherAssignmentQuestionCountValue: '10 questions',
      AppKeys.teacherAssignmentQuestionCountFormat: '{count} questions',
      AppKeys.teacherAssignmentQuestionContent: 'Question content',
      AppKeys.teacherAssignmentQuestionNumber: 'Question {number}',
      AppKeys.teacherAssignmentEquationPrompt:
          'Solve the equation x² - 5x + 6 = 0.',
      AppKeys.teacherCreateAssignmentTitle: 'Create Assignment',
      AppKeys.teacherCreateAssessmentTitle: 'Create Assessment',
      AppKeys.teacherAssignmentClassOption: 'Class 2A1',
      AppKeys.teacherAssignmentSelectClass: 'Select classroom',
      AppKeys.teacherAssignmentClassSummaryName: 'Math A1',
      AppKeys.teacherAssignmentClassStudentCount: '32 Students',
      AppKeys.teacherAssignmentClassStudentCountFormat: '{count} Students',
      AppKeys.teacherAssignmentClassGrade: 'Grade 1',
      AppKeys.teacherAssignmentClassProgram: 'Canh Dieu',
      AppKeys.teacherAssignmentClassDescription: 'Special class',
      AppKeys.teacherAssignmentVolumeOne: 'Book 1',
      AppKeys.teacherAssignmentVolumeTwo: 'Book 2',
      AppKeys.teacherAssignmentTitleHint: 'Title',
      AppKeys.teacherAssessmentTitleHint: 'Assessment title',
      AppKeys.teacherAssignmentProgramLabel: 'Program',
      AppKeys.teacherAssignmentProgramValue: 'Canh Dieu 1',
      AppKeys.teacherAssignmentProgramRequired: 'Please select a program.',
      AppKeys.teacherAssignmentPublishLabel: 'Visibility',
      AppKeys.teacherAssignmentVisibilityPublic: 'PUBLIC',
      AppKeys.teacherAssignmentVisibilityPrivate: 'PRIVATE',
      AppKeys.teacherAssignmentDeadline: 'Deadline',
      AppKeys.teacherAssignmentStartDateHint: 'Start date and time',
      AppKeys.teacherAssignmentEndDateHint: 'End date and time',
      AppKeys.teacherAssignmentStartDateRequired: 'Please select a start date.',
      AppKeys.teacherAssignmentEndDateRequired: 'Please select an end date.',
      AppKeys.teacherAssignmentFutureDateRequired:
          'The selected date must be in the future.',
      AppKeys.teacherAssignmentEndAfterStart:
          'End date must be after start date.',
      AppKeys.teacherAssignmentChapterLabel: 'Chapter',
      AppKeys.teacherAssignmentLessonLabel: 'Lesson',
      AppKeys.teacherAssignmentDescriptionLabel: 'Description',
      AppKeys.teacherAssignmentDescriptionHint: 'Additional description',
      AppKeys.teacherAssessmentDescriptionHint: 'Assessment description',
      AppKeys.teacherAssignmentCreated: 'Assignment created.',
      AppKeys.teacherAssessmentCreated: 'Assessment created.',
      AppKeys.teacherJoinedStudents: 'Joined students ({count})',
      AppKeys.teacherNoJoinedStudents: 'No students have joined yet.',
      AppKeys.teacherStudentFallback: 'Student',
      AppKeys.teacherJustJoined: 'Just joined',
      AppKeys.profileTeacherNameHint: 'Enter teacher name',
      AppKeys.profileIdTypeLabel: 'Document type',
      AppKeys.profileIdTypeHint: 'Choose document type',
      AppKeys.profileIdTypeNone: 'None',
      AppKeys.profileIdValueLabel: 'ID',
      AppKeys.profileTeacherIdHint: 'Enter teacher staff ID or personal ID',
      AppKeys.profileStudentIdHint: 'Enter student record ID',
      AppKeys.idTypeMoetLabel: 'Student record ID',
      AppKeys.idTypeTeacherMoetLabel: 'Teacher staff ID',
      AppKeys.idTypePublicIdLabel: 'Personal identification number',
      AppKeys.noAccountForGrades: 'No account information to load grades.',
      AppKeys.gradeLoadFailed: 'Failed to load grades.',
      AppKeys.gradeQuestionTitle: 'Which grade is your child\nin?',
      AppKeys.generateTestFailed: 'Failed to create test. Please try later.',
      AppKeys.noGrades: 'No grades to show.',
      AppKeys.createQuestionFailed:
          'Could not create questions. Please try again.',
      AppKeys.missingQuizToSubmit: 'Could not find a test to submit.',
      AppKeys.submitQuizFailed: 'Failed to submit. Please try again.',
      AppKeys.unansweredSubmitTitle: 'Some questions are unanswered',
      AppKeys.unansweredSubmitMessage: 'Are you sure you want to submit now?',
      AppKeys.stayUpper: 'STAY',
      AppKeys.submitUpper: 'SUBMIT',
      AppKeys.submittingForYou: 'Numi is submitting your test...',
      AppKeys.generatingAssessment: 'Let Numi create your test',
      AppKeys.aiChallenge: 'AI Challenge',
      AppKeys.questionProgress: 'QUESTION {current}/{total}',
      AppKeys.previousQuestionUpper: 'PREVIOUS',
      AppKeys.submittingUpper: 'SUBMITTING',
      AppKeys.testAgainCreateMissingQuiz: 'Could not find the previous test.',
      AppKeys.testAgainCreateFailed:
          'Could not create a new test. Please try again.',
      AppKeys.testAgainDialogTitle: 'New test failed',
      AppKeys.excellentResultTitle: 'Excellent',
      AppKeys.excellentResultMessage: '',
      AppKeys.generatingNewQuiz: 'Numi is creating a new test...',
      AppKeys.assessmentResultTitle: 'Result',
      AppKeys.scoreUpper: 'SCORE',
      AppKeys.numiAiReview: 'Numi AI review',
      AppKeys.defaultAiReview:
          'Your child did very well with addition. Keep going, and practice subtraction with regrouping a little more.',
      AppKeys.defaultAiReviewHighlight: 'addition',
      AppKeys.assessmentUpper: 'Review',
      AppKeys.practiceUpper: 'Practice',
      AppKeys.authPhoneCheckFailed: 'Could not check this phone number.',
      AppKeys.signupOtpFailed: 'Could not send signup OTP. Please try again.',
      AppKeys.loginOtpFailed: 'Could not send OTP. Please try again.',
      AppKeys.invalidOtp: 'The OTP is incorrect. Please try again.',
      AppKeys.missingOtpUser: 'OTP response is missing user information.',
      AppKeys.verifyOtpFailed: 'Could not verify OTP. Please try again.',
      AppKeys.childNameRequired: "Please enter your child's name.",
      AppKeys.signupFailed: 'Could not sign up. Please try again.',
      AppKeys.quizHasNoQuestions: 'Quiz has no questions.',
      AppKeys.missingUserOrProfileForHistory:
          'Missing user or profile to load history.',
      AppKeys.missingQuizIdShort: 'Missing quiz ID.',
      AppKeys.apiBaseUrlMissing: 'API_BASE_URL is not configured.',
      AppKeys.invalidServerResponse: 'Invalid server response.',
      AppKeys.apiConnectTimeout: 'API connection timed out.',
      AppKeys.apiReceiveTimeout: 'API response timed out.',
      AppKeys.apiConnectFailed: 'Could not connect to API: {message}',
      AppKeys.apiBadCertificate: 'Invalid API certificate.',
      AppKeys.apiRequestCanceled: 'Request was canceled.',
      AppKeys.apiConnectionFailed: 'Could not connect to API.',
    },
  };

  static Map<String, String> getAll(AppLanguage language) {
    return _localizedValues[language.lookupCode] ?? _localizedValues['vi']!;
  }

  static String current(String key) {
    return getAll(AppLanguageState.current)[key] ?? key;
  }

  static String currentFormat(String key, Map<String, Object?> values) {
    var text = current(key);
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', entry.value?.toString() ?? '');
    }
    return text;
  }
}
