import 'app_keys.dart';
import 'app_language.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      AppKeys.appName: 'NUMI',
      AppKeys.loading: 'Đang tải...',
      AppKeys.close: 'Đóng',
      AppKeys.cancel: 'Hủy',
      AppKeys.save: 'Lưu',
      AppKeys.retry: 'Thử lại',
      AppKeys.retryUpper: 'THỬ LẠI',
      AppKeys.delete: 'Xóa',
      AppKeys.update: 'Cập nhật',
      AppKeys.add: 'Thêm',
      AppKeys.back: 'Quay lại',
      AppKeys.skipUpper: 'BỎ QUA',
      AppKeys.continueUpper: 'TIẾP TỤC',
      AppKeys.language: 'Ngôn ngữ',
      AppKeys.languageTitle: 'Ngôn Ngữ',
      AppKeys.languageVietnamese: 'Tiếng Việt',
      AppKeys.languageEnglish: 'English',
      AppKeys.welcomeTitlePrefix: 'Học Toán cùng\n',
      AppKeys.welcomeTitleN: 'NUMI',
      AppKeys.welcomeSubtitlePrefix: 'Hãy cùng Numi',
      AppKeys.welcomeSubtitle: 'trở thành "phù thủy" tính toán nhé!',
      AppKeys.start: 'BẮT ĐẦU',
      AppKeys.phoneLoginTitle: 'Số điện thoại',
      AppKeys.phoneLoginSubtitle: 'Nhập số điện thoại để bắt đầu cùng NUMI.',
      AppKeys.phoneNumberUpper: 'SỐ ĐIỆN THOẠI',
      AppKeys.phoneHint: 'Nhập số điện thoại',
      AppKeys.chooseCountry: 'Chọn quốc gia',
      AppKeys.continueLabel: 'Tiếp tục',
      AppKeys.creatingAccount: 'Đang tạo tài khoản...',
      AppKeys.checking: 'Đang kiểm tra...',
      AppKeys.phoneRequired: 'Vui lòng nhập số điện thoại.',
      AppKeys.invalidPhone: 'Số điện thoại chưa hợp lệ.',
      AppKeys.phoneTooShort: 'Số điện thoại chưa đủ ký tự.',
      AppKeys.restoringSession: 'Đang kiểm tra phiên đăng nhập...',
      AppKeys.newAccountPrompt: 'Đây là tài khoản MỚI. Tiếp tục đăng ký?',
      AppKeys.signup: 'Đăng ký',
      AppKeys.login: 'Đăng nhập',
      AppKeys.otpWithin30Seconds: 'Bạn sẽ nhận được mã trong vòng 30 giây',
      AppKeys.otpTitle: 'MÃ XÁC NHẬN',
      AppKeys.otpSentMessage: 'Mã OTP vừa gửi: {code}',
      AppKeys.otpConfirming: 'Đang xác thực...',
      AppKeys.otpConfirm: 'Xác nhận  →',
      AppKeys.resendOtp: 'Gửi lại mã',
      AppKeys.resendOtpAfter: 'Gửi lại mã sau {seconds} giây',
      AppKeys.signupNameHint: 'Nhập tên',
      AppKeys.signupEmailHint: 'Nhập email',
      AppKeys.signupNameLabel: 'Name',
      AppKeys.signupEmailLabel: 'Email',
      AppKeys.signupRoleLabel: 'Bạn là',
      AppKeys.signupRoleParent: 'Phụ huynh',
      AppKeys.signupRoleTeacher: 'Giáo viên',
      AppKeys.signupEmailDescription:
          'Nhập email để theo dõi kết quả kiểm tra và hành\ntrình học tập của bé',
      AppKeys.avatarUpper: 'ẢNH ĐẠI DIỆN',
      AppKeys.chooseAvatar: 'Chọn ảnh đại diện',
      AppKeys.signingUp: 'Đang đăng ký...',
      AppKeys.navHome: 'HOME',
      AppKeys.navReview: 'ÔN TẬP',
      AppKeys.navHistory: 'LỊCH SỬ',
      AppKeys.navSettings: 'CÀI ĐẶT',
      AppKeys.student: 'HỌC SINH',
      AppKeys.assessment: 'KIỂM TRA',
      AppKeys.assessmentDescription:
          'Cùng AI kiểm tra khả năng toán học\nvượt trội riêng bạn.',
      AppKeys.startNow: 'Bắt đầu ngay',
      AppKeys.practice: 'Luyện tập',
      AppKeys.yourAchievement: 'Thành tích của bạn',
      AppKeys.viewAllUpper: 'XEM TẤT CẢ',
      AppKeys.progressAchievementTitle: 'Tiến độ vượt bậc',
      AppKeys.todayCompletedExercises: 'Đã hoàn thành 12 bài tập hôm nay',
      AppKeys.reviewTitle: 'Lộ trình học tập',
      AppKeys.exercises: 'Bài tập',
      AppKeys.days: 'Ngày',
      AppKeys.noAccountForProfile: 'Chưa có thông tin tài khoản để tải hồ sơ.',
      AppKeys.noAccountForHistory:
          'Chưa có thông tin tài khoản để tải lịch sử.',
      AppKeys.profileLoadFailed: 'Tải hồ sơ thất bại.',
      AppKeys.chapterMissingProfileInfo:
          'Hồ sơ thiếu lớp, chương trình hoặc học kỳ.',
      AppKeys.chapterLoadFailed: 'Tải danh sách chương thất bại.',
      AppKeys.profileLoadErrorTitle: 'Không tải được hồ sơ',
      AppKeys.noProfileTitle: 'Chưa có hồ sơ',
      AppKeys.noProfileMessage: 'Bạn có thể thêm hồ sơ học tập cho bé.',
      AppKeys.addProfile: 'Thêm hồ sơ',
      AppKeys.chapterLoadErrorTitle: 'Không tải được chương',
      AppKeys.noChapterTitle: 'Chưa có chương',
      AppKeys.noChapterMessage: 'Chưa có lộ trình ôn tập cho hồ sơ này.',
      AppKeys.test: 'Kiểm tra',
      AppKeys.startTest: 'Bắt đầu kiểm tra ({count})',
      AppKeys.clearSelection: 'Bỏ chọn',
      AppKeys.startChapterTestMessage: 'Bắt đầu kiểm tra chương {chapter}.',
      AppKeys.startSelectedTestMessage: 'Bắt đầu kiểm tra {count} chương.',
      AppKeys.chapter: 'Chương',
      AppKeys.lessons: 'bài học',
      AppKeys.chapterNumber: 'Chương {number}',
      AppKeys.lockedLessonMessage: 'Bài {number}: {title} sẽ mở sau.',
      AppKeys.historyTitle: 'Lịch Sử',
      AppKeys.searchHint: 'Tìm kiếm ...',
      AppKeys.assessmentTab: 'Kiểm tra',
      AppKeys.practiceTab: 'Luyện tập',
      AppKeys.historyLoadFailed: 'Tải lịch sử thất bại.',
      AppKeys.historyLoadErrorTitle: 'Chưa tải được lịch sử',
      AppKeys.noHistoryTitle: 'Chưa có bài phù hợp',
      AppKeys.noHistoryMessage: 'Đổi từ khóa để xem các bài khác.',
      AppKeys.missingQuizId: 'Bài kiểm tra này thiếu quiz_id.',
      AppKeys.incomplete: 'Chưa xong',
      AppKeys.mathAssessment: 'Bài kiểm tra Toán',
      AppKeys.mathPractice: 'Bài luyện tập Toán',
      AppKeys.mathReview: 'Bài ôn tập Toán',
      AppKeys.excellent: 'Tuyệt vời!',
      AppKeys.good: 'Tốt',
      AppKeys.niceTry: 'Cố gắng tốt',
      AppKeys.failed: 'Chưa đạt',
      AppKeys.quizDetailLoadFailed: 'Tải chi tiết bài kiểm tra thất bại.',
      AppKeys.quizDetailTitle: 'Chi Tiết Bài Kiểm Tra',
      AppKeys.emptyQuizQuestions: 'Bài kiểm tra chưa có câu hỏi.',
      AppKeys.totalQuestions: 'Tổng câu',
      AppKeys.correct: 'Đúng',
      AppKeys.incorrect: 'Sai',
      AppKeys.time: 'Thời gian',
      AppKeys.questionNumber: 'Câu {number}',
      AppKeys.showAnswerUpper: 'ĐÁP ÁN',
      AppKeys.hideAnswerUpper: 'ẨN ĐÁP ÁN',
      AppKeys.noAnswer: 'Chưa có đáp án.',
      AppKeys.answer: 'Đáp án: {answer}',
      AppKeys.quizDetailErrorTitle: 'Không tải được chi tiết bài kiểm tra.',
      AppKeys.settingsTitle: 'Cài Đặt',
      AppKeys.accountTitle: 'Tài Khoản',
      AppKeys.profileTitle: 'Hồ Sơ',
      AppKeys.addProfileTitle: 'Thêm Hồ Sơ',
      AppKeys.updateProfileTitle: 'Cập Nhật Hồ Sơ',
      AppKeys.accountMenuTitle: 'Tài Khoản',
      AppKeys.accountMenuSubtitle: 'Quản lý thông tin tài khoản',
      AppKeys.profileMenuTitle: 'Hồ Sơ',
      AppKeys.profileMenuSubtitle: 'Xem và chỉnh sửa hồ sơ',
      AppKeys.logout: 'Logout',
      AppKeys.logoutSubtitle: 'Đăng xuất khỏi tài khoản',
      AppKeys.missingAccount: 'Thiếu thông tin tài khoản.',
      AppKeys.accountNameRequired: 'Vui lòng nhập tên tài khoản.',
      AppKeys.accountUpdated: 'Đã cập nhật tài khoản.',
      AppKeys.accountUpdateFailed: 'Không thể cập nhật tài khoản.',
      AppKeys.imagePickFailed: 'Không thể chọn ảnh lúc này.',
      AppKeys.profileOptionsMissingAccount:
          'Chưa có thông tin tài khoản để tải lựa chọn.',
      AppKeys.profileOptionsLoadFailed: 'Tải lựa chọn hồ sơ thất bại.',
      AppKeys.reloadOptions: 'Tải lại lựa chọn',
      AppKeys.missingProfileName: 'Vui lòng nhập họ tên.',
      AppKeys.missingProfileSelections: 'Vui lòng chọn đủ thông tin.',
      AppKeys.missingProfileId: 'Hồ sơ này thiếu profile_id.',
      AppKeys.profileCreateFailed: 'Không thể tạo hồ sơ. Vui lòng thử lại.',
      AppKeys.profileUpdateFailed:
          'Không thể cập nhật hồ sơ. Vui lòng thử lại.',
      AppKeys.deleteProfileTitle: 'Xóa hồ sơ?',
      AppKeys.deleteProfileMessage:
          'Bạn có chắc muốn delete profile này không?',
      AppKeys.profileDeleted: 'Đã xóa hồ sơ.',
      AppKeys.profileDeleteFailed: 'Không thể xóa hồ sơ. Vui lòng thử lại.',
      AppKeys.username: 'Username',
      AppKeys.fullName: 'Họ Tên',
      AppKeys.studentNameHint: 'Nhập họ tên học sinh',
      AppKeys.phoneNumber: 'Số Điện Thoại',
      AppKeys.email: 'Email',
      AppKeys.grade: 'Lớp',
      AppKeys.program: 'Chương Trình',
      AppKeys.learningProgram: 'Chương Trình Học',
      AppKeys.semester: 'Học kỳ',
      AppKeys.chooseGrade: 'Chọn lớp',
      AppKeys.chooseProgram: 'Chọn chương trình',
      AppKeys.chooseSemester: 'Chọn học kỳ',
      AppKeys.active: 'ACTIVE',
      AppKeys.belovedChild: 'Bé yêu',
      AppKeys.notSelected: 'Chưa chọn',
      AppKeys.noAccountForGrades:
          'Chưa có thông tin tài khoản để tải danh sách lớp.',
      AppKeys.gradeLoadFailed: 'Tải danh sách lớp thất bại.',
      AppKeys.gradeQuestionTitle: 'Bé đang học lớp mấy\nnhỉ?',
      AppKeys.generateTestFailed: 'Tạo test thất bại. Vui lòng thử lại sau.',
      AppKeys.noGrades: 'Chưa có lớp học nào để hiển thị.',
      AppKeys.createQuestionFailed: 'Không thể tạo câu hỏi. Vui lòng thử lại.',
      AppKeys.missingQuizToSubmit: 'Không tìm thấy bài test để nộp.',
      AppKeys.submitQuizFailed: 'Nộp bài thất bại. Vui lòng thử lại.',
      AppKeys.unansweredSubmitTitle: 'Bạn có câu hỏi chưa trả lời',
      AppKeys.unansweredSubmitMessage: 'Bạn có chắc muốn nộp bài không?',
      AppKeys.stayUpper: 'Ở LẠI',
      AppKeys.submitUpper: 'NỘP BÀI',
      AppKeys.submittingForYou: 'đợi Numi nộp bài cho bạn nhé!',
      AppKeys.generatingAssessment: 'Để Numi tạo bài kiểm tra cho bạn nhé',
      AppKeys.aiChallenge: 'Thử thách AI',
      AppKeys.questionProgress: 'CÂU {current}/{total}',
      AppKeys.previousQuestionUpper: 'CÂU TRƯỚC',
      AppKeys.submittingUpper: 'ĐANG NỘP',
      AppKeys.testAgainCreateMissingQuiz: 'Không tìm thấy bài test trước đó.',
      AppKeys.testAgainCreateFailed: 'Không thể tạo bài mới. Vui lòng thử lại.',
      AppKeys.testAgainDialogTitle: 'Tạo bài mới thất bại',
      AppKeys.excellentResultTitle: 'Tuyệt vời!',
      AppKeys.excellentResultMessage:
          'Bé đã hoàn thành xuất sắc thử thách này.',
      AppKeys.generatingNewQuiz: 'đợi Numi tạo bài mới cho bạn nhé!',
      AppKeys.assessmentResultTitle: 'Kết quả thử thách',
      AppKeys.scoreUpper: 'ĐIỂM SỐ',
      AppKeys.numiAiReview: 'Numi AI nhận xét',
      AppKeys.defaultAiReview:
          'Bé làm rất tốt phần phép cộng, hãy tiếp tục phát huy nhé! Chúng ta chỉ cần luyện tập thêm một chút ở các phép trừ có nhớ thôi.',
      AppKeys.assessmentUpper: 'KIỂM TRA',
      AppKeys.practiceUpper: 'LUYỆN TẬP',
      AppKeys.authPhoneCheckFailed: 'Không thể kiểm tra số điện thoại.',
      AppKeys.signupOtpFailed: 'Không thể gửi OTP đăng ký. Vui lòng thử lại.',
      AppKeys.loginOtpFailed: 'Không thể gửi OTP. Vui lòng thử lại.',
      AppKeys.invalidOtp: 'Mã OTP không đúng. Vui lòng thử lại.',
      AppKeys.missingOtpUser: 'Response OTP thiếu thông tin user.',
      AppKeys.verifyOtpFailed: 'Không thể xác thực OTP. Vui lòng thử lại.',
      AppKeys.childNameRequired: 'Vui lòng nhập tên của bé.',
      AppKeys.signupFailed: 'Không thể đăng ký. Vui lòng thử lại.',
      AppKeys.quizHasNoQuestions: 'Quiz không có câu hỏi.',
      AppKeys.missingUserOrProfileForHistory:
          'Thiếu user hoặc profile để tải lịch sử.',
      AppKeys.missingQuizIdShort: 'Thiếu quiz ID.',
      AppKeys.apiBaseUrlMissing: 'Chưa cấu hình API_BASE_URL.',
      AppKeys.invalidServerResponse: 'Response từ server không hợp lệ.',
      AppKeys.apiConnectTimeout: 'Kết nối API quá thời gian chờ.',
      AppKeys.apiReceiveTimeout: 'API phản hồi quá thời gian chờ.',
      AppKeys.apiConnectFailed: 'Không kết nối được API: {message}',
      AppKeys.apiBadCertificate: 'Chứng chỉ API không hợp lệ.',
      AppKeys.apiRequestCanceled: 'Request đã bị hủy.',
      AppKeys.apiConnectionFailed: 'Không kết nối được API.',
    },
    'en': {
      AppKeys.appName: 'NUMI',
      AppKeys.loading: 'Loading...',
      AppKeys.close: 'Close',
      AppKeys.cancel: 'Cancel',
      AppKeys.save: 'Save',
      AppKeys.retry: 'Retry',
      AppKeys.retryUpper: 'RETRY',
      AppKeys.delete: 'Delete',
      AppKeys.update: 'Update',
      AppKeys.add: 'Add',
      AppKeys.back: 'Back',
      AppKeys.skipUpper: 'SKIP',
      AppKeys.continueUpper: 'CONTINUE',
      AppKeys.language: 'Language',
      AppKeys.languageTitle: 'Language',
      AppKeys.languageVietnamese: 'Tiếng Việt',
      AppKeys.languageEnglish: 'English',
      AppKeys.welcomeTitlePrefix: 'Learn math with\n',
      AppKeys.welcomeTitleN: 'NUMI',
      AppKeys.welcomeSubtitlePrefix: 'Join Numi',
      AppKeys.welcomeSubtitle: 'and become a math wizard!',
      AppKeys.start: 'START',
      AppKeys.phoneLoginTitle: 'Phone number',
      AppKeys.phoneLoginSubtitle: 'Enter your phone number to start with NUMI.',
      AppKeys.phoneNumberUpper: 'PHONE NUMBER',
      AppKeys.phoneHint: 'Enter phone number',
      AppKeys.chooseCountry: 'Choose country',
      AppKeys.continueLabel: 'Continue',
      AppKeys.creatingAccount: 'Creating account...',
      AppKeys.checking: 'Checking...',
      AppKeys.phoneRequired: 'Please enter a phone number.',
      AppKeys.invalidPhone: 'The phone number is invalid.',
      AppKeys.phoneTooShort: 'The phone number is too short.',
      AppKeys.restoringSession: 'Checking login session...',
      AppKeys.newAccountPrompt: 'This is a NEW account. Continue to sign up?',
      AppKeys.signup: 'Sign up',
      AppKeys.login: 'Log in',
      AppKeys.otpWithin30Seconds: 'You will receive a code within 30 seconds',
      AppKeys.otpTitle: 'VERIFICATION CODE',
      AppKeys.otpSentMessage: 'OTP code sent: {code}',
      AppKeys.otpConfirming: 'Verifying...',
      AppKeys.otpConfirm: 'Confirm  →',
      AppKeys.resendOtp: 'Resend code',
      AppKeys.resendOtpAfter: 'Resend code in {seconds}s',
      AppKeys.signupNameHint: 'Enter name',
      AppKeys.signupEmailHint: 'Enter email',
      AppKeys.signupNameLabel: 'Name',
      AppKeys.signupEmailLabel: 'Email',
      AppKeys.signupRoleLabel: 'You are',
      AppKeys.signupRoleParent: 'Parent',
      AppKeys.signupRoleTeacher: 'Teacher',
      AppKeys.signupEmailDescription:
          "Enter an email to follow your child's assessment results\nand learning journey",
      AppKeys.avatarUpper: 'AVATAR',
      AppKeys.chooseAvatar: 'Choose avatar',
      AppKeys.signingUp: 'Signing up...',
      AppKeys.navHome: 'HOME',
      AppKeys.navReview: 'REVIEW',
      AppKeys.navHistory: 'HISTORY',
      AppKeys.navSettings: 'SETTINGS',
      AppKeys.student: 'STUDENT',
      AppKeys.assessment: 'ASSESSMENT',
      AppKeys.assessmentDescription:
          'Use AI to check your unique\nmath strengths.',
      AppKeys.startNow: 'Start now',
      AppKeys.practice: 'Practice',
      AppKeys.yourAchievement: 'Your achievements',
      AppKeys.viewAllUpper: 'VIEW ALL',
      AppKeys.progressAchievementTitle: 'Great progress',
      AppKeys.todayCompletedExercises: 'Completed 12 exercises today',
      AppKeys.reviewTitle: 'Learning journey',
      AppKeys.exercises: 'Exercises',
      AppKeys.days: 'Days',
      AppKeys.noAccountForProfile: 'No account information to load profiles.',
      AppKeys.noAccountForHistory: 'No account information to load history.',
      AppKeys.profileLoadFailed: 'Failed to load profiles.',
      AppKeys.chapterMissingProfileInfo:
          'Profile is missing grade, program, or semester.',
      AppKeys.chapterLoadFailed: 'Failed to load chapters.',
      AppKeys.profileLoadErrorTitle: 'Could not load profiles',
      AppKeys.noProfileTitle: 'No profile yet',
      AppKeys.noProfileMessage:
          'You can add a learning profile for your child.',
      AppKeys.addProfile: 'Add profile',
      AppKeys.chapterLoadErrorTitle: 'Could not load chapters',
      AppKeys.noChapterTitle: 'No chapters',
      AppKeys.noChapterMessage:
          'No review journey is available for this profile.',
      AppKeys.test: 'Test',
      AppKeys.startTest: 'Start test ({count})',
      AppKeys.clearSelection: 'Clear',
      AppKeys.startChapterTestMessage: 'Starting test for chapter {chapter}.',
      AppKeys.startSelectedTestMessage: 'Starting test for {count} chapters.',
      AppKeys.chapter: 'Chapter',
      AppKeys.lessons: 'lessons',
      AppKeys.chapterNumber: 'Chapter {number}',
      AppKeys.lockedLessonMessage: 'Lesson {number}: {title} opens later.',
      AppKeys.historyTitle: 'History',
      AppKeys.searchHint: 'Search ...',
      AppKeys.assessmentTab: 'Assessment',
      AppKeys.practiceTab: 'Practice',
      AppKeys.historyLoadFailed: 'Failed to load history.',
      AppKeys.historyLoadErrorTitle: 'Could not load history',
      AppKeys.noHistoryTitle: 'No matching items',
      AppKeys.noHistoryMessage: 'Change the keyword to view other items.',
      AppKeys.missingQuizId: 'This test is missing quiz_id.',
      AppKeys.incomplete: 'Incomplete',
      AppKeys.mathAssessment: 'Math assessment',
      AppKeys.mathPractice: 'Math practice',
      AppKeys.mathReview: 'Math review',
      AppKeys.excellent: 'Excellent!',
      AppKeys.good: 'Good',
      AppKeys.niceTry: 'Nice try',
      AppKeys.failed: 'Failed',
      AppKeys.quizDetailLoadFailed: 'Failed to load test details.',
      AppKeys.quizDetailTitle: 'Test Details',
      AppKeys.emptyQuizQuestions: 'This test has no questions.',
      AppKeys.totalQuestions: 'Questions',
      AppKeys.correct: 'Correct',
      AppKeys.incorrect: 'Wrong',
      AppKeys.time: 'Time',
      AppKeys.questionNumber: 'Question {number}',
      AppKeys.showAnswerUpper: 'ANSWER',
      AppKeys.hideAnswerUpper: 'HIDE ANSWER',
      AppKeys.noAnswer: 'No answer available.',
      AppKeys.answer: 'Answer: {answer}',
      AppKeys.quizDetailErrorTitle: 'Could not load test details.',
      AppKeys.settingsTitle: 'Settings',
      AppKeys.accountTitle: 'Account',
      AppKeys.profileTitle: 'Profile',
      AppKeys.addProfileTitle: 'Add Profile',
      AppKeys.updateProfileTitle: 'Update Profile',
      AppKeys.accountMenuTitle: 'Account',
      AppKeys.accountMenuSubtitle: 'Manage account information',
      AppKeys.profileMenuTitle: 'Profile',
      AppKeys.profileMenuSubtitle: 'View and edit profiles',
      AppKeys.logout: 'Logout',
      AppKeys.logoutSubtitle: 'Sign out of your account',
      AppKeys.missingAccount: 'Missing account information.',
      AppKeys.accountNameRequired: 'Please enter an account name.',
      AppKeys.accountUpdated: 'Account updated.',
      AppKeys.accountUpdateFailed: 'Could not update account.',
      AppKeys.imagePickFailed: 'Could not choose an image now.',
      AppKeys.profileOptionsMissingAccount:
          'No account information to load options.',
      AppKeys.profileOptionsLoadFailed: 'Failed to load profile options.',
      AppKeys.reloadOptions: 'Reload options',
      AppKeys.missingProfileName: 'Please enter a full name.',
      AppKeys.missingProfileSelections:
          'Please select all required information.',
      AppKeys.missingProfileId: 'This profile is missing profile_id.',
      AppKeys.profileCreateFailed:
          'Could not create profile. Please try again.',
      AppKeys.profileUpdateFailed:
          'Could not update profile. Please try again.',
      AppKeys.deleteProfileTitle: 'Delete profile?',
      AppKeys.deleteProfileMessage:
          'Are you sure you want to delete this profile?',
      AppKeys.profileDeleted: 'Profile deleted.',
      AppKeys.profileDeleteFailed:
          'Could not delete profile. Please try again.',
      AppKeys.username: 'Username',
      AppKeys.fullName: 'Full Name',
      AppKeys.studentNameHint: "Enter student's full name",
      AppKeys.phoneNumber: 'Phone Number',
      AppKeys.email: 'Email',
      AppKeys.grade: 'Grade',
      AppKeys.program: 'Program',
      AppKeys.learningProgram: 'Learning Program',
      AppKeys.semester: 'Semester',
      AppKeys.chooseGrade: 'Choose grade',
      AppKeys.chooseProgram: 'Choose program',
      AppKeys.chooseSemester: 'Choose semester',
      AppKeys.active: 'ACTIVE',
      AppKeys.belovedChild: 'Little learner',
      AppKeys.notSelected: 'Not selected',
      AppKeys.noAccountForGrades: 'No account information to load grades.',
      AppKeys.gradeLoadFailed: 'Failed to load grades.',
      AppKeys.gradeQuestionTitle: 'Which grade is your child\nin?',
      AppKeys.generateTestFailed: 'Failed to create test. Please try later.',
      AppKeys.noGrades: 'No grades to show.',
      AppKeys.createQuestionFailed:
          'Could not create questions. Please try again.',
      AppKeys.missingQuizToSubmit: 'Could not find a test to submit.',
      AppKeys.submitQuizFailed: 'Failed to submit. Please try again.',
      AppKeys.unansweredSubmitTitle: 'Some questions are unanswered',
      AppKeys.unansweredSubmitMessage: 'Are you sure you want to submit now?',
      AppKeys.stayUpper: 'STAY',
      AppKeys.submitUpper: 'SUBMIT',
      AppKeys.submittingForYou: 'Numi is submitting your test...',
      AppKeys.generatingAssessment: 'Let Numi create your test',
      AppKeys.aiChallenge: 'AI Challenge',
      AppKeys.questionProgress: 'QUESTION {current}/{total}',
      AppKeys.previousQuestionUpper: 'PREVIOUS',
      AppKeys.submittingUpper: 'SUBMITTING',
      AppKeys.testAgainCreateMissingQuiz: 'Could not find the previous test.',
      AppKeys.testAgainCreateFailed:
          'Could not create a new test. Please try again.',
      AppKeys.testAgainDialogTitle: 'New test failed',
      AppKeys.excellentResultTitle: 'Excellent!',
      AppKeys.excellentResultMessage:
          'Your child completed this challenge beautifully.',
      AppKeys.generatingNewQuiz: 'Numi is creating a new test...',
      AppKeys.assessmentResultTitle: 'Challenge Result',
      AppKeys.scoreUpper: 'SCORE',
      AppKeys.numiAiReview: 'Numi AI review',
      AppKeys.defaultAiReview:
          'Your child did very well with addition. Keep going, and practice subtraction with regrouping a little more.',
      AppKeys.assessmentUpper: 'ASSESSMENT',
      AppKeys.practiceUpper: 'PRACTICE',
      AppKeys.authPhoneCheckFailed: 'Could not check this phone number.',
      AppKeys.signupOtpFailed: 'Could not send signup OTP. Please try again.',
      AppKeys.loginOtpFailed: 'Could not send OTP. Please try again.',
      AppKeys.invalidOtp: 'The OTP is incorrect. Please try again.',
      AppKeys.missingOtpUser: 'OTP response is missing user information.',
      AppKeys.verifyOtpFailed: 'Could not verify OTP. Please try again.',
      AppKeys.childNameRequired: "Please enter your child's name.",
      AppKeys.signupFailed: 'Could not sign up. Please try again.',
      AppKeys.quizHasNoQuestions: 'Quiz has no questions.',
      AppKeys.missingUserOrProfileForHistory:
          'Missing user or profile to load history.',
      AppKeys.missingQuizIdShort: 'Missing quiz ID.',
      AppKeys.apiBaseUrlMissing: 'API_BASE_URL is not configured.',
      AppKeys.invalidServerResponse: 'Invalid server response.',
      AppKeys.apiConnectTimeout: 'API connection timed out.',
      AppKeys.apiReceiveTimeout: 'API response timed out.',
      AppKeys.apiConnectFailed: 'Could not connect to API: {message}',
      AppKeys.apiBadCertificate: 'Invalid API certificate.',
      AppKeys.apiRequestCanceled: 'Request was canceled.',
      AppKeys.apiConnectionFailed: 'Could not connect to API.',
    },
  };

  static Map<String, String> getAll(AppLanguage language) {
    return _localizedValues[language.lookupCode] ?? _localizedValues['vi']!;
  }

  static String current(String key) {
    return getAll(AppLanguageState.current)[key] ?? key;
  }

  static String currentFormat(String key, Map<String, Object?> values) {
    var text = current(key);
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', entry.value?.toString() ?? '');
    }
    return text;
  }
}
